Develop
membraneframework/membrane_core pull request #287
Opened 2021-02-18 13:30 UTC by mat-hek

2021-03-31 10:15 UTC, AndrzejPodo requested changes

2021-03-31 10:15 UTC, AndrzejPodo commented on lib/membrane/core/parent/child_life_controller.ex
>        handle: error -> error
`:assert` error is not handled in `else`

2021-04-06 12:43 UTC, mat-hek commented
@AndrzejPodo I refactored the linking part, hope it's more intuitive now. Also added docs and specs. Only espec tests don't pass, though they're fixed in one of your PRs afaik.

2021-04-07 13:24 UTC, AndrzejPodo commented on lib/membrane/core/child/pad_controller.ex
> +      end
I'm wondering if the `direction` argument is necessary. It seems to be used only for validation purpose. Is there not enough information in `info`?

2021-04-07 13:33 UTC, AndrzejPodo commented on lib/membrane/core/parent/child_life_controller.ex
> +    end
It would be nice if there was a short docs here. Especially `LifecycleController.maybe_finish_playback_transition(state)` was not very clear to me at the first glance.

2021-04-07 13:39 UTC, AndrzejPodo commented on lib/membrane/core/parent/child_life_controller.ex
>    end
It would be nice if there was a short docs here. Especially `LifecycleController.maybe_finish_playback_transition(state)` was not very clear to me at the first glance.

2021-04-07 13:39 UTC, AndrzejPodo commented on lib/membrane/core/child/pad_controller.ex
> +      state =
I'm wondering if the `direction` argument is necessary. It seems to be used only for validation purpose. Is there not enough information in info?

2021-04-07 13:39 UTC, AndrzejPodo commented on lib/membrane/core/parent/link.ex
> +    |> Enum.reverse()
ok, good note.

2021-04-08 15:34 UTC, mat-hek commented on lib/membrane/core/child/pad_controller.ex
> +      state =
The direction argument is the direction determined from links specification, while the direction in `info` is the one specified in the element's pads specification. We need to ensure they match so that nobody links e.g. input as an output. You can see that a few lines below:
```
      info.direction != direction ->
        raise LinkError, """
        Invalid pad direction:
          expected: #{inspect(info.direction)},
          actual: #{inspect(direction)}
        """
```

2021-04-09 09:18 UTC, AndrzejPodo submitted a review, later dismissed

2021-05-05 08:32 UTC, andpodob approved these changes

2021-05-05 08:37 UTC, merged