Handle delay supply fix
membraneframework/membrane_core pull request #288
Opened 2021-03-12 13:38 UTC by AndrzejPodo

- Removes necessity of calling `DemandHandler.handle_delayed_demands()` after receiving a message.
- Replaces `delayed_demands Map` with `delayed_demands Set` after getting rid of sync/async delayed demand types

2021-03-31 12:57 UTC, mat-hek requested changes

2021-03-31 12:57 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
>    end
this is now only called by supply_demand, let's move the code there

2021-03-31 12:57 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
>    def delay_redemand(pad_ref, state) do
this is now only called by handle_redemand, let's move the code there

2021-03-31 12:57 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +        DemandController.handle_demand(pad_ref, 0, state)
calling `handle_redemand` would look better

2021-03-31 12:57 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +      {:ok, %State{state | supplying_demand?: false}}
seems redundant

2021-04-07 14:10 UTC, AndrzejPodo commented on lib/membrane/core/element/demand_handler.ex
> +      {:ok, %State{state | supplying_demand?: false}}
Which part do you mean?

2021-04-07 14:46 UTC, mat-hek requested changes

2021-04-07 14:46 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> -      handle_delayed_demands(state)
why remove that? seems still needed

2021-04-07 14:48 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +      {:ok, %State{state | supplying_demand?: false}}
![image](https://user-images.githubusercontent.com/16493463/113886464-faaba500-97c0-11eb-943e-109a7c324205.png)

2021-04-07 14:55 UTC, AndrzejPodo commented on lib/membrane/core/element/demand_handler.ex
> +      {:ok, %State{state | supplying_demand?: false}}
hm, but `handle_delayed_demands` calls `supply_demand` which calls `do_supply_demand` with `supplying_demand?: true`. I'm quite unsure if `supplying_demand?` is always `false` after all this calls.

2021-04-07 15:00 UTC, AndrzejPodo commented on lib/membrane/core/element/demand_handler.ex
> -      handle_delayed_demands(state)
if i remember well this recurrence call has been moved to `supply_demand`

2021-04-07 15:06 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +      {:ok, %State{state | supplying_demand?: false}}
If it was to be set to true after `handle_delayed_demands`, something would have to change it there. However, the only place where it changes is in `supply_demand` and it's changed back immediately, so I see no possibility that it remains true.

2021-04-07 15:08 UTC, AndrzejPodo commented on lib/membrane/core/element/demand_handler.ex
> +      {:ok, %State{state | supplying_demand?: false}}
Ok, I see, you're right.

2021-04-07 15:14 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> -      handle_delayed_demands(state)
Ok, I see... though it won't be sufficient if supply_demand results in more than one delayed demands

2021-04-08 07:43 UTC, AndrzejPodo commented on lib/membrane/core/element/demand_handler.ex
> -      handle_delayed_demands(state)
I see, good point.

2021-04-23 10:53 UTC, mat-hek approved these changes

2021-04-23 10:56 UTC, merged