Remove element message dispatcher
membraneframework/membrane_core pull request #289
Opened 2021-03-17 09:34 UTC by AndrzejPodo

Moves handling messages back to the Element module.

2021-04-27 17:49 UTC, mat-hek commented
@andpodob it seems this PR somehow contains changes from https://github.com/membraneframework/membrane_core/pull/288

2021-04-28 09:07 UTC, mat-hek requested changes

2021-04-28 09:07 UTC, mat-hek commented on lib/membrane/core/element.ex
> +    {{:error, reason}, state}
Please revisit if this is actually useful. `Membrane.Helper.GenServer.(no)reply` already handle logging. I don't think that wrapping error in that `{:cannot_handle_message, ..}` tuple adds any valuable information too.

2021-04-28 09:07 UTC, mat-hek commented on lib/membrane/core/element/action_handler.ex
> -    supply_demand(pad_ref, size, cb, params[:supplying_demand?] || false, state)
this was already reviewed and merged, wasn't it?

2021-05-19 10:22 UTC, andpodob commented on lib/membrane/core/element/action_handler.ex
> -    supply_demand(pad_ref, size, cb, params[:supplying_demand?] || false, state)
Yes, I think so.

2021-05-19 11:46 UTC, mat-hek commented on lib/membrane/core/element.ex
>    end
is this needed? `noreply` already handles logging

2021-06-23 08:41 UTC, mat-hek requested changes

2021-06-23 08:41 UTC, mat-hek commented on lib/membrane/core/element.ex
> +  defp handle_message_error(_message, _mode, reason, state) do
this function is useless now

2021-06-23 10:02 UTC, mat-hek requested changes

2021-06-23 10:02 UTC, mat-hek commented on lib/membrane/core/element.ex
> +        noreply({{:error, reason}, new_state}, state)
you could just do `noreply(result, state)`

2021-06-24 11:46 UTC, mat-hek approved these changes

2021-06-24 13:49 UTC, merged