add crash groups handling in pipeline
membraneframework/membrane_core pull request #292
Opened 2021-04-07 12:16 UTC by AndrzejPodo

2021-04-08 12:52 UTC, mat-hek requested changes

2021-04-08 12:52 UTC, mat-hek commented on lib/membrane/core/parent/message_dispatcher.ex
> +  def handle_message({:EXIT, pid, reason}, state) do
let's move that to a proper controller, for example the ChildLifeController

2021-04-08 12:52 UTC, mat-hek commented on lib/membrane/core/pipeline.ex
> +    Process.flag(:trap_exit, true)
There's a problem with this approach - the user may want to enable or disable trapping exits in their own code, and it seems impossible to both allow them to do so and trap exits from children. The alternative may be a separate process only for trapping exits and proxying exit events (seems complicated) or using monitors.

2021-04-08 12:52 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +        |> Bunch.Access.update_in([:links], &(&1 |> Enum.reject(fn link -> link in links end)))
Map.update! should be sufficient

2021-04-08 12:52 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +    res
`res` is needless

2021-04-08 12:52 UTC, mat-hek commented on test/support/child_crash_test/pipeline.ex
> +      end)
You can do better :P And format the code

2021-04-09 15:04 UTC, AndrzejPodo commented on lib/membrane/core/parent/message_dispatcher.ex
> +        members_pids |> Enum.each(&if Process.alive?(&1), do: GenServer.stop(&1, reason))
Waiting specific period of time after sending `:stop` requires some additional logic, let's leave that for next PR. So for now pipeline can behave as Supervisor in `:brutal_kill` and stop with `:kill` reason.

2021-04-09 15:07 UTC, AndrzejPodo commented on test/support/child_crash_test/pipeline.ex
> +      end)
What do mean?

2021-04-12 10:25 UTC, mat-hek commented on test/support/child_crash_test/pipeline.ex
> +      end)
For example use `Enum.chunk_by`

2021-04-12 13:22 UTC, mat-hek requested changes

2021-04-12 13:22 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/crash_group_handler.ex
> +  # for now only Pipeline.State has crash_groups field
handling it in bins should be fairly easy

2021-04-12 13:22 UTC, mat-hek commented on lib/membrane/core/parent/crash_group.ex
> +  """
either be move outside of the core or make it a comment and `@moduledoc false`

2021-04-12 14:03 UTC, AndrzejPodo commented on lib/membrane/core/parent/message_dispatcher.ex
> +
oh, I forgot to remove that, sorry, but remember it's still a draft ;)

2021-04-12 14:07 UTC, AndrzejPodo commented on lib/membrane/core/parent/crash_group.ex
> +  """
ok, I guess it should be kept inside the core as this is rather entirely for internal usage.

2021-04-13 11:58 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +      ### update link in state
seems unfixed

2021-04-13 11:58 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +    with :ok <- send_unlink(links) do
seems unfixed

2021-04-13 11:58 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +    end)
seems unfixed

2021-04-13 11:58 UTC, mat-hek commented on lib/membrane/core/parent/message_dispatcher.ex
> +  # when monitored child exited normally
seems unfixed

2021-04-14 13:53 UTC, mat-hek requested changes

2021-04-14 13:53 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +           |> Enum.each(&if Process.alive?(&1), do: GenServer.stop(&1, {:shutdown, :group_kill})) do
`with` is not needed

2021-04-14 13:53 UTC, mat-hek commented on test/support/child_crash_test/pipeline.ex
> +      end)
use `Enum.chunk_by`

2021-04-16 12:28 UTC, AndrzejPodo commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +    end)
Im wondering if I should send `:handle_unlink` to `:from` as well. @mat-hek can give some advice on that?

2021-04-16 15:15 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +    end)
I think you should unlink the pads that have to be unlinked, no matter if they're input or output.

2021-04-20 07:23 UTC, Qizot requested changes

2021-04-20 07:23 UTC, Qizot commented on lib/membrane/core/parent/child_life_controller/crash_group_handler.ex
> +    if group_name in state.crash_groups do
Are you sure you didn't mean `not in`?

2021-04-20 07:26 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller/crash_group_handler.ex
> +    if group_name in state.crash_groups do
ah yes, you're right, thanks!

2021-04-21 17:42 UTC, mat-hek requested changes

2021-04-21 17:42 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +    links_to_unlink =
```suggestion
    links_to_remove =
```

2021-04-21 17:42 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
>      end)
```suggestion
    Enum.each(links_to_unlink, fn %Link{to: to, from: from} ->
      cond do
        from.pid not in members_pids -> Message.send(from.pid, :handle_unlink, from.pad_ref)
        to.pid not in members_pids -> Message.send(to.pid, :handle_unlink, to.pad_ref)
        true -> :ok
      end
    end)
```

2021-04-21 17:42 UTC, mat-hek commented on test/support/child_crash_test/pipeline.ex
>        end)
```suggestion
      Enum.chunk_every(children_names, 2, 1, [:center_filter])
      |> Enum.map(fn [first_elem, second_elem] -> link(first_elem) |> to(second_elem) end)
```

2021-04-21 17:42 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +          {:ok | {:error, any}, Parent.state_t()}
This will always return `{:ok, state}`. Avoid using `any` as an error value, it's as bad as `any` for a successful result. We need to clean the core from such types, not introduce new ones ;) I also think we shouldn't return ok tuples if there's no error expected anymore, especially in the private API. Please pay ​special attention to that.

2021-04-22 10:59 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +          {:ok | {:error, any}, Parent.state_t()}
ok, good to know, because I've patterned after implementations of other similar functions :D

2021-04-22 11:03 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +          {:ok | {:error, any}, Parent.state_t()}
Yes, we used to do that and it turned out to be a mistake

2021-04-22 11:52 UTC, mat-hek approved these changes

2021-04-23 10:31 UTC, merged