pass messages not from child to handle_other
membraneframework/membrane_core pull request #300
Opened 2021-04-27 13:18 UTC by andpodob

Fix the issue of handling `:DOWN` messages from processes that are not children of pipeline. This PR makes `develop` to work properly when crash groups are not used. Crash groups are yet to be debugged.

2021-04-27 14:02 UTC, mat-hek requested changes

2021-04-27 14:02 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +      {:ok, state}
```suggestion
    with {:ok, child_name} <- child_by_pid(pid, state) do
       state = Bunch.Access.delete_in(state, [:children, child_name])
       state = remove_child_links(child_name, state)
       LifecycleController.maybe_finish_playback_transition(state)
```

2021-04-27 16:43 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller.ex
> +      {:ok, state}
`maybe_finish_playback_transition(state)` is having specs for return value like this: `{:ok | {:error, any}, Parent.state_t()}`, is that safe to just return result of `LifecycleController.maybe_finish_playback_transition(state)`?

2021-04-27 17:07 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +      {:ok, state}
Specs (and possibly error handling) for `maybe_finish_playback_transition` should be fixed, but the code I suggested works exactly the same way as yours, unless I'm missing something

2021-04-28 12:00 UTC, mat-hek requested changes

2021-04-28 12:00 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +              "Tried to handle child death that wasn't a child of that pipeline."
fix english :P

2021-04-28 12:00 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +         state = remove_child_links(child_name, state) do
assignments can be moved out of with

2021-04-28 12:00 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +              "Child  that was not a member of a group killed with :membrane_crash_group_kill."
```suggestion
              "Child that was not a member of a crash group killed with :membrane_crash_group_kill."
```

2021-04-28 12:20 UTC, mat-hek approved these changes

2021-04-28 12:25 UTC, merged