Pipeline handle group down
membraneframework/membrane_core pull request #302
Opened 2021-04-30 13:47 UTC by andpodob

2021-04-30 15:19 UTC, mat-hek requested changes
btw let's move CrashGroupHandler to membrane/core/parent

2021-05-04 11:10 UTC, mat-hek requested changes

2021-05-04 11:10 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +      Enum.map(group.members, fn member_pid ->
won't this be empty when we execute the callback?

2021-05-04 11:50 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller.ex
> +      Enum.map(group.members, fn member_pid ->
oops, I think you're right

2021-05-04 15:10 UTC, mat-hek commented on lib/membrane/core/parent/crash_group.ex
> +          dead_members: [pid()]
couldn't we just keep a list of element names here?

2021-05-05 08:38 UTC, andpodob commented on lib/membrane/core/parent/crash_group.ex
> +          dead_members: [pid()]
Ofc we can but we use this list to i.a. send messages to members. Keeping pids let us avoid necessity to change name to pid every time we send message.

2021-05-05 08:47 UTC, mat-hek commented on lib/membrane/core/parent/crash_group.ex
> +          dead_members: [pid()]
But using names makes it consistent with all the core and allows to do anything else without converting pid to name. However, crash groups are quite specific, because apart from sending messages, they get the monitor down signals, which are also identified by pids. That's why I'd stick to
- `members`, containing names of all the children in the group, no matter if alive or dead
- `alive_pids`, containing pids of members that are alive

2021-05-12 09:14 UTC, mat-hek requested changes

2021-05-12 09:14 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
>          Pipeline child crashed but was not a member of any crash group.
These clauses differ only by error handling, let's merge them

2021-05-12 09:14 UTC, mat-hek commented on lib/membrane/core/parent/crash_group.ex
> +  defstruct @enforce_keys ++ [members: [], alive_members: [], triggered?: false]
```suggestion
  defstruct @enforce_keys ++ [members: [], alive_members_pids: [], triggered?: false]
```

2021-05-12 09:14 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +      |> Enum.map(& &1.pid)
we can just operate on names
```suggestion
```

2021-05-12 09:14 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +        |> Bunch.Access.delete_in([:children, child_name])
we should do that when all the children from the crash group are dead

2021-05-12 09:14 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +        |> Bunch.Access.delete_in([:children, child_name])
as above

2021-05-12 09:14 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/crash_group_handler.ex
> +    }
use `update_in`

2021-05-12 09:14 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/crash_group_handler.ex
> +    if group_name in Map.keys(state.crash_groups) do
why do we allow passing a non-existing crash group?

2021-05-12 09:16 UTC, mat-hek commented
and fix CI

2021-05-12 14:38 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller.ex
> +        |> Bunch.Access.delete_in([:children, child_name])
Why? Doesn't it make some possibility for race condition then?

2021-05-12 15:01 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller/crash_group_handler.ex
> +    if group_name in Map.keys(state.crash_groups) do
sorry, debugging leftover

2021-05-13 10:17 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +          propagate_child_crash(state)
```suggestion
        {:error, :not_member} when reason == {:shutdown, :membrane_crash_group_kill} ->
          raise Membrane.PipelineError,
                "Child that was not a member of any crash group killed with :membrane_crash_group_kill."
        {:error, :not_member} ->
          Membrane.Logger.debug("""
          Pipeline child crashed but was not a member of any crash group.
          Terminating.
          """)

          propagate_child_crash(state)
```

2021-05-13 10:17 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/crash_group_handler.ex
> +          } = maybe_group
```suggestion
      Bunch.Access.update_in(state, [:crash_groups, group_name], fn 
          %CrashGroup{
            members: current_children_names,
            alive_members_pids: current_alive_members
          } = group ->
```

2021-05-13 10:17 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/crash_group_handler.ex
> +        else
```suggestion
        nil ->
```

2021-05-13 10:33 UTC, mat-hek approved these changes

2021-05-13 10:34 UTC, merged