More telemetry events
membraneframework/membrane_core pull request #308
Opened 2021-06-01 10:47 UTC by sheldak

Work in progress.

Current changes:
- `method` is now called `metric`
- `input_buffer_size_event` is now called `metric_event`
- added reporting `caps`
- added reporting `event`

Closes [Add more telemetry events #297](https://github.com/membraneframework/membrane_core/issues/297)

2021-06-01 14:12 UTC, Qizot requested changes

2021-06-01 14:12 UTC, Qizot commented on lib/membrane/core/element/caps_controller.ex
> +  defp report_caps(log_tag) do
Can you create a separate module for that to keep the telemery functions in one place? Would be easier to track all events and their reporting functions.

2021-06-01 14:12 UTC, Qizot commented on lib/membrane/core/element/event_controller.ex
> +  defp report_event(log_tag) do
Same as we report caps.

2021-06-04 10:07 UTC, sheldak commented on lib/membrane/core/element/caps_controller.ex
> +  defp report_caps(log_tag) do
Maybe in `Membrane.Telemetry`? What do you think about it?

2021-06-14 14:25 UTC, Qizot requested changes

2021-06-14 14:25 UTC, Qizot commented on lib/membrane/telemetry.ex
> +  * metric - metric name
```suggestion
  * metric - metric's name
```

2021-06-14 14:25 UTC, Qizot commented on lib/membrane/core/element/caps_controller.ex
> +    report_caps(inspect(pad_ref))
Do you need to wrap the `Membrane.Telemetry.report_metric` into a function? With this approach you are calling unnecessarily a function that will just return `:ok`. When using directly there won't event be code to run.

And I think if you just use it in a single place you don't have to wrap that call and it will look more descriptive.

2021-06-14 14:25 UTC, Qizot commented on lib/membrane/core/element/event_controller.ex
> +  defp report_event(log_tag) do
This thread is old but do the same thing as with caps, you probably don't need this function.

2021-06-14 14:47 UTC, Qizot approved these changes
Change this last think and otherwise LGTM

2021-06-14 14:47 UTC, Qizot commented on lib/membrane/telemetry.ex
> +          unquote(metric_event_name()),
I guess you can put directly the array here instead of having it in function call.

2021-06-14 15:11 UTC, merged