Release membrane_core v0.7.0
membraneframework/membrane_core pull request #310
Opened 2021-06-10 15:56 UTC by mickel8

### Release "Simply Pro Cub"

| Project | New Version |
|---|---|
| membrane_core | `0.7.0` |

<sup>proudly automated with <a href="https://github.com/membraneframework/sebex">Sebex</a></sup>

2021-06-11 14:49 UTC, mat-hek requested changes

2021-06-11 14:49 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +  @opaque link_builder_t :: link_builder_t()
shouldn't that be

```suggestion
  @opaque link_builder_t :: LinkBuilder.t()
```

please check if dialyzer passes

2021-06-11 15:03 UTC, mat-hek approved these changes
If dialyzer passes, we can merge. Btw we could add it to CI

2021-06-14 08:13 UTC, mat-hek submitted a review, later dismissed

2021-06-15 10:49 UTC, mat-hek requested changes

2021-06-15 10:49 UTC, mat-hek commented on lib/membrane/telemetry.ex
> +  defmacro report_new_link(from, to) do
I would instead provide a generic `report_metric_lazy(metric, function, log_tag)` that would accept a function calculating value instead of a value itself. Reporting links could use that instead of having a separate macro for that purpose.

2021-06-15 10:49 UTC, mat-hek commented on lib/membrane/telemetry.ex
> +            element_path: path,
```suggestion
            component_path: path,
```

2021-06-16 09:56 UTC, sheldak commented on lib/membrane/telemetry.ex
> +            element_path: path,
I can change that. It also requires changes in Reporter and Dashboard (due to change in DB I assume is necessary for consistence in naming - there is entire table called `element_paths` now, so I will change it to `component_paths`). 

Now, I think, is the best moment for any other naming changes if they are necessary, because I am already working on Reporter and Dashboard.

2021-06-16 15:42 UTC, mat-hek requested changes

2021-06-16 15:42 UTC, mat-hek commented on lib/membrane/telemetry.ex
> +  def report_new_link(from, to) do
The point of making `report_metric` accept function was to make this private, as it's only used inside the core. So let's move that to `Membrane.Core.Parent.Link`.

2021-06-16 15:52 UTC, sheldak commented on lib/membrane/telemetry.ex
> +  def report_new_link(from, to) do
Currently `report_measurement` accepts function. I wanted to separate metrics (events, caps, input buffer's sizes) from all measurements (both metrics and new links) so I have changed the name.

Okay, I can make `report_new_link` private and move to `Membrane.Core.Parent.Link`, but what about `report_metric` which is called from 3 places?

2021-06-17 08:51 UTC, mat-hek commented on lib/membrane/telemetry.ex
> +  def report_new_link(from, to) do
report_metric is generic, doesn't require awareness of core internals, and can be possibly used from outside of the core - so it can be public. Btw you could make two versions of report_metric - one accepting just a value, and the other accepting a function.

2021-06-18 11:23 UTC, mat-hek submitted a review, later dismissed

2021-06-21 07:59 UTC, mat-hek approved these changes

2021-06-21 08:02 UTC, merged