auto demand
membraneframework/membrane_core pull request #313
Opened 2021-06-22 12:35 UTC by mat-hek

2021-11-04 15:22 UTC, sax commented on lib/membrane/core/bin/pad_controller.ex
> +      end
Yeah, it'll be interesting if we can speed up the membrane_core internals, if new race conditions are exposed. So far we have not seen that in our optimizations branch, so 🤞🏻.

2021-11-05 16:06 UTC, andpodob requested changes

2021-11-05 16:06 UTC, andpodob commented on lib/membrane/pad_data.ex
> +            demand_pads: [],
WDYT about `:demanding_pads`, or simply `:output_pads`? I had a hard time connecting the name of this field with its purpose.

2021-11-08 10:44 UTC, andpodob commented on lib/membrane/core/element/demand_controller.ex
> +    %{demand: demand, toilet: toilet, demand_pads: demand_pads} =
We need to handle EOS by probably removing the pad from `demand_pads` to make `auto_demands_positive?` check work properly when one of the pads receives EOS.

2021-11-08 18:09 UTC, bblaszkow06 requested changes

2021-11-08 18:09 UTC, bblaszkow06 commented on lib/membrane/core/element/state.ex
> +      demand_size: 4000
Have you considered making it configurable?

2021-11-08 18:09 UTC, bblaszkow06 commented on test/membrane/core/element_test.exs
> +           } = reply
Maybe you should rather change the asserted result

2021-11-09 09:13 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +      Process.exit(pid, :kill)
I suppose that in such a case one should create a separate, possibly content-aware element and plug it in between. I'd at least wait till we actually need that

2021-11-09 09:15 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +    toilet_size = :atomics.add_get(toilet, 1, buf_size)
Erlang API great as always ;) Not sure what is simpler though - this or having a wrapper (which could be a macro)

2021-11-09 09:16 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +    if toilet_size > 200 do
We're going to replace that with some smart algorithm

2021-11-09 09:17 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +    PadModel.update_data!(state, pad_ref, :demand, &(&1 - buf_size))
I'd optimize the PadModel itself, but in a separate PR

2021-11-09 09:25 UTC, mat-hek commented on lib/membrane/core/element/buffer_controller.ex
> +    Telemetry.report_metric("buffer", 1, inspect(pad_ref))
This wasn't introduced in this PR and I believe should be fixed in a separate PR, as it has to work with the dashboard

2021-11-09 09:29 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +    if toilet = PadModel.get_data!(state, pad_ref, :toilet) do
If it becomes an int it will still be `nil` if turned off. Although not perfect, this is a common way of handling `maybe` in elixir

2021-11-09 13:29 UTC, mat-hek commented on lib/membrane/core/element/state.ex
> +      demand_size: 4000
I believe it ultimately should somehow automatically adapt.

2021-11-09 14:29 UTC, mat-hek commented on lib/membrane/core/element/pad_controller.ex
> +  end
I suppose it could, but not sure how to do it to make it look better...
> it seems like every caller of DemandController.check_auto_demand/2 needs to update demand

That's actually not true :P

> then call check_auto_demand, which also updates demand

It doesn't always do so

> Could the demand logic account for this so the demand size is only updated once?

Given the above facts, it's hard to achieve

> I'm also curious if PadModel.set_data!(state, pad_ref, :demand, demand - buf_size) can be moved into DemandController

That's a good idea, I moved it

2021-11-09 14:34 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> +    |> Enum.all?(& &1.linked?)
Not a fan of this and don't see a reason to optimize here. And if we were to optimize, we should not make it linear at all.

2021-11-09 15:02 UTC, mat-hek commented on lib/membrane/core/element/pad_controller.ex
> +    data = data |> Map.merge(init_pad_mode_data(data, props, other_info, metadata, state))
We'd have to do in multiple clauses...

2021-12-22 18:55 UTC, bblaszkow06 commented on lib/membrane/core/element/demand_handler.ex
> +    )
Maybe get&set? this seems like something that might have impact on performance but most importantly it's shorter and less indented :wink: 
```suggestion
    demand = PadModel.get_data!(state, pad_ref, :demand)
    new_demand = size_fun.(demand)

    if new_demand < 0 do
      raise Membrane.ElementError,
               "Demand altering function requested negative demand on pad #{inspect(pad_ref)} in #{state.module}"
    end

    PadModel.set_data!(state, pad_ref, :demand, new_demand)
```

2021-12-22 18:55 UTC, bblaszkow06 commented on lib/membrane/core/element/demand_handler.ex
> +        {:ok, state}
Maybe this could be handled in a separate function clause sparing the case here? I mean
```elixir
@empty_map_set MapSet.new()
defp handle_delayed_demands(%State{delayed_demands: demands} = state) when demands == @empty_map_set do
  {:ok, state}
end

defp handle_delayed_demands(%State{delayed_demands: delayed_demands} = state) do
  entry = Enum.random(delayed_demands)
  {pad_ref, action} = entry
  # ...

2021-12-22 18:55 UTC, bblaszkow06 commented on lib/membrane/core/element/state.ex
> +      demand_size: 4000
Right now it doesn't so it should be configurable to have a workaround if the value isn't appropriate

2021-12-24 12:16 UTC, andpodob requested changes
High-level comment - this PR is way too big. I followed the auto-demand part of the code and it looks quite good to me apart from @bblaszkow06 comments. The part connected to the atomic toilet is also quite clear, but I can't wrap my head around the linking part - I just can't spot the mechanism you described in the PR description in the code.

2021-12-28 16:02 UTC, mat-hek commented on lib/membrane/pad.ex
> +  @type bin_spec_t :: {name_t(), [common_spec_options_t]}
I think it would be better to manually duplicate some options to reduce magic. I think it's out of scope though.

2021-12-28 16:03 UTC, mat-hek commented on lib/membrane/core/parent/link_endpoint.ex
> +
It provides a default implementation of the access protocol, so this struct can be used in put_in and friends.

2021-12-28 16:03 UTC, mat-hek commented on lib/membrane/core/parent/link.ex
> +  use Bunch.Access
as above

2021-12-28 16:05 UTC, mat-hek commented on lib/membrane/core/element/buffer_controller.ex
> +  defp do_handle_buffer(pad_ref, %{mode: :pull, demand_mode: :auto} = data, buffers, state) do
I'm going to rename this and more functions in element internals to reflect better if they're handling incoming or outgoing data in a separate PR

2021-12-28 16:16 UTC, mat-hek commented on lib/membrane/core/element/buffer_controller.ex
> +    %{direction: :input} = data = PadModel.get_data!(state, pad_ref)
Generally, it shouldn't happen that the buffer is sent to an output pad and it's verified at the sending stage, so such a situation would mean a bug in the core, so I don't think we should have a pretty error for that. However, I'm considering removing that check at all.

2021-12-28 16:17 UTC, mat-hek commented on lib/membrane/core/element/demand_controller.ex
> +    %{direction: :output, mode: :pull} = data
Again, it's a consistency check, like in `handle_buffer`

2021-12-28 16:19 UTC, mat-hek commented on lib/membrane/core/element/demand_controller.ex
> -  defp ignore?(pad_ref, state), do: state.pads.data[pad_ref].mode == :push
From now on, a demand on a push pad shouldn't ever happen

2021-12-28 16:21 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +        {:ok, state}
Dialyzer complains about using empty mapset this way

2021-12-29 11:15 UTC, mat-hek commented on lib/membrane/core/element.ex
> +    {:noreply, state}
The parent sends this message to all children but it's only important for bins. I can change it to be sent to bins only

2021-12-29 11:30 UTC, mat-hek commented on lib/membrane/core/element/demand_controller.ex
> +        if toilet do
When a push output (of A) is connected to an auto-demand input (of B) there must be a toilet in between. Otherwise, A could flood B with data. Indeed, `auto_demands_positive` will return false at some point, so the toilet won't be decreased, while it will be constantly increased in A until it overflows.

2021-12-29 11:36 UTC, bblaszkow06 commented on lib/membrane/core/parent/link_endpoint.ex
> +
That doesn't answer my question :stuck_out_tongue: The problem is it allows to break the struct and bypass both compile-time and run-time checks on keys (example below), so it shouldn't be put everywhere by default but only when it has convincing benefits

```iex
iex(2)> s = %Membrane.ChildEntry{}                          
%Membrane.ChildEntry{
  clock: nil,
  component_type: nil,
  module: nil,
  name: nil,
  options: nil,
  pid: nil,
  playback_synced?: false,
  sync: nil,
  terminating?: false
}
iex(3)> put_in(s, [:zupa], :barszcz)
%{
  __struct__: Membrane.ChildEntry,
  clock: nil,
  component_type: nil,
  module: nil,
  name: nil,
  options: nil,
  pid: nil,
  playback_synced?: false,
  sync: nil,
  terminating?: false,
  zupa: :barszcz
}
```

2021-12-29 11:56 UTC, bblaszkow06 commented on lib/membrane/core/element/buffer_controller.ex
> +    %{direction: :input} = data = PadModel.get_data!(state, pad_ref)
> so I don't think we should have a pretty error for that.

Well, I strongly disagree - 'memento mori`, we're not going to live forever. The team is growing and such error is a clear indication of where to look for an error without checking the code here might be helpful. And remember something might change in future regarding sending checks, i.e. some refactor may introduce a bug that will manifest itself only when someone else makes a mistake in an element or pipeline.
And one more argument - if a bug in core appears in a client application it will be easier to give us feedback on what went wrong.

I think these kinds of checks might be included conditionally like assertions in ErlangVM, i.e. unless building in a debug mode (here - in a 'dev' env) they are purged from the resulting code

2021-12-29 12:20 UTC, bblaszkow06 commented on lib/membrane/core/element/demand_handler.ex
> +        {:ok, state}
OK, then I would split this into 2 functions
```elixir
  @spec handle_delayed_demands(State.t()) :: State.stateful_try_t()
  defp handle_delayed_demands(%State{delayed_demands: delayed_demands} = state) do
    if MapSet.size(delayed_demands) == 0 do
      {:ok, state}
    else
      # Taking random element of `:delayed_demands` is done to keep data flow
      # balanced among pads, i.e. to prevent situation where demands requested by
      # one pad are supplied right away while another one is waiting for buffers
      # potentially for a long time.
      demands_list = Enum.shuffle(delayed_demands)
      do_handle_delayed_demand(demands_list, %State{state | delayed_demands: MapSet.new()})
    end
  end

  defp do_handle_delayed_demands([], state) do
    {:ok, state}
  end

  defp do_handle_delayed_demands([{pad_ref, action} = entry | tail], state) do
    res =
        case action do
          :supply -> do_supply_demand(pad_ref, state)
          :redemand -> handle_redemand(pad_ref, state)
        end

      with {:ok, state} <- res do
        do_handle_delayed_demands(tail, state)
      end
  end
```

2021-12-29 12:55 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +        {:ok, state}
It won't work, as new delayed demands may be added while handling previous ones

2021-12-29 12:58 UTC, bblaszkow06 commented on lib/membrane/core/element/demand_handler.ex
> +        {:ok, state}
Bring back the MapSet.delete then, but the concept stays the same

2021-12-29 13:07 UTC, mat-hek commented on lib/membrane/core/element/buffer_controller.ex
> +    %{direction: :input} = data = PadModel.get_data!(state, pad_ref)
Agreed we could have such assertions, as they would make it clear that something should never happen and if it does then it's a bug in the core itself. Otherwise, a user may have a wrong impression that something is bad with their code (which may be true as well, but such an error may be as helpful as misleading). Moreover, the fact that such checks are de facto redundant makes the code harder to understand, so we should mark that explicitly.

2021-12-29 13:15 UTC, mat-hek commented on lib/membrane/core/parent/link_endpoint.ex
> +
You can do this without the access behaviour anyway `Map.put(s, :zupa, :barszcz)`. I believe that default Access implementation can (or even should) be added whenever a struct is not meant to be opaque, otherwise using it in nested structures is very tough. And tracking whether Access is used anywhere to operate on a struct is pointless imo

2021-12-29 13:25 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +        {:ok, state}
Anyway, I don't see how it would help and especially what's wrong with this code

2021-12-29 13:30 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +        {:ok, state}
BTW fixing that is out of the scope of this PR, as I didn't change this function at all, so -> issue

2021-12-29 13:33 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> +        state
Link requests are sent from a parent to their children and the children send a link response for each link request. When all children respond, then the actual linking happens.

2021-12-29 13:43 UTC, bblaszkow06 commented on lib/membrane/core/parent/link_endpoint.ex
> +
> You can do this without the access behaviour anyway

This was just an example, `Map.` call is a clear indication that you treat something as a map. The main issue is obviously putting inside nested struct

> I believe that default Access implementation can (or even should) be added whenever a struct is not meant to be opaque

I strongly disagree with that. Implementing Access defies the main benefit from using struct - key checks. There is a reason why this isn't done by Elixir by default.
The benefits are present when a struct is part of the nesting chain, not the last link - then you can get_in/put_in/update_in one level up and use the struct as usual. However, it is a bit of a code smell that you operate on a nested structure - sometimes it is possible to decompose the structure earlier and have functions operating only on nested structures without reaching through a deep chain of structs. That should be the preferred way to go.

> And tracking whether Access is used anywhere to operate on a struct is pointless IMO

You shouldn't be tracking that - you should be considering adding `Bunch.Access` only when you find yourself in a situation where you cannot do something without it, not the other way. And since it worked without `use Bunch.Access` before the PR - it means it hasn't been used and I didn't notice usage in this PR

2021-12-29 16:32 UTC, mat-hek commented on lib/membrane/core/parent/link_endpoint.ex
> +
> This was just an example, Map. call is a clear indication that you treat something as a map

And `put_in` is a clear indication that you're using access

> Implementing Access defies the main benefit from using struct - key checks

Actually, there are many other benefits of using structs, like documentation of data types, I'm not really sure which is most important. There are many cases where this validation doesn't work and it's common to use structs these ways as well. It's even explicitly stated in Elixir docs that struct are maps and Map functions can be used on them. Anyway, this claim is not true - it's just the Bunch implementation that delegates to Map and doesn't verify keys: https://github.com/membraneframework/bunch/blob/master/lib/bunch/access.ex#L26 . So it should rather be an issue in Bunch.

> You shouldn't be tracking that - you should be considering adding Bunch.Access only when you find yourself in a situation where you cannot do something without it

So I probably did ;)

> I didn't notice usage in this PR

So you wasted time on tracking that :P Possibly I used that but happened to remove that code so at some point. And maybe someone will do that again at some point. It's not worth checking each time if it's still used or not.

2021-12-29 16:55 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> +    {reply, state}
No, the bin just proxies the `:handle_link` call from its parent to its child and proxies the reply back.

2022-01-06 11:02 UTC, andpodob commented on lib/membrane/testing/pipeline.ex
> +
This doesn't feel right that PR about automatic demands adds functionality to `Testing.Pipeline`, I will need to remember now to remove that when RemoteControlled pipeline is merged ;)

2022-01-06 11:20 UTC, andpodob commented on lib/membrane/parent_spec.ex
> +  on an input that connects to the bin input, they will be overriden if set when linking to the bin in its parent.
```suggestion
  on an input that connects to the bin input, they will be overridden if set when linking to the bin in its parent.
```

2022-01-06 15:16 UTC, andpodob requested changes

2022-01-07 08:40 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +    )
BTW. this function responsibility can be easily moved to the map_reduce that is just below the only call to `resolve_links/2`

2022-01-07 09:34 UTC, andpodob requested changes

2022-01-07 09:34 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +    {:ok, _info} = Message.call(from.pid, :handle_link, [:output, from, to, nil, nil])
Don't you think this should be some other type of message, e.g. `:init_linking`. Then we will get rid of these weird two `nil`'s and maybe it will be possible to simplify the handling of `:handle_link` message (e.g. `Element.PadController` won't need to decide which way to go based on existence `link_metadata`).

2022-01-10 12:45 UTC, andpodob requested changes

2022-01-10 15:13 UTC, andpodob commented on lib/membrane/core/bin/pad_controller.ex
> +  defp handle_pad_added(ref, state) do
I observed that usually when a function does something for some conditions and is a NOP for others (in this case if the `availability` is not `:dynamic`) it is prefixed with a `maybe_`
```suggestion
  defp maybe_handle_pad_added(ref, state) do
```

2022-01-12 11:35 UTC, andpodob requested changes

2022-01-18 12:30 UTC, mat-hek commented on lib/membrane/testing/pipeline.ex
> +
I just needed that ¯\_(ツ)_/¯ though I suppose that RemoteControlled pipeline will be merged first :P

2022-01-18 12:34 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +        {to_respond_from, state} =
Yes, we expect one response from both sides of the link, unless they are bin pads. Do you have an idea for better naming? :P

2022-01-18 14:51 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +      do_proceed_spec_linking(spec_ref, %{spec_data | status: :linked}, state)
We'd have to do that twice - for pipeline and bin separately.

2022-01-18 14:52 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +    {:ok, _info} = Message.call(from.pid, :handle_link, [:output, from, to, nil, nil])
Good idea, will change

2022-01-19 13:37 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +    {:ok, _info} = Message.call(from.pid, :handle_link, [:output, from, to, nil, nil])
It turned out that leaving handle_link is more convenient, but I added a clear indication where the call originates

2022-01-19 18:02 UTC, bblaszkow06 requested changes

2022-01-20 12:36 UTC, mat-hek commented on lib/membrane/buffer/metric.ex
> +  @callback buffer_size_approximation() :: pos_integer
This is actually meant to be the approximation of the size of a buffer. In other words, an approximation of what the `buffers_size` callback will return for an average buffer.

2022-01-20 12:41 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> +      end)
Hmm, the original way seems more readable to me... @andpodob wdyt?

2022-01-20 12:44 UTC, mat-hek commented on lib/membrane/core/element/toilet.ex
> +  end
> Time to grow up 😛

:'(

2022-01-20 16:20 UTC, mat-hek commented on lib/membrane/core/element/pad_controller.ex
> +        nil
I'd rather for omitting that too, but I suppose it may be confusing for some people

2022-01-20 16:27 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +    end
> I would differentiate status atoms from pad type and name 

done

2022-01-21 17:01 UTC, bblaszkow06 requested changes

2022-01-21 17:01 UTC, bblaszkow06 commented on lib/membrane/parent_spec.ex
> +    and `t:Membrane.Pad.demand_mode_t/0` for more info.
The docs miss the explanation of what those values do

2022-01-24 12:39 UTC, bblaszkow06 requested changes

2022-01-24 12:39 UTC, bblaszkow06 commented on lib/membrane/parent_spec.ex
> +    Used only for pads working in pull mode with manual demands. See `t:Membrane.Pad.mode_t/0`
This still doesn't explain everything and only remembering the old `preffered_size` I could get it. I'd modify the docs and change the name of the option:
```suggestion
  - `initial_demand` - The initial demand sent to the linked output pad. It is used to fill the queue of the input pad.
    That allows for fulfilling the demands of the element by taking data from the queue while the actual sending of demands is done asynchronously, smoothing the processing.
    Used only for pads working in pull mode with manual demands. See `t:Membrane.Pad.mode_t/0`
```

Ideas for alternative names:
* `warm_up_demand`
* `starting_demand`

This may however affect the way `min_demand_factor` is defined, I'm not sure if if makes sense to define the `min_demand` as function of this demand and calculated using a factor

2022-01-24 13:25 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +    Used only for pads working in pull mode with manual demands. See `t:Membrane.Pad.mode_t/0`
`initial demand` seems like it was only sent initially and didn't matter afterwards. I refactored the description but left `demand_excess`

2022-01-24 14:25 UTC, bblaszkow06 approved these changes

2022-01-24 15:40 UTC, andpodob approved these changes
LGTM! 🎉

2022-01-24 15:41 UTC, merged