add crash group docs
membraneframework/membrane_core pull request #315
Opened 2021-06-24 16:20 UTC by andpodob

Added documentation for Crash Groups.

2021-06-25 11:15 UTC, mat-hek requested changes
There are some uncathegorized modules in docs, can you assign them also?

![image](https://user-images.githubusercontent.com/16493463/123416358-bdcc9e80-d5b6-11eb-9242-9cde85e53eb8.png)

2021-06-25 11:15 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +  # Crash Groups
`#` shouldn't be used in docs, start with `##`. Generate the docs and check if they look good

2021-06-25 11:15 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +    {:endpoint_bin, endpoint_id} => %EndpointBin{
endpoint bin may be a bit confusing, use `some_element` or so

2021-06-25 11:15 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +  doesn't influence value of `:trap_exit` flag.
I wouldn't mention that, especially since we're going to change that

2021-06-25 11:15 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +  `:temporary` which means that membrane will not make any attempts to restart crashed child.
I'd move that before the example

2021-06-25 11:15 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +  In above snippet we create a new children - EndpointBin and we add it to crash group with id `endpoint_id`. When EndpointBin crashes the whole pipeline will still be alive.
use a tool like grammarly to check the spelling for you

```suggestion
  In the above snippet, we create new children - EndpointBin and we add it to the crash group with id `endpoint_id`. When EndpointBin crashes, the rest of the pipeline will still be alive.
```

2021-06-25 11:15 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +  At this moment Crash Groups are only useful for elements with dynamic pads.
mention that they're currently not supported within bins

2021-06-25 11:16 UTC, andpodob commented on lib/membrane/parent_spec.ex
> +  doesn't influence value of `:trap_exit` flag.
are we?

2021-06-25 11:17 UTC, andpodob commented on lib/membrane/parent_spec.ex
> +  doesn't influence value of `:trap_exit` flag.
aren't we going to add dummy ancestor and stay with monitors?

2021-06-25 12:24 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +  doesn't influence value of `:trap_exit` flag.
IIRC the 'dummy ancestor' was to use links and trap exits

2021-07-29 09:59 UTC, mat-hek approved these changes

2021-07-29 10:00 UTC, merged