Added init/termiante telemetry events
membraneframework/membrane_core pull request #317
Opened 2021-07-12 06:56 UTC by Qizot

2021-07-16 11:11 UTC, mat-hek requested changes

2021-07-16 11:11 UTC, mat-hek commented on lib/membrane/telemetry.ex
> +  def bin_terminate_event_name(), do: [:membrane, :_terminate, :terminate]
```suggestion
  def bin_terminate_event_name(), do: [:membrane, :bin, :terminate]
```

2021-07-16 11:11 UTC, mat-hek commented on lib/membrane/telemetry.ex
> +  def element_terminate_event_name(), do: [:membrane, :element, :terminate]
do we have to have all these functions? IMHO it's enough that these names are documented

2021-07-19 06:09 UTC, Qizot commented on lib/membrane/component_path.ex
> +
I can see that it has been closed and not merged.  I can apply that change here.

2021-07-19 06:10 UTC, Qizot commented on lib/membrane/telemetry.ex
> +  def element_terminate_event_name(), do: [:membrane, :element, :terminate]
Sure ;)

2021-07-19 06:29 UTC, Qizot commented on lib/membrane/component_path.ex
> +
Nevermind, I see that the `System.pid()` gets added in timescale reporter.

2021-07-19 09:22 UTC, mat-hek requested changes

2021-07-19 09:22 UTC, mat-hek commented on lib/membrane/core/element.ex
> +    )
This should rather happen each time handle_info is called. I'd convert existing clauses to `do_handle_info` not to repeat that every clause

2021-07-19 13:37 UTC, Qizot commented on lib/membrane/core/element.ex
> +    )
I don't think that adding another function call for reporting the `queue_len` is worth it.

2021-07-19 14:49 UTC, mat-hek commented on lib/membrane/core/element.ex
> +    )
if you add `@compile :inline` to `do_handle_info` there will be no difference

2021-07-21 08:14 UTC, Qizot commented on lib/membrane/core/element.ex
> +    )
Ok, makes sense as the compile inline will work just like pattern matching on functions but it will internally create a `case` so we will end up with the same amount of pattern matching without any additional overhead.

2021-07-21 10:51 UTC, mat-hek commented
Can we also somehow solve the problem of bitrate and buffers at sinks? That metrics won't be reported for them or for any element that only receives data. Maybe we'd have `incoming_bitrate`, `outgoing_bitrate`, `incoming_buffers` and `outgoing_buffers`?

2021-07-21 13:37 UTC, Qizot commented
> Can we also somehow solve the problem of bitrate and buffers at sinks? That metrics won't be reported for them or for any element that only receives data. Maybe we'd have `incoming_bitrate`, `outgoing_bitrate`, `incoming_buffers` and `outgoing_buffers`?

We can either:
-  perform the measuring bitrate and number of buffers when buffers arrive on input pads. We will support a more vast range of elements (including elements that just consume data and does not produce, sinks, ect.) but again we will lose information about sources producing such buffers (from what I researched there is no an easy way to measure those 2 metrics for sources without duplicating the information for other types of elements)
- measure metrics for sinks in buffer controlelrs as I did and ignore the elements that does not produce data (I think that those elements should be sinks in the end)

2021-09-20 11:39 UTC, mat-hek requested changes

2021-09-24 09:03 UTC, Qizot commented on lib/membrane/core/telemetry.ex
> +  @compile {:inline, report_metric: 3}
Changed to macros :)

2021-09-24 09:08 UTC, mat-hek requested changes

2021-09-24 09:08 UTC, mat-hek commented on lib/membrane/core/telemetry.ex
> +  def get_public_pad_name(pad) do
This should be private. Generate the docs and check if nothing's missing

2021-09-24 09:35 UTC, Qizot commented on lib/membrane/core/telemetry.ex
> +  def get_public_pad_name(pad) do
The problem is that the macros can't access that when it is private.

2021-09-24 09:44 UTC, mat-hek approved these changes

2021-09-24 11:48 UTC, mat-hek approved these changes

2021-09-24 11:48 UTC, merged