Allow to specify node when spawning bin or element.
membraneframework/membrane_core pull request #319
Opened 2021-09-06 12:25 UTC by ostinelli

Adds the ability to distribute elements across a cluster. It will use node in `%ParentSpec{}` in `ChildLifeController`.

2021-09-06 14:06 UTC, Qizot requested changes

2021-09-06 14:06 UTC, Qizot commented on lib/membrane/core/element.ex
> +      if node == nil do
same case as above with `Membrane.Core.Bin`

2021-09-06 14:06 UTC, Qizot commented on lib/membrane/core/bin.ex
> +      if node == nil do
EDIT: I know that `nil` is also an atom and the question is if we want to treat `nil` and `node()` (current node) the same way.

2021-09-06 14:06 UTC, Qizot commented on lib/membrane/core/bin.ex
> +    do: start(node(), options, process_options)
I guess that it should be a `nil` to avoid spawning it via rpc call?

2021-09-06 16:59 UTC, ostinelli commented on lib/membrane/core/bin.ex
> +      if node == nil do
> Can it ever be `nil`? If so then the function spec should account for that or we should probably raise.

It can be `nil` because `ChildLifeController` calls `StartupHandler.start_children/5` with the `node` parameter coming from the optional `node` element in `%ParentSpec{}` from [here](https://github.com/geometerio/membrane_core/commit/3741c61ff8ef15e527eed1646a47e479b0e17551#diff-9fc8a1f82166b1f51259297d76ef5b53ffce74fc633eb00060190baf97edd403R41).

> I think we should also check if the node equals current node and start it without the `rpc` as you do in `nil` case.

I conformed to Erlang's `rpc` module that doesn't do this check, but I'm totally fine in adding this.

2021-09-06 17:00 UTC, ostinelli commented on lib/membrane/core/bin.ex
> +    do: start(node(), options, process_options)
I'm adding the suggested check so this can stay as is.

2021-09-07 08:50 UTC, Qizot approved these changes

2021-09-07 10:09 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +          node: node()
```suggestion
          clock_provider: Child.name_t(),
          node: node() | nil
```

2021-09-07 10:27 UTC, ostinelli commented on lib/membrane/parent_spec.ex
> +          node: node()
Indeed! Thanks for catching it.

2021-09-07 10:59 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +          node: node()
Actually clock_provider can be `nil` either, maybe let's fix them both ;)

2021-09-15 14:51 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +          node: node()
@ostinelli bump ;)

2021-09-15 15:14 UTC, ostinelli commented on lib/membrane/parent_spec.ex
> +          node: node()
I wasn't aware you were waiting for me! Will update asap.

2021-09-16 09:42 UTC, mat-hek approved these changes

2021-09-16 09:43 UTC, mat-hek commented
@sax @ostinelli can you please rebase?

2021-09-16 10:14 UTC, ostinelli commented
> @sax @ostinelli can you please rebase?

Do you mean squash the commits?

2021-09-16 10:30 UTC, mat-hek commented
@ostinelli I mean update to the membrane master, which changed since the PR was created. I don't expect any conflicts, but I cannot rebase since it's geometer's repo and I don't have rights

![image](https://user-images.githubusercontent.com/16493463/133596606-6b4992f0-ef41-4789-b2ca-d2c4e2e43efe.png)

2021-09-17 08:27 UTC, mat-hek approved these changes

2021-09-17 08:27 UTC, merged