Add ability to remove links from ParentSpec
membraneframework/membrane_core pull request #329
Opened 2021-10-03 15:40 UTC by sax

Everything about this change set is up for debate. It's the beginning of a proof of concept, and seems to work in the context of `membrane_rtc_engine` to unlink a `tee` from an `endpoint`, except for the fact that in my code the tee can not then be re-linked to that same endpoint.

```
"Pad {Membrane.Pad, :input, \"cde48b33-6269-4dd3-87aa-7e00729b89e2:00b2256c-69fe-48a9-aec7-f29f80c35e88 \"} has already been linked"
```

This happens because the pad is still present in `Membrane.Core.Bin.State` for `Membrane.WebRTC.EndpointBin`. I might be missing some cleanup in `membrane_core`, or it might be that I'm not correctly unlinking the endpoint bin in `membrane_webrtc_plugin` when the pad goes away.

2021-10-08 21:39 UTC, sax commented
After diving a little deeper, I *think* my issues with re-linking existing children are not with the new code, but with pad state that is not cleaned on parents for pads removed from children. I think this is an existing issue in membrane core, but one that didn't cause problems before—generally this would only happen when children were removed, so a new child would generate a new pad reference that wouldn't conflict with the state retained on a pipeline or bin.

I'm checking this using the `membrane_rtc_engine`, but having one endpoint running, then joining and leaving many times in another browser window. When I inspect the state of the first bin in `:observer`, I see that it has a huge list of input pads for the historical other endpoints.

2021-10-12 19:01 UTC, sax commented
I think this catches the last bit of state in bins when links are removed—at least the state that has been causing me problems.

2021-11-02 15:34 UTC, mat-hek requested changes

2021-11-02 15:34 UTC, mat-hek commented on lib/membrane/core/child/pad_controller.ex
> +              """
Can it happen that the pad is not present?

2021-11-02 20:23 UTC, sax commented on lib/membrane/core/child/pad_controller.ex
> +              """
I think I was running into issues when trying to unlink bin inputs, before we split `handle_unlink` into separate function heads for Bins and Elements. I added this to show a more understandable error, rather than blowing up on `PadModel.get_data!/3`.

With the other changes, this can go away... though I think I'll collapse it into a single `get_data!` call.

2021-11-02 20:48 UTC, sax commented
Looks like it's failing based on not updating the changelog. I'm not sure if I should add a new section to the changelog, though... Seems like adding a section for `0.9.0` vs a different version would be a choice you would make rather than me.

2021-11-03 07:12 UTC, mat-hek commented
@sax eh, we introduced that changelog recently and it seems to cause problems... If you need it soon, we can release in 0.8, otherwise I'd go for in 0.9, where auto demands should land

2021-11-04 14:56 UTC, mat-hek commented
@sax apart from the changelog, please refresh my review request whenever it's ready ;)

2021-11-04 15:06 UTC, sax commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +          """)
I switched this to the raise as you suggested.

2021-12-07 20:30 UTC, sax commented on test/membrane/integration/link_removal_test.exs
> +  describe "removing links" do
I ran into a small issue with the fact that `:handle_unlink` was being used not only for the `:remove_link` action, but for removing links during the handling of crash groups. I just worked around it by sending a different message between processes... it calls down to the same function in the end, so I don't think it's too terrible.

It was more difficult to write the test than to write the code, so hopefully this solution is acceptable.

2021-12-07 20:32 UTC, sax commented
@mat-hek I think this last commit may resolve your last suggestion, unless I missed something in the comments above. Please take another look when you have a chance!

2022-05-18 14:01 UTC, closed without merging