Reduce garbage, reductions when pulling buffers
membraneframework/membrane_core pull request #338
Opened 2021-10-15 23:04 UTC by sax

My measurements are imprecise, but with a video room of 4 participants I think I'm seeing 25-100% CPU reduction with these changes. This should reduce the number of reductions, as well as some garbage generation.

2021-11-25 15:27 UTC, mat-hek requested changes

2021-11-25 15:27 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +  def get_data!(state, pad_ref, keys) do
why?

2021-11-25 15:27 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +        |> Bunch.Access.put_in(data_keys(pad_ref, keys), value)
```suggestion
        put_in(data_keys(pad_ref, keys), value)
```
Bunch.Access seems not to help there and it's an additional function call

2021-11-25 15:27 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +  defp data_keys(pad_ref, keys)
```suggestion
  @compile {:inline, data_keys: 2}
  defp data_keys(pad_ref, keys)
```

2021-11-25 15:27 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +  @spec constraints_met?(Pad.Data.t(), [
invalid spec

2021-11-25 15:36 UTC, mat-hek requested changes

2021-11-25 15:36 UTC, mat-hek commented on lib/membrane/core/callback_handler.ex
> +  defp exec_callback(
We should consider making it a macro

2021-11-25 15:36 UTC, mat-hek commented on lib/membrane/core/callback_handler.ex
> +  defp parse_callback_result({:error, reason}, module, cb, %{state: false}) do
Here we rely on the handler params, while in `exec_callback` we check whether the callback is handle_init

2021-12-07 21:48 UTC, sax commented on lib/membrane/core/child/pad_model.ex
> +  def get_data!(state, pad_ref, keys) do
When I ran eprof on a video call for 10 seconds, I noticed that functions wrapping and unwrapping lists were among the most called functions. I realized that this default was only added so that it could be thrown away, and that fixing the callers to call the right function removes not only the need for wrapping/unwrapping, but also the need for this default.

2021-12-07 22:13 UTC, sax commented on lib/membrane/core/child/pad_model.ex
> +    |> Map.get(pad_ref)
The simple fix (just pushed) uses `Map.fetch/2` to remove one of the accesses in this function. The idea of replacing this with macros is interesting, but I don't think I can wrap my head around the implementation at the moment.

I was also thinking that moving pad data into ETS could be a solution that make access and updates cheaper. I think it would be good to measure that before committing to it, though.

2021-12-07 23:52 UTC, sax commented on lib/membrane/core/callback_handler.ex
> +  defp parse_callback_result({:error, reason}, module, cb, %{state: false}) do
Yeah, I wasn't sure about this. The main reason I added this was because the callers who care about it seem to all put `%{state: false}` into `exec_and_handle_callback/5` when they care about it. I see now that only happens for `:handle_init`, so...

I see what you're saying. I'll push a commit in a sec that catches `:handle_init` directly. This removes the need for `%{state: false}` everywhere.

2021-12-07 23:58 UTC, sax commented
@mat-hek I *think* these changes cover all your suggestions. Please take another look when you get a chance.

I have not had a chance to look at rebasing master, so this might need some updating related to what you've been working on.

2021-12-08 00:12 UTC, sax commented
Actually, since I realized it makes more sense to squash commit this all back onto master when ready, I just updated this branch with a merge commit.

2021-12-08 11:44 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +  def get_data!(state, pad_ref, keys) do
Oh I haven't noticed you added get_data!/2

2021-12-08 12:58 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +        state |> Bunch.Access.get_and_update_in(data_keys(pad_ref, keys), f)
Let's remove `Bunch.Access` from wherever possible

2021-12-08 12:59 UTC, mat-hek commented
Looks great! I'd believe removing `Bunch.Access` calls should be fairly simple and save us some overhead

2021-12-09 00:51 UTC, sax commented
This last commit removes the explicit calls to `Bunch.Access`, though it still depends on `use Bunch.Access` being added to the structs. My guess is that this isn't going to help too much, since the compiler might be smart enough to compile out the intermediary calls. It doesn't hurt though.

It seems like removing `Bunch.Access` itself will be a bigger refactor, and since we'll be modifying nested structs/maps, might not give us too much of a gain until operations can be batched. 

Could that be a done as a separate issue? I was thinking that moving these to different data structures might be more beneficial. I know that records were not a huge improvement (and I don't see a great alternative in erlang), but maybe flattening out the data and using ETS could improve update times with acceptable impact to reads. Alternatively, a small C-based mutable data structure using a NIF could speed things up? Anyways, both of those seem larger than this pull request.

2021-12-09 10:22 UTC, mat-hek commented
@sax I meant just to remove the `Bunch.Access.*_in` calls, just like you did ;) this will save some overhead, as it will remove the intermediary call before `Kernel.*_in`. Not using elixir's Access is a bigger refactor indeed. We did some research and it seems like using elixir's pattern matching and map put `%{map | key: value}` syntax performs great while providing immutability, so the plan is to create some macros generating that. Of course, that's beyond this PR

2021-12-09 10:45 UTC, mat-hek submitted a review, later dismissed

2021-12-09 17:17 UTC, sax commented
Yay!

2021-12-10 14:16 UTC, mat-hek commented
If you could just rebase to master, we updated credo there so the checks should start passing

2021-12-13 04:36 UTC, sax commented
Since I started doing merges, I decided to continue with another. Hopefully this can be squashed without too much trouble.

2021-12-14 15:53 UTC, mat-hek approved these changes

2021-12-14 15:53 UTC, merged

2021-12-14 17:29 UTC, sax commented
Thank you!