Multiple elements in one process (#293)
membraneframework/membrane_core pull request #355
Opened 2021-11-19 11:52 UTC by bblaszkow06

Closes #293

2022-05-16 11:40 UTC, mat-hek requested changes

2022-05-16 11:40 UTC, mat-hek commented on test/membrane/filter_aggregator_test.exs
> +defmodule Membrane.FilterAggregatorTest do
I'd add some integration test

2022-05-16 11:40 UTC, mat-hek commented on lib/membrane/filter_aggregator/context.ex
> +  @spec before_incoming_action(t(), action :: any()) :: t()
use proper type for action

2022-05-16 11:40 UTC, mat-hek commented on lib/membrane/filter_aggregator.ex
> +  An element allowing to aggregate many filters within one Elixir process.
I'd mention it's still experimental

2022-05-16 11:52 UTC, bblaszkow06 commented on lib/membrane/element/base.ex
> +  @callback __struct__(kv :: [atom | {atom, any()}]) :: struct()
[You already have done that](https://github.com/membraneframework/membrane_core/blame/75d4a6b5c859458101c28113e9cf3a0e5c7c058b/lib/membrane/element/base.ex#L81) so this is consistent.
If auto-generated callbacks were to be removed, it would affect the whole module and it's outside the scope of this PR

2022-05-16 15:34 UTC, bblaszkow06 commented on lib/membrane/filter_aggregator.ex
> +  defp perform_action({:buffer, {:output, []}}, _module, _context, state) do
It doesn't seem possible without a major refactor - the checks there are based on the invoked callback, so I'd also do this separately.

2022-05-16 15:37 UTC, bblaszkow06 commented on lib/membrane/filter_aggregator/context.ex
> +defmodule Membrane.FilterAggregator.Context do
Why would you like to do this? It's just a part of FilterAggregator extracted to a separate module and I would keep it as-is, i.e. as `Membrane.FilterAggregator`'s helper module

2022-05-18 09:42 UTC, bblaszkow06 commented on lib/membrane/filter_aggregator.ex
> +            _error -> result
This is actually an invalid name for the unused variable as it can be `{:ok, actions}` but I think I should add the raise anyway

2022-05-23 11:44 UTC, bblaszkow06 commented on lib/membrane/filter_aggregator.ex
> +  defp perform_action({:buffer, {:output, []}}, _module, _context, state) do
#429

2022-05-30 07:34 UTC, mat-hek approved these changes

2022-05-30 07:37 UTC, mat-hek commented on lib/membrane/filter_aggregator.ex
> +            raise "#{inspect(module)} is not an element!"
Let's raise something more like https://github.com/membraneframework/membrane_core/blob/master/lib/membrane/core/parent/child_entry_parser.ex#L53

2022-05-30 11:43 UTC, bblaszkow06 commented on lib/membrane/filter_aggregator.ex
> +            raise "#{inspect(module)} is not an element!"
Do you mean the message, exception type or both?
I've started to write it as a `ParentError` but I realized it might not be the best idea to treat `FilterAggregator` as a parent in that scenario. I've used `ArgumentError` instead as it's passed via options and raise happens on `handle_init`. Any thoughts on that?

2022-05-30 11:51 UTC, mat-hek approved these changes

2022-05-30 11:52 UTC, merged