Fix failing tests.
membraneframework/membrane_core pull request #357
Opened 2021-11-26 15:39 UTC by marcinwasowicz

Fixes tests failing due to changes introduced in original branch.

2021-11-29 10:18 UTC, FelonEkonom commented on test/support/bin/test_bins.ex
> +          %Membrane.Testing.Notification{payload: _payload} = notification,
What is the reason of pattern matching, if struct ` %Membrane.Testing.Notification{}` contains field `payload`, if it is enforced key?

2021-11-29 10:26 UTC, FelonEkonom commented on test/support/bin/test_bins.ex
> +
If stopping forwarding notifications in Bins causes fail of some tests, that are not explicitly related to forwarding notifications, I would rather consider the correctness of these tests or maybe unobvious and undesirable behaviors of Bins caused by this change, then just override the changed callback in implementation used in tests

2021-12-02 12:28 UTC, andpodob requested changes

2021-12-02 12:28 UTC, andpodob commented on test/support/bin/test_bins.ex
> +    end
As we discussed on today's check-in, let's make `test_bin` to forward all notifications.

2021-12-02 12:28 UTC, andpodob commented on test/support/bin/test_bins.ex
> +
Same here.

2021-12-06 13:11 UTC, merged