Remote controlled pipeline
membraneframework/membrane_core pull request #366
Opened 2021-12-22 15:51 UTC by andpodob

2021-12-28 12:02 UTC, mat-hek requested changes

2021-12-28 12:02 UTC, mat-hek commented on lib/membrane/remote_controlled/pipeline.ex
> +  @type event_t ::
it's a bit ambiguous with the `Membrane.Event`, maybe just `message_t` ?

2021-12-28 13:21 UTC, andpodob commented on lib/membrane/remote_controlled/pipeline.ex
> +
I wanted this line to be right before the returned value :P

2022-03-23 09:18 UTC, mat-hek requested changes

2022-03-23 09:18 UTC, mat-hek commented on lib/membrane/remote_controlled/message.ex
> +  defstruct @enforce_keys
I think it would be better to have a more flat structure and place the `from` field in each type of message instead of wrapping them with this struct. It doesn't matter that much when using our wrappers, but would be quite cumbersome when doing `receive` manually

2022-03-23 09:18 UTC, mat-hek commented on lib/membrane/remote_controlled/pipeline.ex
> +  for that message.
```suggestion
  It is required to firstly use `subscribe/2` to subscribe to a given message before awaiting
  for that message.
```

2022-03-23 09:18 UTC, mat-hek commented on lib/membrane/remote_controlled/pipeline.ex
> +  controlled by a controlling process. The controlling process can request the execution of arbitrary
The first sentence till two break lines serves as a short description in the modules list in docs
```suggestion
  A basic `Membrane.Pipeline` implementation that can be controlled by a controlling process.

  The controlling process can request the execution of arbitrary
```

2022-03-23 09:18 UTC, mat-hek commented on lib/membrane/remote_controlled/pipeline.ex
> +  receives notification from one of its children.
this seems not quite up to date

2022-03-23 09:18 UTC, mat-hek commented on lib/membrane/remote_controlled/pipeline.ex
> +  logic in the `Membrane.Pipeline` callbacks implementation. An example of usage could be running a
I'd describe that in more detail, mentioning that you have to subscribe for a message to receive it. I'd also include an example (maybe a doctest?)

2022-03-23 09:18 UTC, mat-hek commented on lib/membrane/remote_controlled/pipeline.ex
> +  def await_start_of_stream(pipeline, element, pad) do
```suggestion
  def await_start_of_stream(pipeline, element, pad \\ Macro.var(:_, __MODULE__)) do
```

Wouldn't something like this cover the above case as well?

2022-03-24 09:36 UTC, varsill commented on lib/membrane/remote_controlled/message.ex
> +            | Membrane.RemoteControlled.Message.Terminated.t()
done

2022-03-24 10:39 UTC, varsill commented on lib/membrane/remote_controlled/message.ex
> +  defstruct @enforce_keys
indeed, done

2022-03-24 10:41 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +  for that message.
done

2022-03-24 11:15 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +  for that message.
done

2022-03-24 11:16 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +  receives notification from one of its children.
in fact it is :D 
done

2022-03-24 11:16 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +  def await_start_of_stream(pipeline, element, pad) do
So finally I have decided to stick to this implementation

2022-03-24 11:27 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +  logic in the `Membrane.Pipeline` callbacks implementation. An example of usage could be running a
done

2022-03-24 11:29 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +  controlled by a controlling process. The controlling process can request the execution of arbitrary
done

2022-03-24 15:02 UTC, mat-hek requested changes

2022-03-25 07:45 UTC, varsill commented on lib/membrane/remote_controlled/message.ex
> -  @type t :: %__MODULE__{
Hmm is the type really useful? We do not have the Message.__struct__ anymore.
How about listing all possible submodules in the `@moduledoc`?

2022-03-25 07:48 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +        {:subscription, fn x -> match?(unquote(subscription_pattern), x) end}
done

2022-03-25 07:49 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +  * `Membrane.RemoteControlled.Message.Terminated.t()` sent when the pipeline is terminated.
done

2022-03-28 06:38 UTC, varsill commented on lib/membrane/remote_controlled/message.ex
> -  @type t :: %__MODULE__{
ok, I got it. I was supposing that one would simply write this type as `PlaybackState.t() | StartOfStream.t() ...` but indeed, why not to do it for themselves :D 
done

2022-03-28 08:54 UTC, mat-hek approved these changes

2022-03-28 08:54 UTC, mat-hek commented on lib/membrane/remote_controlled/message.ex
> +  @type message_t ::
```suggestion
  @type t ::
```

2022-03-30 08:32 UTC, mat-hek submitted a review, later dismissed

2022-03-30 12:11 UTC, mat-hek requested changes

2022-03-30 12:11 UTC, mat-hek commented on lib/membrane/remote_controlled/pipeline.ex
> +    ```Elixir
AFAIK this is not needed, as elixir is the default language in hexdocs

2022-03-31 07:24 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +    ```Elixir
done

2022-03-31 11:54 UTC, mat-hek approved these changes

2022-04-04 11:08 UTC, merged