add try-catch to the Message.call/5 implementation
membraneframework/membrane_core pull request #385
Opened 2022-02-01 16:26 UTC by andpodob

This PR refactors `Message.call` to return an error instead of exiting when the receiver process is not alive.

2022-02-02 11:06 UTC, mat-hek requested changes

2022-02-02 11:06 UTC, mat-hek commented on lib/membrane/core/message.ex
> +      GenServer.call(pid, message(type: type, args: args, opts: opts), timeout)
```suggestion
      result = GenServer.call(pid, message(type: type, args: args, opts: opts), timeout)
      {:ok, result}
```

And we should handle that properly wherever it's used. We could possibly keep the old version of `call` named `call!` too.

2022-02-02 12:36 UTC, andpodob commented on lib/membrane/core/message.ex
> +      GenServer.call(pid, message(type: type, args: args, opts: opts), timeout)
Currently call is not wrapping the result in the tuple `{:ok, result}`. Why do you want to change that? Also as we noticed during the last discussion on that, we are using `Message.call` only in 4 places in the whole codebase, I don't see a clear benefit of using `call!` over matching against the expected result. 
This code would end up very weird with this wrapping approach:
https://github.com/membraneframework/membrane_core/blob/master/lib/membrane/core/parent/child_life_controller/link_handler.ex#L270
The only place that requires an additional handling is here:
https://github.com/membraneframework/membrane_core/blob/master/lib/membrane/core/bin/pad_controller.ex#L180

2022-02-03 13:31 UTC, mat-hek commented on lib/membrane/core/message.ex
>    @spec call(GenServer.server(), type_t, args_t, opts_t, timeout()) :: term()
I'd list the error explicitly in the return type

2022-02-04 10:20 UTC, mat-hek approved these changes

2022-02-04 10:21 UTC, merged