Reliable unlinking/case 1
membraneframework/membrane_core pull request #396
Opened 2022-02-15 12:11 UTC by andpodob

This PR:
* adds pad_info to `%Endpoint` structure
* adds handling the case when one of the sides of the link is not alive and the other side wants to connect via static pad
* adds the test of handling that case

2022-02-15 15:12 UTC, mat-hek requested changes

2022-02-15 15:12 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +        {{:error, {:call_failure, _reason}}, :static, _to_availability} ->
Shouldn't we kill `to.pid` when `to_availability` is `:static`?

2022-02-16 10:04 UTC, mat-hek requested changes

2022-02-16 10:04 UTC, mat-hek commented on test/membrane/integration/linking_test.exs
> +        link(:source) |> to(:sink)
a test when the source has a dynamic output would be useful

2022-02-16 16:11 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +        {{:error, {:call_failure, _reason}}, :static, _to_availability} ->
You're right.

2022-02-16 16:11 UTC, andpodob commented on lib/membrane/core/element/pad_controller.ex
> +        {{:error, {:neighbor_not_alive, reason}}, state}
Done.

2022-02-17 17:46 UTC, mat-hek requested changes

2022-02-18 09:58 UTC, andpodob commented on test/membrane/integration/linking_test.exs
> +  defmodule DynamicSource do
To make it really generic I would add a logic that sends all buffers passed through the option `output` to all connected pads. Now let's say you connect two Testing.Sinks, it is unpredictable which buffers will end up in which Testing.Sink, so it effectively makes it impossible to use `assert_sink_buffer`.

2022-02-18 12:53 UTC, andpodob commented on test/membrane/integration/linking_test.exs
> +  defmodule DynamicSource do
done.

2022-02-18 12:54 UTC, andpodob commented on test/membrane/integration/linking_test.exs
> +    end
done.

2022-02-18 12:55 UTC, andpodob commented on test/membrane/integration/linking_test.exs
> +        {{:ok, [end_of_stream: :output]}, state}
done.

2022-02-18 12:55 UTC, andpodob commented on lib/membrane/core/element/pad_controller.ex
> +    with :ok <- Membrane.Core.Child.PadModel.assert_instance(state, pad_ref),
done.

2022-02-18 15:26 UTC, mat-hek submitted a review, later dismissed

2022-02-21 09:59 UTC, mat-hek approved these changes

2022-02-21 11:06 UTC, merged