Reliable unlinking/case 3
membraneframework/membrane_core pull request #400
Opened 2022-02-25 15:58 UTC by andpodob

2022-03-11 13:07 UTC, mat-hek requested changes

2022-03-11 13:07 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +        end
Some other specs may not be linked yet. Maybe we could just check if there are any pending specs?

2022-03-11 13:40 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +        end
Added check to verify if the `pending_specs` map is empty.

2022-03-11 16:00 UTC, mat-hek requested changes

2022-03-11 16:00 UTC, mat-hek commented on lib/membrane/core/playback_handler.ex
> +      end
It's quite an ifology here, can't we refactor it somehow? `cond` perhaps?

2022-03-16 10:22 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +      state = put_in(state, [:pending_specs], Map.delete(state.pending_specs, spec_ref))
Done.

2022-03-16 10:29 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +      state
Done.

2022-03-16 14:19 UTC, mat-hek approved these changes

2022-03-16 14:19 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +          )
```suggestion
      if state.delayed_playback_change != nil do
        {:ok, state} = LifecycleController.change_playback_state(
          state.delayed_playback_change,
          %{state | delayed_playback_change: nil}
        )
```

2022-03-17 09:41 UTC, andpodob commented on lib/membrane/core/parent/child_life_controller/link_handler.ex
> +          )
Done.

2022-03-17 10:53 UTC, mat-hek approved these changes

2022-03-17 11:08 UTC, merged