Remote controlled pipeline improved
membraneframework/membrane_core pull request #401
Opened 2022-02-28 13:12 UTC by varsill

Solves the problems with warnings and illegible pattern syntax in the await macros.
Provides three alternative syntaxes for the patterns. 
Defines the message structure.
Problem with  :terminating message not being delivered is a result of handle_stopped_to_terminating/2 callback not being called, probably due to this implementation: https://github.com/membraneframework/membrane_core/blob/f7ff09f929d26c455cc2b3d117c8ddf428f162d3/lib/membrane/core/playback_handler.ex#L82

As I can see, there are no tests for the handle_stopped_to_terminating/2 callback, and its invocation in the PlaybackHandler has been removed ~2 years ago, in https://github.com/membraneframework/membrane_core/commit/5867a6ef22ce67703a9443dbe1f85aff98ad8741

2022-03-08 14:09 UTC, andpodob requested changes
Apart from what we discussed and a few comments it LGTM.

2022-03-09 09:10 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +  Awaits for the first `Membrane.RemoteControlled.Message()` wrapping the `Membrane.RemoteControlled.Message.PlaybackState()` message with the given `state`,
done

2022-03-09 09:13 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +          body: %Membrane.RemoteControlled.Message.unquote(message_type){
done

2022-03-09 09:59 UTC, varsill commented on lib/membrane/remote_controlled/pipeline.ex
> +  for that message.
done

2022-03-17 10:48 UTC, andpodob approved these changes
LGTM!

2022-03-18 08:02 UTC, merged