Raise exception when caps are not send before the first buffer
membraneframework/membrane_core pull request #404
Opened 2022-03-08 10:19 UTC by varsill

Add ActionError exception raising when the `:buffer` action is made on pad, which does not have caps set. Add unit test and integration test checking that functionality. Change the existing tests in a`ction_handler_test.exs` and `auto_demands_test.exs` so that they are now working with pads that have the caps set before sending the first buffer.
closes #341

2022-03-16 14:08 UTC, mat-hek requested changes

2022-03-16 14:08 UTC, mat-hek commented on lib/membrane/core/element/action_handler.ex
> +      if state.pads.data[pad_ref].caps == nil do
- this can be an additional clause in the `withl` above
- you can use the `pad_data` variable

2022-03-16 14:08 UTC, mat-hek commented on lib/membrane/exceptions.ex
> +    "Caps were not sent on this pad before the first buffer was"
```suggestion
    "Tried to send a buffer, while caps have not been sent on this pad"
```

2022-03-16 14:08 UTC, mat-hek commented on test/membrane/core/element/action_handler_test.exs
> +      state = state |> set_playback_state(:prepared) |> PadModel.set_data!(:output, :caps, :any)
```suggestion
      state = state |> set_playback_state(:prepared) |> PadModel.set_data!(:output, :caps, :some_caps)
```

2022-03-17 08:42 UTC, varsill commented on lib/membrane/exceptions.ex
> +    "Caps were not sent on this pad before the first buffer was"
done

2022-03-17 08:45 UTC, varsill commented on test/membrane/core/element/action_handler_test.exs
> +      state = state |> set_playback_state(:prepared) |> PadModel.set_data!(:output, :caps, :any)
I have found that in this test file there is `@mock_caps` defined and I have used it there.

2022-03-17 08:45 UTC, varsill commented on test/membrane/core/element/action_handler_test.exs
> +      state = state |> set_playback_state(:prepared) |> PadModel.set_data!(:output, :caps, :any)
done

2022-03-17 09:41 UTC, varsill commented on lib/membrane/core/element/action_handler.ex
> +      if state.pads.data[pad_ref].caps == nil do
done

2022-03-21 09:40 UTC, mat-hek approved these changes

2022-03-24 10:33 UTC, merged