Add playback actions
membraneframework/membrane_core pull request #411
Opened 2022-03-22 12:47 UTC by varsill

Adds {:playback, :playing|:prepared|:stopped} actions which can be returned by the pipeline.
Depricates Membrane.Pipeline.{prepare, play, stop} functions and these functions defined by default in modules, which `use Membrane.Pipeline`
closes #337

2022-03-22 13:48 UTC, varsill commented
EXPLANATION: 
I have decided to choose a "soft" manner of deprecation. Membrane.Pipeline.{play, prepare, stop} functions are still available, however, using them in code leads to a `@deprecated` warning being printed.

I have needed to change the `Membrane.Pipeline.__before_compile__` (invoked during the `use Membrane.Pipeline`) implementation so that the `play/1, stop/1, prepare/1` methods are no longer delegated to the `Membrane.Pipeline` default implementations. It was necessary since `Membrane.Pipeline.{play, stop, prepare}` are now `@deprecated` and we do not want a warning while defining a custom pipeline module with `use Membrane.Pipeline`. However, changing `defdelegate` to a function definition led to a [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) increase of the `__before_compile__` function. `mix credo` complains about this and I couldn't find any way to decrease that complexity, so I have just turned off the `mix credo` for the line defining `__before_compile`.

2022-03-23 09:46 UTC, mat-hek requested changes

2022-03-23 09:46 UTC, mat-hek commented on lib/membrane/core/pipeline/action_handler.ex
> +    Membrane.Core.PlaybackHandler.request_playback_state_change(self(), playback_state)
This unnecessarily introduces sending a message, better call `LifecycleController.handle_playback_state`. Also check if there's a good error when passing an invalid state

2022-03-23 09:46 UTC, mat-hek commented on lib/membrane/pipeline.ex
>        unless Enum.any?(1..2, &Module.defines?(__MODULE__, {:stop_and_terminate, &1})) do
I'd rename this to `terminate`

2022-03-23 09:46 UTC, mat-hek commented on test/membrane/element_test.exs
> +      Testing.Pipeline.execute_actions(pipeline, playback: :playing)
I'd make all these pipelines return `playback: :playing` in `init` instead

2022-03-25 08:30 UTC, varsill commented on lib/membrane/core/pipeline/action_handler.ex
> +    Membrane.Core.PlaybackHandler.request_playback_state_change(self(), playback_state)
hmm didn't you mean `LifecycleController. change_playback_state/2`? As far as I see, `LifecycleController. change_playback_state/2` calls `PlaybackHandler.change_playback_state/3`, which finally calls `LifecycleController.handle_playback_state/3` - but wraps some logic concerning updating `state.playback`, etc.

2022-03-25 08:40 UTC, varsill commented on lib/membrane/core/pipeline/action_handler.ex
> +    Membrane.Core.PlaybackHandler.request_playback_state_change(self(), playback_state)
Is this the desired error message? :P 
<img width="794" alt="image" src="https://user-images.githubusercontent.com/10851084/160085429-5ad15b34-efb9-4265-96f4-399f1ba5f33c.png">

2022-03-25 08:58 UTC, varsill commented on lib/membrane/pipeline.ex
>        unless Enum.any?(1..2, &Module.defines?(__MODULE__, {:stop_and_terminate, &1})) do
good idea, done

2022-03-25 09:04 UTC, varsill commented on lib/membrane/pipeline.ex
>        unless Enum.any?(1..2, &Module.defines?(__MODULE__, {:stop_and_terminate, &1})) do
I have also changed `Membrane.Core.Bin.stop_and_terminate` into `Membrane.Core.Bin.terminate`

2022-03-25 11:53 UTC, varsill commented on test/membrane/element_test.exs
> +      Testing.Pipeline.execute_actions(pipeline, playback: :playing)
done

2022-03-31 11:53 UTC, mat-hek commented on lib/membrane/core/pipeline/action_handler.ex
> +    Membrane.Core.PlaybackHandler.request_playback_state_change(self(), playback_state)
> hmm didn't you mean LifecycleController. change_playback_state/2

yes, sorry

2022-04-05 17:02 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +    do_terminate(pipeline, opts)
couldn't we just call `terminate` here?

2022-04-06 06:42 UTC, varsill commented on lib/membrane/pipeline.ex
> +    do_terminate(pipeline, opts)
well, sure we could :D Done

2022-04-06 07:41 UTC, mat-hek approved these changes

2022-04-07 07:56 UTC, merged