Refine testing pipeline
membraneframework/membrane_core pull request #414
Opened 2022-04-05 07:32 UTC by varsill

2022-04-05 16:58 UTC, mat-hek requested changes

2022-04-05 16:58 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +  def populate_links(children) when length(children) < 2 do
```suggestion
  def populate_links([]) do
```

2022-04-05 16:58 UTC, mat-hek commented on lib/membrane/parent_spec.ex
> +  end
- I guess this should create the children as well, now it ignores the values
- `populate_links` isn't quite meaningful, maybe something like `link_linear`?

2022-04-05 16:58 UTC, mat-hek commented on lib/membrane/testing/pipeline.ex
> +    end
Actually, we could just have the `module` key that would be either `:default` or a custom module, and it could default to `:default`. WDYT?

2022-04-05 16:58 UTC, mat-hek commented on lib/membrane/testing/pipeline.ex
> +  @type default_pipeline_keywords_list_t :: [
```suggestion
  @type default_pipeline_keyword_list_t :: [
```

It's keyword list, not keywords list ;)

2022-04-06 06:49 UTC, varsill commented on lib/membrane/testing/pipeline.ex
> +  @type default_pipeline_keywords_list_t :: [
indeed, done

2022-04-06 08:33 UTC, varsill commented on lib/membrane/testing/pipeline.ex
> +    end
I am up to it

2022-04-06 08:36 UTC, varsill commented on lib/membrane/testing/pipeline.ex
> +    end
done

2022-04-07 07:52 UTC, varsill commented on lib/membrane/parent_spec.ex
> +  def populate_links(children) when length(children) < 2 do
done

2022-04-11 15:47 UTC, mat-hek approved these changes

2022-04-15 11:30 UTC, merged