Error cleanup
membraneframework/membrane_core pull request #418
Opened 2022-04-13 13:36 UTC by mat-hek

This PR changes the approach to handling fatal errors - instead of being passed up the call stack and raised in a single place, they're raised ASAP. Most element and child code is refactored, parent code will be adjusted in a separate PR.

2022-04-13 15:46 UTC, bblaszkow06 commented on lib/membrane/core/child/pad_model.ex
> +      end
I think case would be more idiomatic here (make sure to format this suggestion):
```suggestion
      case data do
        unquote(pattern) ->
          :ok
        _ ->
          raise Membrane.PadError, """
          Assertion on data of the pad #{inspect(pad_ref)} failed, pattern: #{unquote(Macro.to_string(pattern))}
          Pad data: #{inspect(data, pretty: true)}
          """
      end
```

2022-04-13 15:57 UTC, bblaszkow06 commented on lib/membrane/core/child/pad_model.ex
> +      |> wrap_with_reraise(pad_ref, state)
Continuation marker for me :wink:

2022-04-14 08:22 UTC, mat-hek commented on lib/membrane/core/bin/action_handler.ex
> +    with {:ok, state} <- do_handle_action(action, callback, params, state) do
Agreed, but I decided to move bin and pipeline refactor to another PR to merge this one faster and avoid conflicts

2022-04-14 08:24 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +            Bunch.Type.stateful_t(:ok | unknown_pad_error_t, Child.state_t())
This is the part that we're going to remove when switching to elixir 1.14, so I only removed the alias

2022-04-14 17:05 UTC, bblaszkow06 requested changes

2022-04-20 09:33 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +          end
If we checked for a pad before executing `code`, that error wouldn't happen and we'd raise `UnknownPadError`. So this code gives the same effect

2022-04-20 09:51 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +        match: _data -> {:error, :no_match}
In that case, we'd return no_match if get_data happened to return a different error/value. That would be very misleading.

2022-04-20 09:52 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +    @type unknown_pad_error_t :: {:error, :unknown_pad}
I define it only for the legacy part that's using it. It's not used anywhere else

2022-04-20 09:55 UTC, mat-hek commented on lib/membrane/core/element/action_handler.ex
> +  def handle_action({action, _}, :handle_init, _params, _state)
We have, but it's wider than that and includes renaming more functions so that it's easy to distinguish the ones that handle incoming data from those handling actions and outgoing data

2022-04-20 09:57 UTC, mat-hek commented on lib/membrane/core/element/pad_controller.ex
>        state = PadModel.delete_data!(state, pad_ref)
I'm not convinced, we usually accept the state as the last argument.

2022-04-20 09:59 UTC, mat-hek commented on lib/membrane/core/timer_controller.ex
> +    with true <- Map.has_key?(state.synchronization.timers, timer_id),
we have the same check a couple of lines further, I think it's more readable to do it the same way

2022-04-20 10:45 UTC, mat-hek commented on lib/membrane/core/element/action_handler.ex
> +         when caps != nil <- pad_data do
That way seems slower:
```elixir
range = 1..10_000

map = %{x: 0, y: 0, z: 0, a: 1, b: 2}

cases = %{
  multi: fn ->
    Enum.map_reduce(range, map, fn _i, acc ->
      case acc do
        %{x: 1} -> raise "x"
        %{y: 2} -> raise "y"
        %{z: 3} -> raise "z"
        %{a: a, b: b} -> {{a, b}, acc}
      end
    end)
  end,
  single: fn ->
    Enum.map_reduce(range, map, fn _i, acc ->
      with %{x: 0, y: 0, z: 0, a: a, b: b} <- acc do
        {{a, b}, acc}
      else
        %{x: 1} -> raise "x"
        %{y: 2} -> raise "y"
        %{z: 3} -> raise "z"
      end
    end)
  end
}

Benchee.run(cases)
```
```
Operating System: macOS
CPU Information: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
Number of Available Cores: 8
Available memory: 16 GB
Elixir 1.13.3
Erlang 24.3

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 5 s
memory time: 0 ns
reduction time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 14 s

Benchmarking multi ...
Benchmarking single ...

Name             ips        average  deviation         median         99th %
single        1.14 K        0.88 ms    ±21.52%        0.86 ms        1.35 ms
multi         0.89 K        1.12 ms    ±24.02%        1.05 ms        1.65 ms

Comparison:
single        1.14 K
multi         0.89 K - 1.28x slower +0.25 ms
```

Plus the current way better separates the happy path from error handling IMO

2022-04-20 11:01 UTC, mat-hek commented on lib/membrane/core/element/action_handler.ex
> +        raise ElementError, "Tried to request a demand on output pad #{inspect(pad_ref)}"
1. I decided to leave action errors for invalid (unknown) actions, actions returned from invalid callbacks and in a wrong playback state. Validation of these is the entire responsibility that I'd like ActionHandler to eventually have. The pad-related stuff involves, apart from directions, demand modes, presence of eos and other specific stuff that is not ActionHandler-level generic IMO.
2. Will do
3. I think it's overkill for errors that happen twice

2022-04-20 15:15 UTC, bblaszkow06 commented on lib/membrane/core/child/pad_model.ex
> +        match: _data -> {:error, :no_match}
The type spec on `get_data` guarantees it won't return any other error - it's not up to the code other than unit tests to ensure that. I won't insist on changing that, but it still seems like a too defensive approach.

2022-04-20 16:28 UTC, bblaszkow06 commented on lib/membrane/core/timer_controller.ex
> +    with true <- Map.has_key?(state.synchronization.timers, timer_id),
This argument isn't compelling to me as both checks use the same code, but test for a bit different scenarios. Reading that was even more puzzling as my first thought was that it was a mistake. For me, it hinders readability by adding another branch to the function clause (I think that's an increase of the cyclomatic complexity of that clause)

On top of that, if you believe checking key existence in different ways is not readable enough, I'd suggest defining a (private) guard `timer_present?` it will do more for readability than putting it twice in one function.

2022-04-20 16:37 UTC, bblaszkow06 commented on lib/membrane/exceptions.ex
> +    other possible circumstances.\
This error message is quite vague. I believe we should explicitly specify what's wrong with the action, but the absolute minimum for me is to separate the unknown action from an action disallowed in the circumstances

2022-04-21 10:10 UTC, bblaszkow06 commented on lib/membrane/exceptions.ex
> +    other possible circumstances.\
One more idea - you may link to the proper docs e.g. `Membrane.Element.Action` for elements

2022-04-21 10:12 UTC, mat-hek commented on lib/membrane/core/element/pad_controller.ex
>        state = PadModel.delete_data!(state, pad_ref)
> All these functions are basically state transformations

Almost all functions in the core are state transformations, but I don't think it's the most intuitive way of looking at them. In `PadModel` it's somehow justified because it's a model, so changing data is the whole point there. To me, chaining things in a pipeline is good when there is an obvious subject that is passed through the pipeline, while other arguments are just a context. The state doesn't seem to be an obvious subject here.

2022-04-21 10:17 UTC, mat-hek commented on lib/membrane/core/child/pad_model.ex
> +        match: _data -> {:error, :no_match}
If you don't insist, I'll leave `withl`. Apart from verifying returned values, it's more explicit, readable and future-proof IMO.

2022-04-21 13:16 UTC, mat-hek commented on lib/membrane/core/element/pad_controller.ex
>        state = PadModel.delete_data!(state, pad_ref)
Anyway, `generate_eos_if_needed` and `remove_pad_associations` are public and changing only them would make the API terribly inconsistent, while fixing that is out of scope of this PR.

2022-04-22 14:16 UTC, mat-hek commented on lib/membrane/core/element/action_handler.ex
> +    state
I'll change that when refactoring playback states

2022-04-25 12:23 UTC, bblaszkow06 commented on lib/membrane/core/element/action_handler.ex
> +         when caps != 0 <- pad_data do
https://user-images.githubusercontent.com/2119556/165088188-8e4c4d5a-fa90-4394-bac7-8049f1f1b742.mp4

2022-04-25 12:40 UTC, bblaszkow06 commented on lib/membrane/core/element/action_handler.ex
> +        raise InvalidPadDirectionError, what: "end of stream", direction: :input, pad: pad_ref
1. This has a bit of Java smell :stuck_out_tongue: I think `PadDirectionError` would be enough.
2. The key `:what` is kind of `meh`. I'd name it `action`

2022-04-25 12:40 UTC, bblaszkow06 commented on lib/membrane/exceptions.ex
> +      message: "Tried to send #{opts.what} via #{opts.direction} pad #{inspect(opts.pad)}"
One thing is missing here - what is wrong with that send. I know it's included in the exception name, but I'd still include that in the message as well

```suggestion
      message: "Sending #{opts.what} via pad #{inspect(opts.pad)} with #{opts.direction} direction is not allowed"
```

2022-05-05 13:22 UTC, bblaszkow06 submitted a review, later dismissed

2022-05-10 08:40 UTC, varsill approved these changes

2022-05-12 15:33 UTC, bblaszkow06 approved these changes

2022-05-13 09:02 UTC, merged