Parent error cleanup
membraneframework/membrane_core pull request #426
Opened 2022-05-04 11:53 UTC by mat-hek

2022-05-09 14:44 UTC, bblaszkow06 requested changes

2022-05-09 14:44 UTC, bblaszkow06 commented on lib/membrane/core/parent/child_life_controller/startup_handler.ex
> +        Map.put(children, child.name, child)
This gets rid of checks for the existence of the pad inside children. (It was at line 12 in child_model) Was that intended?

2022-05-09 14:44 UTC, bblaszkow06 commented on lib/membrane/core/parent/children_model.ex
> +      _children -> raise ParentError, "Unknown child #{inspect(child)}"
I wonder if this message will be clear enough for the user to figure out what's wrong. Can you think of example where this might appear and how the stacktrace will look? Plus, WDYT about adding the list of children that are there?

```suggestion
      _children -> raise ParentError, "Unknown child #{inspect(child)}. Current children: #{inspect(Map.keys(children))}"
```

2022-05-09 14:44 UTC, bblaszkow06 commented on lib/membrane/core/parent/children_model.ex
> +          _children -> raise ParentError, "Unknown child #{inspect(name)}"
Like above. Maybe `UnknownChildError` for deduplication?

2022-05-09 14:44 UTC, bblaszkow06 commented on lib/membrane/core/pipeline.ex
> +  alias Membrane.Core.Parent.{ChildLifeController, LifecycleController}
Lexicographically, `Parent` < `Timer`. Do we have some guidelines regarding alias sorting?

2022-05-09 14:53 UTC, mat-hek commented on lib/membrane/core/pipeline.ex
> +  alias Membrane.Core.Parent.{ChildLifeController, LifecycleController}
they should be lexicographically sorted, but there's nothing enforcing that ¯\_(ツ)_/¯

2022-05-09 14:59 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/startup_handler.ex
> +        Map.put(children, child.name, child)
There was a check for duplicate children, but we already do that at line 37 in the child life controller

2022-05-09 14:59 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/startup_handler.ex
> +        Map.put(children, child.name, child)
https://github.com/membraneframework/membrane_core/pull/426/files/a7cd2d7e29aaa3a427966d801a03d10849615f5f#diff-9fc8a1f82166b1f51259297d76ef5b53ffce74fc633eb00060190baf97edd403R37

2022-05-11 08:44 UTC, varsill commented on lib/membrane/core/parent/message_dispatcher.ex
> -  @moduledoc false
I am asking out of my curiosity, as I cannot find a reason for that action on my own - what was the purpose of removing Parent.MessageDispatcher, when we are duplicating the code for handling messages in pipeline and bin right now? Because, I believe, there was some reason :D

2022-05-11 08:44 UTC, varsill commented on lib/membrane/core/pipeline/action_handler.ex
> +    :ok = Parent.ChildLifeController.handle_forward(Bunch.listify(children_messages), state)
`Enum.each`, which is the last and the only thing called in `ChildLifeController.handle_forward`, always returns `:ok`, so there is probably no point in matching it with `:ok` on the left side.

2022-05-12 13:59 UTC, merged