Bump Ratio to 3.0
membraneframework/membrane_core pull request #438
Opened 2022-07-12 09:16 UTC by varsill

This PR updates the Ratio dependency do 3.0 and updates the code accordingly to the changes in API. This PR should be merged once we decide to update Ratio dependency in all the plugins in organization.

2022-11-15 12:33 UTC, varsill commented
Closing since Ratio 4.0 has been released ;)

2022-11-24 09:01 UTC, varsill commented
Reopening since Ratio v4.0.0 is only a release candidate ;)

2022-11-24 11:08 UTC, mat-hek requested changes

2022-11-24 11:08 UTC, mat-hek commented on lib/membrane/clock.ex
> +    if Ratio.lt?(till_next, 0) do
why do we overload operators if we don't use them?

2022-11-24 11:08 UTC, mat-hek commented on lib/membrane/clock.ex
> +    ratio = Ratio.div(Ratio.new(clock_time), Ratio.new(state.time_provider.() - state.init_time))
as above

2022-11-24 15:09 UTC, varsill commented on lib/membrane/clock.ex
> +    if Ratio.lt?(till_next, 0) do
Well, we are using them - the overloaded operators are not only comparison operators, but also arithmetic operators

2022-11-25 17:13 UTC, mat-hek commented on lib/membrane/clock.ex
> -
I'd leave this type

```suggestion
  @typedoc """
  Ratio of the Clock time to the reference time.
  """
  @type ratio_t :: Ratio.t()
```

2022-11-25 17:13 UTC, mat-hek commented on lib/membrane/clock.ex
> +    ratio = Ratio.new(clock_time, state.time_provider.() - state.init_time)
`div` is less confusing in this case IMO

```suggestion
    ratio = Ratio.div(clock_time, state.time_provider.() - state.init_time)
```

2022-11-25 17:13 UTC, mat-hek commented on lib/membrane/core/timer.ex
> +    use Numbers, overload_operators: true
let's be consistent and not use that

2022-11-25 17:13 UTC, mat-hek commented on lib/membrane/time.ex
> +      use Numbers, overload_operators: true
as above

2022-11-29 07:54 UTC, varsill commented on lib/membrane/clock.ex
> -
done

2022-11-29 07:55 UTC, varsill commented on lib/membrane/clock.ex
> +    ratio = Ratio.new(clock_time, state.time_provider.() - state.init_time)
done

2022-11-29 08:32 UTC, varsill commented on lib/membrane/time.ex
> +      use Numbers, overload_operators: true
done here and also in clock_test.exs

2022-11-30 12:51 UTC, mat-hek approved these changes

2022-12-01 10:58 UTC, merged