Distrubuted toilet
membraneframework/membrane_core pull request #440
Opened 2022-07-14 11:54 UTC by varsill

Description of the problem: https://membraneframework.atlassian.net/browse/MC-57
This PR adds Membrane.Core.Element.Toilet.Atomic - an abstraction put above the implementation of atomic counter. It also adds AtomicProcess as one of it's implementation.

2022-07-22 10:49 UTC, mat-hek commented on lib/membrane/core/element/toilet.ex
> +          {:ok, pid} = GenServer.start(Membrane.Core.Element.Toilet.DistributedCounter.Worker, [])
```suggestion
          {:ok, pid} = GenServer.start(Worker, [])
```

2022-07-22 10:49 UTC, mat-hek commented on test/membrane/core/toilet_test.exs
> +defmodule Membrane.Core.ToiletTest do
```suggestion
defmodule Membrane.Core.Element.ToiletTest do
```

2022-07-22 12:04 UTC, varsill commented on lib/membrane/core/element/toilet.ex
> +          {:ok, pid} = GenServer.start(Membrane.Core.Element.Toilet.DistributedCounter.Worker, [])
done

2022-07-22 12:05 UTC, varsill commented on test/membrane/core/toilet_test.exs
> +defmodule Membrane.Core.ToiletTest do
done and the file has been moved to the appropriate directory

2022-07-25 12:30 UTC, mat-hek requested changes

2022-07-25 14:14 UTC, varsill commented on lib/membrane/core/element/demand_handler.ex
>          )
Sure, it's just a leftover of the previous implementation.
done

2022-07-26 08:01 UTC, mat-hek approved these changes

2022-07-26 09:17 UTC, varsill commented on lib/membrane/core/playback_handler.ex
> +        other_error
i have reverted them

2022-07-26 09:22 UTC, merged