Add Membrane.Time.to_timebase/2 function
membraneframework/membrane_core pull request #441
Opened 2022-07-21 07:32 UTC by varsill

2022-07-22 10:56 UTC, mat-hek requested changes

2022-07-22 10:56 UTC, mat-hek commented on lib/membrane/time.ex
> +  def to_timebase(timestamp, timebase) do
```suggestion
  @spec round_to_timebase(t, t | Ratio.t()) :: integer
  def round_to_timebase(timestamp, timebase) do
```

2022-07-22 10:56 UTC, mat-hek commented on lib/membrane/time.ex
> +  Returns timestamp in timebase units. Rounded to the nearest integer.
an example would be useful

2022-07-25 10:54 UTC, varsill commented on lib/membrane/time.ex
> +  def to_timebase(timestamp, timebase) do
done

2022-07-26 07:56 UTC, varsill commented on lib/membrane/time.ex
> +  Returns timestamp in timebase units. Rounded to the nearest integer.
done

2022-07-26 07:57 UTC, mat-hek approved these changes

2022-07-26 07:57 UTC, mat-hek commented on lib/membrane/time.ex
> +      300
you can make this a doctest

2022-07-26 09:24 UTC, merged