Playback wip
membraneframework/membrane_core pull request #447
Opened 2022-09-06 15:43 UTC by mat-hek

2022-09-08 14:36 UTC, bblaszkow06 requested changes

2022-09-08 14:36 UTC, bblaszkow06 commented on lib/membrane/core/parent/child_life_controller/startup_utils.ex
> +    end
OK finally found the place where this is defined. IMHO instead of lambda I'd pass the module and args

2022-09-08 14:36 UTC, bblaszkow06 commented on lib/membrane/utility_supervisor.ex
> +  is needed, a dedicated supervisor should be spawned under this supervisor.
I guess an example here wouldn't hurt

2022-09-08 14:36 UTC, bblaszkow06 commented on lib/membrane/resource_guard.ex
> +  and provides it via callback context.
Example?

2022-09-08 14:36 UTC, bblaszkow06 commented on lib/membrane/resource_guard.ex
> +  functions can be registered with the same name.
```suggestion
  Registers a resource cleanup function in the resource guard.

  Registered functions are called in the order reverse to the registration order.
  A return value of a registered function is ignored. If a `name` is passed,
  the function can be cleaned up manually with `cleanup_resource/2`. Many
  functions can be registered with the same name.
```

2022-09-08 14:36 UTC, bblaszkow06 commented on lib/membrane/resource_guard.ex
> +  and provides it via callback context.
```suggestion
  Utility for handling resources that must be cleaned up after use.

  This utility uses a separate process that allows registering functions
  that are called when the owner process (passed to `start_link/1`) dies for
  any reason. Each Membrane component spawns its resource guard on startup
  and provides it via callback context.
```

2022-09-08 14:49 UTC, mat-hek commented on lib/membrane/resource_guard.ex
> +  def handle_info(Message.new(:cleanup_resource, name), state) do
Using bare processes has some problems - for example, they cannot be introspected with the observer. We don't use casts anywhere across the core. I don't see any benefit in using them, but if we choose to do so, we should be consistent.

2022-09-12 13:39 UTC, varsill commented on lib/membrane/core/children_supervisor.ex
> +    end
[Not that important] `Process.link/1` returns true - just for the purpose of consistency the last match could be `_error -> true`. Btw. - are we anyhow informing about the error in `start_utility`? (Or perhaps there is just no reason to do so?)

2022-09-12 13:39 UTC, varsill commented on lib/membrane/pipeline.ex
> +      Membrane.Core.Pipeline.Supervisor.go_brrr(
Are we sticking to `go_brrr`? :D

2022-09-12 13:39 UTC, varsill commented on lib/membrane/utility_supervisor.ex
> +defmodule Membrane.UtilitySupervisor do
I don't think we have a test for utility supervisor

2022-09-29 12:41 UTC, mat-hek commented on lib/membrane/core/children_supervisor.ex
> +    end
I think `true` would look weird here. Not sure what you mean by informing about the error, but the result is returned  in the next line, no matter if error or not

2022-09-29 12:42 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +      Membrane.Core.Pipeline.Supervisor.go_brrr(
Why not? :P

2022-09-30 10:22 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/startup_utils.ex
> +    end
done

2022-09-30 13:35 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +      Membrane.Core.Pipeline.Supervisor.go_brrr(
done

2022-09-30 13:35 UTC, mat-hek commented on lib/membrane/resource_guard.ex
> +  and provides it via callback context.
done

2022-10-03 10:25 UTC, bblaszkow06 requested changes

2022-10-03 10:25 UTC, bblaszkow06 commented on lib/membrane/resource_guard.ex
> +      {:EXIT, ^task, reason} -> reason
You forgot about the timeout.

2022-10-03 11:36 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +      Membrane.Core.Pipeline.Supervisor.go_brrr(
![image](https://user-images.githubusercontent.com/16493463/193567720-04cfdc24-fe6a-44d9-bac1-e111dcb4353e.png)

2022-10-03 11:45 UTC, mat-hek commented on lib/membrane/core/observability.ex
> +        }
I think it's overkill

2022-10-03 11:58 UTC, mat-hek commented on lib/membrane/resource_guard.ex
> +      {:EXIT, ^task, reason} -> reason
done

2022-10-03 12:40 UTC, bblaszkow06 requested changes

2022-10-03 12:40 UTC, bblaszkow06 commented on lib/membrane/resource_guard.ex
> +        Process.exit(task, :kill)
This will put another `:EXIT` signal in your mailbox (i.e. `{:EXIT, task_pid, :killed}`). I'm not sure if that's not going a bit into the implementation details of `Task`s but you can unlink the task process before killing like `Task.ignore` does (https://github.com/elixir-lang/elixir/blob/c5151e6890b5ac8df13276459696f0f47a8e634b/lib/elixir/lib/task.ex#L850)

2022-10-03 15:41 UTC, varsill approved these changes

2022-10-03 16:05 UTC, bblaszkow06 approved these changes

2022-10-10 12:47 UTC, merged