Add list of available callbacks in each component
membraneframework/membrane_core pull request #449
Opened 2022-09-23 10:55 UTC by varsill

2022-09-28 12:22 UTC, mat-hek requested changes

2022-09-28 12:22 UTC, mat-hek commented on lib/membrane/docs_helper.ex
> +               :ok
This seems weird, are you sure it's correct? Maybe it's possible to remove `when` when present and try parsing again with the same code

2022-09-28 12:22 UTC, mat-hek commented on lib/membrane/docs_helper.ex
> +  defp generate_docstring_with_list_of_callbacks(module, modules_list, starting_with) do
grouping callback by behaviours and explaining why we include them would be great

2022-09-29 08:18 UTC, varsill commented on lib/membrane/bin.ex
> +  Membrane.DocsHelper.add_callbacks_list_to_moduledoc(__MODULE__, [], "handle_")
done

2022-09-29 08:23 UTC, varsill commented on lib/membrane/docs_helper.ex
> +defmodule Membrane.DocsHelper do
indeed, done

2022-09-29 08:24 UTC, varsill commented on lib/membrane/docs_helper.ex
> +               :ok
well, it works fine, but I will implement your suggestion

2022-09-29 09:25 UTC, varsill commented on lib/membrane/docs_helper.ex
> +               :ok
done

2022-09-29 10:20 UTC, mat-hek requested changes

2022-09-29 10:20 UTC, mat-hek commented on lib/membrane/core/docs_helper.ex
> +    {name, if(is_nil(array), do: 0, else: length(array))}
```suggestion
  defp parse_callback_ast({:"::", _line1, [{name, _line2, args} | _rest]}) do
    {name, if(is_nil(args), do: 0, else: length(args))}
```

2022-09-29 10:20 UTC, mat-hek commented on lib/membrane/core/docs_helper.ex
> +  @moduledoc """
```suggestion
  @moduledoc false
```

2022-09-29 10:20 UTC, mat-hek commented on lib/membrane/core/docs_helper.ex
> +        The callbacks available in `#{module}` behaviour:
```suggestion
        Below there is a list of all the callbacks available in a module, that implements `#{inspect(module)}` behaviour.
        We have put it for your convenience, as some of these callbacks are not directly defined in that module and
        their specification is available in different modules.

        The callbacks available in `#{inspect(module)}` behaviour:
```

2022-09-29 11:40 UTC, varsill commented on lib/membrane/docs_helper.ex
> +  defp generate_docstring_with_list_of_callbacks(module, modules_list, starting_with) do
done

2022-09-30 06:54 UTC, varsill commented on lib/membrane/core/docs_helper.ex
> +        The callbacks available in `#{module}` behaviour:
done

2022-09-30 08:29 UTC, mat-hek requested changes
+ grouping by behaviour seems still missing

2022-09-30 14:22 UTC, varsill commented on lib/membrane/core/docs_helper.ex
> +        The callbacks available in `#{module}` behaviour:
ups, I have forgotten about checking if that changes is applicable in other places :D 
done

2022-10-03 12:08 UTC, mat-hek requested changes

2022-10-03 12:08 UTC, mat-hek commented on lib/membrane/bin.ex
> +  DocsHelper.add_callbacks_list_to_moduledoc(__MODULE__)
```suggestion
```

2022-10-03 12:19 UTC, mat-hek requested changes

2022-10-03 12:19 UTC, mat-hek commented on lib/membrane/core/docs_helper.ex
> +    Enum.map(module.behaviour_info(:callbacks), &{&1, module})
```suggestion
    module.behaviour_info(:callbacks) |> Enum.sort() |> Enum.map(&{&1, module})
```

2022-10-03 12:20 UTC, mat-hek requested changes

2022-10-03 12:20 UTC, mat-hek commented on lib/membrane/core/docs_helper.ex
> +  defp generate_docstring_with_list_of_callbacks(list_of_callbacks) do
the module could be passed to this function instead of being put in a tuple with each callback's name

2022-10-03 12:49 UTC, varsill commented on lib/membrane/bin.ex
> +  DocsHelper.add_callbacks_list_to_moduledoc(__MODULE__)
done

2022-10-03 12:49 UTC, varsill commented on lib/membrane/pipeline.ex
> +  DocsHelper.add_callbacks_list_to_moduledoc(__MODULE__)
done

2022-10-03 13:03 UTC, varsill commented on lib/membrane/core/docs_helper.ex
> +  defp generate_docstring_with_list_of_callbacks(list_of_callbacks) do
done

2022-10-03 13:06 UTC, varsill commented on lib/membrane/core/docs_helper.ex
> +    Enum.map(module.behaviour_info(:callbacks), &{&1, module})
done

2022-10-05 10:12 UTC, mat-hek approved these changes

2022-10-05 10:14 UTC, merged