Playback termination
membraneframework/membrane_core pull request #451
Opened 2022-09-30 14:42 UTC by mat-hek

2022-10-06 10:49 UTC, bblaszkow06 requested changes

2022-10-06 10:49 UTC, bblaszkow06 commented on lib/membrane/bin.ex
> +  Callback invoked when bin is removed by its parent.
I'm not 100% sure, but I'd say:
```suggestion
  A callback invoked when the bin is being removed by its parent.
```

2022-10-06 10:49 UTC, bblaszkow06 commented on lib/membrane/bin/action.ex
> +    by parent, i.e. after `c:Membrane.Bin.handle_terminate_request/2` is called
Suggestion by courtesy of Grammarly:
```suggestion
  - use `:normal` for graceful termination. Allowed only when the parent already requested termination,
    i.e. after `c:Membrane.Bin.handle_terminate_request/2` is called
```

2022-10-06 10:49 UTC, bblaszkow06 commented on lib/membrane/core/bin.ex
> +  def terminate(_reason, _state) do
Do we need that callback now? That telemetry event seems useless now assuming some other form or reporting termination of a component is in place

2022-10-06 10:49 UTC, bblaszkow06 commented on lib/membrane/core/element.ex
> +  def terminate(_reason, _state) do
Like above - seems unneeded.

2022-10-06 10:49 UTC, bblaszkow06 commented on lib/membrane/core/parent/lifecycle_controller.ex
> +          %Core.Bin.State{} -> Core.Bin.Zombie
I don't think I saw any docs on what these Zombies are. They should be in the codebase somewhere, not sure where to not repeat them though.

2022-10-06 10:49 UTC, bblaszkow06 commented on lib/membrane/core/pipeline.ex
> +  end
Again - is this needed at all?

2022-10-06 10:49 UTC, bblaszkow06 commented on lib/membrane/element/action.ex
> +  - if reason is neither `:normal`, `:shutdown` nor `{:shutdown, term}`, an error is logged
Do a Cmd+c, Cmd+v from previous suggestion

2022-10-06 10:49 UTC, bblaszkow06 commented on test/membrane/pipeline_test.exs
> +      {:ok, supervisor_pid, pipeline_pid} = Membrane.Pipeline.start_link(TrivialPipeline)
```suggestion
      assert {:ok, supervisor_pid, pipeline_pid} = Membrane.Pipeline.start_link(TrivialPipeline)
```

2022-10-06 10:49 UTC, bblaszkow06 commented on test/membrane/pipeline_test.exs
> +      assert module == NotAPipeline
```suggestion
      assert Membrane.Pipeline.start_link(NotAPipeline) == {:error, {:not_pipeline, NotAPipeline}}
```

2022-10-06 10:49 UTC, bblaszkow06 commented on test/membrane/pipeline_test.exs
> +      assert module == NotAPipeline
```suggestion
      assert Membrane.Pipeline.start(NotAPipeline) == {:error, {:not_pipeline, NotAPipeline}}
```

2022-10-06 10:49 UTC, bblaszkow06 commented on test/membrane/pipeline_test.exs
> +      {:ok, supervisor_pid, pipeline_pid} = Membrane.Pipeline.start_link(TrivialPipeline)
too much copy-paste :hand_over_mouth: 
```suggestion
      assert {:ok, pipeline_pid} = Membrane.Pipeline.start(TrivialPipeline)
```

2022-10-06 10:49 UTC, bblaszkow06 commented on test/membrane/pipeline_test.exs
> +      assert Process.alive?(pipeline_pid) == true
You may also check if the processes are linked (it's important since you're doing hacks in supervision)
https://hexdocs.pm/elixir/Process.html#info/2 & https://www.erlang.org/doc/man/erlang.html#process_info-1 should be handy

2022-10-06 13:31 UTC, varsill commented on lib/membrane/core/bin/zombie.ex
> +  @moduledoc false
How about a comment describing what is the purpose of the Zombie bin?

2022-10-06 13:31 UTC, varsill commented on lib/membrane/core/pipeline/zombie.ex
> +  @moduledoc false
The same as in case of Bin.Zombie :D

2022-10-06 13:31 UTC, varsill commented on lib/membrane/core/pipeline/action_handler.ex
> +          "Action #{inspect({name, args})} cannot be handled because the bin is already terminating"
```suggestion
          "Action #{inspect({name, args})} cannot be handled because the pipeline is already terminating"
```

2022-10-06 14:18 UTC, mat-hek commented
@varsill can you answer @bblaszkow06's comments on tests? :P

2022-10-07 11:24 UTC, mat-hek commented on lib/membrane/core/bin.ex
> +  def terminate(_reason, _state) do
I don't think we report termination via telemetry anywhere else, so this is still needed. I can possibly move that to the supervisor though

2022-10-07 11:37 UTC, mat-hek commented on lib/membrane/element/action.ex
> +  - if reason is neither `:normal`, `:shutdown` nor `{:shutdown, term}`, an error is logged
Suggestion by courtesy of Grammarly:
```suggestion
  - use `:normal` for graceful termination. Allowed only when the parent already requested termination,
    i.e. after `c:Membrane.Element.Base.handle_terminate_request/2` is called
```

2022-10-07 11:38 UTC, mat-hek commented on lib/membrane/element/action.ex
> +    by parent, i.e. after `c:Membrane.Element.Base.handle_terminate_request/2` is called
Suggestion by courtesy of Grammarly:
```suggestion
  - use `:normal` for graceful termination. Allowed only when the parent already requested termination,
    i.e. after `c:Membrane.Element.Base.handle_terminate_request/2` is called
```

2022-10-10 08:17 UTC, mat-hek commented on lib/membrane/core/element/pad_controller.ex
> +          "Ignoring unlinking a static pad #{inspect(pad_ref)} because of terminating"
The EoS is sent on each static pad when switching to terminating, so it seems we don't have to undertake any action here

2022-10-10 09:03 UTC, mat-hek commented on lib/membrane/core/pipeline/zombie.ex
> +  @moduledoc false
done

2022-10-10 09:03 UTC, mat-hek commented on lib/membrane/core/bin/zombie.ex
> +  @moduledoc false
done

2022-10-10 10:25 UTC, varsill commented on test/membrane/pipeline_test.exs
> +      {:ok, supervisor_pid, pipeline_pid} = Membrane.Pipeline.start_link(TrivialPipeline)
done

2022-10-10 10:26 UTC, varsill commented on test/membrane/pipeline_test.exs
> +      assert module == NotAPipeline
done

2022-10-10 10:27 UTC, varsill commented on test/membrane/pipeline_test.exs
> +      {:ok, supervisor_pid, pipeline_pid} = Membrane.Pipeline.start_link(TrivialPipeline)
done

2022-10-10 11:39 UTC, varsill commented on test/membrane/pipeline_test.exs
> +      assert module == NotAPipeline
done

2022-10-11 13:02 UTC, varsill commented on lib/membrane/core/element/state.ex
> +    :children_supervisor,
Do we want to call it `children_supervisor`, since element doesn't have any children (in Membrane's nomenclature)?

2022-10-12 09:21 UTC, mat-hek commented on lib/membrane/core/element/state.ex
> +    :children_supervisor,
Yup, elements use it only to spawn utilities via `start_utility`. I'm struggling to figure out a better name though. `SupervisorUsedByComponentsToSpawnWhateverTheyNeed` would be more accurate, but seems too long :P @varsill @bblaszkow06 any ideas?

2022-10-12 14:26 UTC, bblaszkow06 approved these changes

2022-10-12 14:26 UTC, bblaszkow06 commented on lib/membrane/core/element/state.ex
> +    :children_supervisor,
Any ideas:
* `SubprocessSupervisor`
* `ElementsSupervisor` (as in element's supervisor, dunno how to better reflect it in module's name)

2022-10-13 10:17 UTC, merged