Validate parent bin caps
membraneframework/membrane_core pull request #454
Opened 2022-10-11 14:00 UTC by FelonEkonom

2022-10-14 08:41 UTC, varsill reviewed
Good job!
However, apart from some small changes I have suggested, I believe we need a test that checks if it also works for nested bins

2022-10-14 08:41 UTC, varsill commented on lib/membrane/core/bin/pad_controller.ex
> +              parents_accepted_caps: [struct() | module() | tuple()]
Are you sure these specification is correct? What if the bin's caps specification is, for instance, `:any`?

2022-10-14 08:41 UTC, varsill commented on lib/membrane/core/element/caps_controller.ex
> +      for pad #{inspect(pad_ref)}. Specs of accepted caps are:
How about adding information about the element name / module for which the caps matching failed? So that the user wouldn't need to traverse the nested bins one by one to find the problematic specification.

2022-10-14 08:41 UTC, varsill commented on lib/membrane/element/pad_data.ex
> +    - `:parents_accepted_caps` - specification of possible caps that are accepted on the pad in the ancestors of the element.
I wouldn't refer to "ancestors" of the element - why not to simply call them parents?

2022-10-14 08:41 UTC, varsill commented on lib/membrane/core/bin/pad_controller.ex
> +              parents_accepted_caps: [struct() | module() | tuple()]
I see that the `parents_accepted_caps` is aggregated out of `state.pads_info[direction].accepted_caps`, which in fact, are specified as `any` :O https://github.com/membraneframework/membrane_core/blob/4ad63c58a6d733a2e808f4a17f855ab262e52bf5/lib/membrane/core/child/pad_model.ex#L56

2022-10-17 15:35 UTC, FelonEkonom commented on lib/membrane/element/pad_data.ex
> +    - `:parents_accepted_caps` - specification of possible caps that are accepted on the pad in the ancestors of the element.
In this case, by "ancestors" I mean not only parents, but also "grandparents" and their ancestors as well. Naming them `parents` wouldn't suggest only closest parents?

2022-10-18 11:14 UTC, mat-hek requested changes

2022-10-18 11:14 UTC, mat-hek commented on lib/membrane/core/child/pads_specs.ex
> +        match?(unquote(caps_pattern), caps)
This doesn't seem to support a list of patterns. If someone wants to match two different formats, it's going to be tough to do without that possibility. We may also consider making use of elixir's `or` operator instead of a list, WDYT @varsill ?

Also, passing just a format module should work. It can be done by converting it to a match on a struct of that module

2022-10-18 11:14 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> +          %{initiator: :parent, parents_with_pads: [{module(), Pad.name_t()}]}
```suggestion
          %{initiator: :parent, ancestors_pads: [{module(), Pad.name_t()}]}
```

2022-10-18 11:14 UTC, mat-hek commented on lib/membrane/core/element/caps_controller.ex
> +  @spec ensure_caps_match(Pad.direction_t(), [{module(), Pad.name_t()}], Caps.t()) :: :ok
I'd extract that `[{module(), Pad.name_t()}]` to a new type in this module

2022-10-18 11:14 UTC, mat-hek commented on lib/membrane/core/element/caps_controller.ex
> +  def ensure_caps_match(direction, modules_with_pads, caps) do
```suggestion
  def ensure_caps_match!(direction, modules_with_pads, caps) do
```

2022-10-18 11:14 UTC, mat-hek commented on lib/membrane/core/element/caps_controller.ex
> +      if not module.caps_match?(pad_name, caps) do
It's a unique occasion to use unless :P

```suggestion
      unless module.caps_match?(pad_name, caps) do
```

2022-10-18 11:14 UTC, mat-hek commented on test/membrane/core/element/action_handler_test.exs
> +    # end
fix or remove

2022-10-18 11:56 UTC, varsill commented on test/support/caps_test/inner_source_bin.ex
> +  Has caps pattern for `:output` pad.
```suggestion
It has a caps pattern defined for the `:output` pad.
```

2022-10-18 11:56 UTC, varsill commented on test/support/caps_test/outer_sink_bin.ex
> +  Has caps pattern for `:input` pad.
```suggestion
It has a caps pattern defined for the `:input` pad.
```

2022-10-18 11:56 UTC, varsill commented on test/support/caps_test/outer_source_bin.ex
> +  Has caps pattern for `:output` pad.
It has a caps pattern defined for the `:output` pad.

2022-10-18 11:56 UTC, varsill commented on test/membrane/integration/caps_test.exs
> +    end
You could add here also a test to make sure there is a crash when the format is not accepted by the elements themselves.

2022-10-18 11:56 UTC, varsill commented on test/membrane/integration/caps_test.exs
> +  end
How about parametrizing it so that to have `assert_down(name)` function?

2022-10-18 12:01 UTC, FelonEkonom commented on lib/membrane/core/child/pads_specs.ex
> +        match?(unquote(caps_pattern), caps)
IMO using `or` or `|` operator to have a collection of checked patterns is ok, but using a list could be confusing because it might be mistaken with the match on the whole list. Beyond this, are you sure, we need to support passing just a format module? It could lead to potential ambiguity when a value of a field also should be a struct, and writing a match on a struct is not much harder than passing only a module name

2022-10-19 06:12 UTC, varsill commented on lib/membrane/core/element/action_handler.ex
> +      %{name: pad_name, parents_with_pads: parents_with_pads} = pad_data
Well, I thought only of fetching: `:name`,  `:parents_with_pads` all along with `:direction`, `:pid` and `other_ref`

2022-10-19 08:16 UTC, mat-hek commented on lib/membrane/core/child/pads_specs.ex
> +        match?(unquote(caps_pattern), caps)
`or` is not hard to handle:
```elixir
def or_to_list({:or, _meta, [a, b]}), do: or_to_list(a) ++ or_to_list(b)
def or_to_list(term), do: [term]
```
I'd rather worry about the fact that it normally accepts booleans, not patterns

2022-10-19 13:56 UTC, FelonEkonom commented on lib/membrane/core/bin/pad_controller.ex
> +              parents_with_pads: [{module(), Pad.name_t()}]
@mat-hek what is your impression? IMO `parents_with_pads` is ok, because it suggests, that we deal with parents and **their** pads (not parents and **some** pads)

2022-10-19 14:15 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> +              parents_with_pads: [{module(), Pad.name_t()}]
I'd stick to `ancestors_pads` :P

2022-10-19 14:53 UTC, FelonEkonom commented on lib/membrane/core/child/pads_specs.ex
> +        match?(unquote(caps_pattern), caps)
Because of operators precedence, it is not a good idea to use `|` or `or`, because in both cases expression like `a | b when b == 2 | c` is equal to `(a | b) when (b == 2 | c)`. Another option, beyond list, is to use our custom function call (something like `alternative(a, b when b == 2, c)`) and convert it to list during parsing AST

2022-10-19 15:30 UTC, FelonEkonom commented on test/support/caps_test/source.ex
> +  def handle_playing(_ctx, state) do
Unfortunately, it sometimes crashes without this match

2022-10-19 15:34 UTC, FelonEkonom commented on lib/membrane/core/bin/pad_controller.ex
> +              parents_with_pads: [{module(), Pad.name_t()}]
Yeah, but we hold there not only pads, but related modules as well, so maybe `ancestors_with_pads`?

2022-10-20 09:03 UTC, mat-hek commented on lib/membrane/core/child/pads_specs.ex
> +        match?(unquote(caps_pattern), caps)
That's a valid point, I'd stick to the list then. That's what the voice of people said too, as well as that passing a bare module shall be supported :P

2022-10-20 12:54 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> +              parents_with_pads: [{module(), Pad.name_t()}]
Doesn't matter much to me

2022-10-20 12:57 UTC, mat-hek commented on test/support/caps_test/source.ex
> +  def handle_playing(_ctx, state) do
can't you just pass the caps via options?

2022-10-21 11:49 UTC, mat-hek requested changes

2022-10-21 11:51 UTC, FelonEkonom commented on lib/membrane/bin/pad_data.ex
> +          caps_pattern: String.t(),
It is used to generate docs

2022-10-21 13:35 UTC, mat-hek requested changes

2022-10-21 13:35 UTC, mat-hek commented on lib/membrane/core/child/pads_specs.ex
> +        {:alternative, _meta, args} -> args
I think it would introduce more confusion than profit in the end, so I'd remove that, at least for now

2022-10-21 13:35 UTC, mat-hek commented on lib/membrane/pad.ex
> +  @type module_with_pad_t() :: {module(), name_t()}
I don't think we need this type. At least it shouldn't be public

2022-10-21 13:35 UTC, mat-hek commented on lib/membrane/pad.ex
> -          | {:caps, Caps.Matcher.caps_specs_t()}
This shouldn't disappear and the docs should say how the caps specification should look like

2022-10-24 11:26 UTC, FelonEkonom commented on lib/membrane/pad.ex
> +  @type module_with_pad_t() :: {module(), name_t()}
https://github.com/membraneframework/membrane_core/pull/454#discussion_r998057448

2022-10-24 11:32 UTC, FelonEkonom commented on lib/membrane/pad.ex
> +  @type module_with_pad_t() :: {module(), name_t()}
Do you have an idea for a better name for this type?

2022-10-24 12:34 UTC, mat-hek commented on lib/membrane/pad.ex
> +          | {:caps_pattern, code :: any()}
This still doesn't tell how the caps specification should actually look like. Let's create `caps_pattern_t` and describe that in its typedoc

2022-10-24 12:34 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> +          %{initiator: :parent, ancestors_with_pads: CapsController.caps_validation_params_t()}
So ancestors_with_pads can now become caps_validation_params ;)

2022-10-24 14:37 UTC, varsill commented on lib/membrane/element/pad_data.ex
> +          caps_pattern: String.t(),
`caps_pattern` should be listed as one of the public fields avaibale in the `PadData` structure, along with the description of that field

2022-10-24 14:51 UTC, varsill commented on lib/membrane/pad.ex
> +  @type caps_t :: any()
I am not sure if typespec `any()` should be used to describe a pattern - but I've no idea how it should be typespeced either :D

2022-10-24 14:58 UTC, varsill reviewed
Some small things to reconsider

2022-10-24 15:18 UTC, mat-hek commented on lib/membrane/element/pad_data.ex
> +          caps_pattern: String.t(),
Not sure if we should make it public. But if so, this should be rather kept as AST

2022-10-24 15:22 UTC, mat-hek commented on lib/membrane/pad.ex
> +  @type caps_t :: any()
There's probably no better way, unfortunately. But I suggested a change that may improve it a bi

2022-10-26 13:55 UTC, FelonEkonom commented
Changes from here were moved to https://github.com/membraneframework/membrane_core/pull/463

2022-10-26 13:55 UTC, closed without merging