Improved spec
membraneframework/membrane_core pull request #458
Opened 2022-10-21 11:32 UTC by varsill

The new API for defining children and links between them has been introduced:
```elixir
unlinked_children = [
  child(:child_name, %ChildStruct{}),
  child(:child_name, %ChildStruct{}, ignore_duplicates: true)
]

links = [
  get_child(:first_child) |> get_child(:second_child),
  child(:third_child, % ChildStruct{}) |> child(:fourth_child, % ChildStruct{}),   
  child(:fifth_child, % ChildStruct{}, ignore_duplicates: true) 
    |> child(:sixth_child, % ChildStruct{}, ignore_duplicates: true),
  child(% ChildStruct{}) |> child(% ChildStruct{}) #spawning anonymous children
]
spec = %ChildrenSpec{structure: unlinked_children ++ links}
```

2022-10-28 14:23 UTC, mat-hek requested changes

2022-10-28 14:23 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +       dont_spawn_if_already_exists: Keyword.get(opts, :get_if_exists, false)}
Let's use `Bunch.Config.parse` to detect typos

2022-10-28 14:23 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +          {Child.name_t(), child_spec_t(), child_spec_extension_options_t()}
- why do we have another type for the same options
- these should be opaque
- these aren't used in this module
- maybe `child_spec_with_options` would be more accurate

2022-10-28 14:23 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
>            Parent.state_t()
this should fit in one line

2022-10-28 14:23 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +    |> Enum.filter(&(&1 != nil))
This could be done with just Enum.filter. Also, matching on a keyword like that isn't future-proof. It's better to convert this to a map earlier

2022-10-28 14:23 UTC, mat-hek commented on lib/membrane/core/parent/structure_parser.ex
> +          {[raw_link_t], [ChildrenSpec.child_spec_extended_t()]} | no_return
IMO returning `{children, links}` (reverse order) would be more natural

2022-11-04 08:39 UTC, varsill commented on lib/membrane/children_spec.ex
> +          structure_builder_t()
done

2022-11-04 08:40 UTC, varsill commented on lib/membrane/children_spec.ex
> +  def child(child_name, child_spec, opts \\ @default_child_opts)
We have `child/4` defined

2022-11-04 08:46 UTC, varsill commented on lib/membrane/children_spec.ex
> +          {Child.name_t(), child_spec_t(), child_spec_extension_options_t()}
`extended_childspec_opts` was meant to be internally used, and `child_spec_opts` were the ones to be used by user. However, it seems that these options in fact are the same (well, we have only one option ;D) 
I've decided to slightly redesign it - there is no more `extended_childrenspec_t`, I've introduced `@type child_definition_t :: struct() | module()` instead of `child_spec_t` and the `child_spec_t` is now what use to be `extended_childrenspec_t` before
I know it sounds confusing, but I suggest looking at those typespecs in children_spec.ex once again - and I hope it is now much more clear ;)

2022-11-04 09:19 UTC, varsill commented on lib/membrane/core/parent/structure_parser.ex
> +          {[raw_link_t], [ChildrenSpec.child_spec_extended_t()]} | no_return
done

2022-11-04 09:26 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +    |> Enum.filter(&(&1 != nil))
indeed, I have no idea what I had in mind while writing that ;D 
done

2022-11-04 09:27 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
>            Parent.state_t()
it doesn't :<

2022-11-04 09:27 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +    |> Enum.filter(&(&1 != nil))
I guess it made sense before other changes ;)

2022-11-04 09:30 UTC, varsill commented on lib/membrane/children_spec.ex
> +    child(:sink, Sink)]
docs are yet to be rewritten, but I will keep that in mind

2022-11-04 13:07 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +  def child(child_name, child_spec, opts \\ @default_child_opts)
Indeed, haven't noticed. But maybe we could put `child/3` next to `child/4` and `do_child/3` next to `do_child/4`?

2022-11-04 13:34 UTC, mat-hek requested changes

2022-11-04 13:34 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +          crash_group: Membrane.CrashGroup.t(),
```suggestion
          crash_group: Membrane.CrashGroup.t() | nil,
```

2022-11-04 13:34 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +    raise "Link builder cannot be used as a child name! Perhaps you meant to use get_child/2?"
How do we know that the user tried to pass a builder as a child name here?

2022-11-04 13:34 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +  @type childrenspec_options_t :: [
```suggestion
  @type children_spec_options_t :: [
```

2022-11-04 13:34 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +  def get_default_childrenspec_options(), do: @default_childrenspec_options
I'd keep the defaults in the child_life_controller instead

2022-11-04 13:34 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +    specs_for_this_options = Enum.filter(spec, &(not is_tuple(&1)))
Use `Enum.split`

2022-11-04 13:34 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +        not (Keyword.get(options, :get_if_exists) and Map.has_key?(state_children, name))
```suggestion
    |> Enum.reject(fn
      {name, _child_spec, options} ->
        Keyword.get(options, :get_if_exists) and Map.has_key?(state_children, name)
```

2022-11-07 14:21 UTC, varsill commented on lib/membrane/children_spec.ex
> +          crash_group: Membrane.CrashGroup.t(),
done

2022-11-07 14:22 UTC, varsill commented on lib/membrane/children_spec.ex
> +  @type childrenspec_options_t :: [
done

2022-11-07 14:22 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +    specs_for_this_options = Enum.filter(spec, &(not is_tuple(&1)))
done

2022-11-07 14:24 UTC, varsill commented on lib/membrane/children_spec.ex
> +  def get_default_childrenspec_options(), do: @default_childrenspec_options
done

2022-11-07 14:28 UTC, varsill commented on lib/membrane/children_spec.ex
> +    raise "Link builder cannot be used as a child name! Perhaps you meant to use get_child/2?"
Indeed, after changes concerning the the handled children names it is not necessary that the first argument is a linkbuilder :D I have changed the error message.

2022-11-07 17:12 UTC, mat-hek requested changes

2022-11-08 08:34 UTC, varsill commented on lib/membrane/children_spec.ex
> +  def child(child_name, child_spec, opts \\ @default_child_opts)
done

2022-11-10 10:23 UTC, varsill commented on lib/membrane/children_spec.ex
> +          {Child.name_t(), child_definition_t(), child_opts_map_t()}
done

2022-11-10 13:36 UTC, mat-hek requested changes

2022-11-10 13:36 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +      Enum.map_reduce(children_definitions, state, fn {children_definitions_with_given_options,
let's use flat_map_reduce and extract this to a private function

2022-11-14 13:30 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +  defp make_canonical({spec, options_keywords_list}, previous_level_options_keywords_list) do
done

2022-11-15 14:03 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +  @type children_spec_options_map_t :: %{
is this used anywhere?

2022-11-15 14:20 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +  @type children_spec_options_map_t :: %{
It's not :/ 
https://github.com/membraneframework/membrane_core/pull/458#discussion_r1016343567

2022-11-15 14:20 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +      |> Map.new()
done

2022-11-15 14:32 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +  defp setup_children(
done

2022-11-16 11:20 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +           Membrane.ChildrenSpec.children_spec_options_t()}
```suggestion
  @spec make_canonical(Membrane.ChildrenSpec.t(), children_spec_options_map_t()) :: [
          {[Membrane.ChildrenSpec.structure_builder_t()], children_spec_options_map_t()}
```

2022-11-16 11:20 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +  @typep children_spec_options_map_t :: %{
```suggestion
  @typep parsed_children_spec_options_t :: %{
```

2022-11-16 13:22 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +           Membrane.ChildrenSpec.children_spec_options_t()}
done

2022-11-16 14:41 UTC, merged