Children groups
membraneframework/membrane_core pull request #461
Opened 2022-10-24 15:35 UTC by varsill

This PR introduces children groups - a way to aggregate children so that all the children being part of a group can be referenced at once.

2022-11-25 11:46 UTC, mat-hek requested changes

2022-11-25 11:46 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +      Enum.map(children_definitions, fn {children_definitions, children_spec_options} ->
maybe the full name resolution could be done in make_cannonical? children names in links could be updated there as

2022-11-25 11:46 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +  spec2 = get_child({:first_group, :source}) |> child(:sink, Sink)
It seems this way is ambiguous - what if we spawn a child in which the name is a 2-tuple, with first element being an id of some group? Maybe we could pass the group via an option to get_child?

2022-11-25 11:46 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +  spec2 = get_child({:first_group, :source}) |> child(:sink, Sink)
And there are some typos in this doc - let's pass it through grammarly

2022-11-25 15:50 UTC, varsill commented on lib/membrane/children_spec.ex
> +  spec1 = {links1, children_group_id: :first_children_group}
I agree ;)

2022-11-28 11:34 UTC, varsill commented on lib/membrane/core/observability.ex
> +      end
It does, however note one thing. 
A full name of a child, for whom a children group has been specified, is a tuple of form: `{children_group_id, children_name_as_provided_by_user}`, while a full name of child which is not in any children group is `children_name_as_provided_by_user` - and in fact, `children_name_as_provided_by_user` might be a tuple. It would be problematic to fetch the children_group_id out of a full name, so IMO it's easier to store it in another place

2022-11-28 11:41 UTC, varsill commented on lib/membrane/children_spec.ex
> +  spec1 = {links1, children_group_id: :first_children_group}
done

2022-11-28 11:50 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +  defp check_if_children_names_and_children_groups_ids_are_unique(children_definitions, state) do
done

2022-11-28 11:51 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +    if length(duplicated) > 0,
done

2022-11-28 13:02 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +      Enum.map(children_definitions, fn {children_definitions, children_spec_options} ->
Hmm, we need to somewhere check if the group ids are different than the children names, for the whole spec -  and that needs to be done before the name is mapped into the fullname. 
It could be done in `make_canonical`, but we would need to aggregate a state holding all the previously seen group ids and children names - I believe, extracting the name mapping process into a separate function should be enough, WDYT?

2022-11-28 16:42 UTC, varsill commented on lib/membrane/children_spec.ex
> +  spec2 = get_child({:first_group, :source}) |> child(:sink, Sink)
I am afraid that with the current implementation (where children group makes the child `:some_name` become `{children_group_id, :some_name}`, passing the group via an option to `get_child` won't help anyhow, it would be just another syntax sugar. In case somebody has spawned a child with a name of the following form: `{<children_group_id>, :some_name}`, it won't be possible to distinguish if both the `get_child(`{<children_group_id>, :some_name})` and `get_child(`:some_name, group: <children_group_id>)` should refer to the child with name: `{<children_group_id>, :some_name}` or to `:some_name` child within the `<children_group_id>` group. The solution would be to add another condition checking if the child name does not interfere with the existing children groups (and the other way round).

2022-11-28 16:47 UTC, varsill commented on lib/membrane/children_spec.ex
> +  spec2 = get_child({:first_group, :source}) |> child(:sink, Sink)
Another solution would be to seek for `ChildEntry` (which has a `group` field) while using `get_child` - but it would make the StructureBuilder parsing more complicated

2022-11-28 17:51 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +  spec2 = get_child({:first_group, :source}) |> child(:sink, Sink)
We could add some unique prefix, like `{:__membrane_child__, name, group_id}` to solve that

2022-11-28 18:14 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +      Enum.map(children_definitions, fn {children_definitions, children_spec_options} ->
We check for that in `check_if_children_names_and_children_groups_ids_are_unique`

2022-11-29 07:53 UTC, varsill commented on lib/membrane/children_spec.ex
> +  spec2 = get_child({:first_group, :source}) |> child(:sink, Sink)
I'm always a bit afraid to use such "unique" prefix since they are not necessary reserved for us :/ However, we can always raise once somebody uses such a prefix, so perhaps this is the way

2022-11-30 12:43 UTC, mat-hek commented on lib/membrane/children_spec.ex
> +  spec2 = get_child({:first_group, :source}) |> child(:sink, Sink)
I think we can consider them reserved, but we can use a struct as well - the child name cannot be a struct. This would allow us to implement the inspect protocol for it too

2022-12-05 12:24 UTC, mat-hek requested changes

2022-12-05 13:32 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +  @opaque parsed_children_spec_options_t :: %{
Well, this type is used externally only by `StartupUtil.scheck_if_children_names_and_children_groups_ids_are_unique` - and that function does not manipulate the internals of the type. In fact, `StartupUtil.scheck_if_children_names_and_children_groups_ids_are_unique` needs to use of that type since there is a need to emphasize, that the input argument is in the `canonical form` - perhaps we should add a `children_spec_canonical_form_t` type than, and make `parsed_children_spec_options_t` private?

2022-12-05 13:59 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +      Enum.map(specs, fn spec ->
well, sure ;) Done

2022-12-05 14:00 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +  defp equip_spec_with_children_refs(specs, group) do
indeed, done

2022-12-05 14:07 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +  @opaque parsed_children_spec_options_t :: %{
Good idea ;)

2022-12-05 14:20 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +      ref -> ref
done

2022-12-05 14:24 UTC, varsill commented on guides/upgrading/v0.11.md
>  + {[spec: spec], %{}}
I have removed that a few commits before, I don't know how has it appeared there and how was it still visible to you :D

2022-12-05 15:27 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +  @opaque parsed_children_spec_options_t :: %{
done

2022-12-09 08:25 UTC, merged