Improve caps
membraneframework/membrane_core pull request #463
Opened 2022-10-25 14:41 UTC by FelonEkonom

Contains changes from https://github.com/membraneframework/membrane_core/pull/454
Related Jira tickets:
 * https://membraneframework.atlassian.net/browse/MC-53
 * https://membraneframework.atlassian.net/browse/MC-76

2022-10-26 10:07 UTC, mat-hek requested changes

2022-10-26 10:07 UTC, mat-hek commented on lib/membrane/core/child/pads_specs.ex
> +    "<code>#{pattern_string}</code>"
````suggestion
    """
    ```
    #{pattern_string}
    ```
    """
````

Also, it would be better if a list of caps generated a code block for each pattern in the list

2022-10-26 13:04 UTC, FelonEkonom commented on lib/membrane/core/child/pads_specs.ex
> +    specs = [{:caps_pattern, Macro.to_string(caps_pattern)} | specs]
Because in `PadData` we hold under key `:caps` value passed to action `:caps`, so 
1) it would be inconsistent
2) it could lead to bugs, when somebody will forget, that in different structs value stored under this same key means something totally different

2022-10-26 14:52 UTC, FelonEkonom commented on lib/membrane/core/child/pads_specs.ex
> +    "<code>#{pattern_string}</code>"
Having ``` instead of `<code>` leads to such a warnings
```
warning: ExDoc.Markdown.Earmark (warning) test/support/caps_test/outer_sink_bin.ex:24 Failed to find closing <tr>
```

2022-10-27 07:59 UTC, mat-hek commented on mix.exs
> +  defp elixirc_paths(_env), do: ["lib", "spec/support", "test/support"]
why this change? BTW, `spec/support` is not there anymore

2022-10-27 10:39 UTC, varsill commented on lib/membrane/element/pad_data.ex
> +          caps_validation_params: private_field(),
NIT - how about keeping it consistent and `private_field` instead of `private_field()`?

2022-10-27 10:39 UTC, varsill commented on lib/membrane/pad.ex
> +  @type caps_t :: module() | (pattern :: term())
Why not `caps_pattern_t`? 
(Associated with the next comment, just below that one)

2022-10-27 10:39 UTC, varsill commented on lib/membrane/pad.ex
> +  action.
I believe we are missing a part of docs that would describe how the caps pattern should look like

2022-10-27 10:39 UTC, varsill commented on lib/membrane/pad.ex
> +          | {:caps, caps_t() | [caps_t()]}
I know we have decided to rethink the naming, but perhaps now is the time - I am not keen on calling that option `:caps` and I would prefer `:caps_pattern`

2022-10-27 10:39 UTC, varsill commented on lib/membrane/pad.ex
> +          :caps_pattern => String.t() | [String.t()],
Perhaps it should be called `:caps_pattern_str`?

2022-10-27 10:39 UTC, varsill commented on lib/membrane/core/child/pads_specs.ex
> +        in form of %:any{}, not >>any<< caps (to achieve such a effect, put
```suggestion
        in form of %:any{}, not >>any<< caps (to achieve such an effect, put
```

2022-10-27 10:39 UTC, varsill commented on lib/membrane/core/child/pads_specs.ex
> +        in form of %:any{}, not >>any<< caps (to achieve such a effect, put
Generally speaking, I am not convinced that the part of the sentence: `...will be satisified by caps
        in form of %:any{}` is true - `:any` has no `__struct__` field, so trying to match on `:any`'s struct will probably simply produce an error

2022-10-27 10:39 UTC, varsill commented on test/support/distributed.ex
> +      caps = %Membrane.Support.Distributed.SomeCaps{}
```suggestion
      caps = %SomeCaps{}
```
NIT

2022-10-27 11:19 UTC, mat-hek commented on lib/membrane/pad.ex
> +          | {:caps, caps_t() | [caps_t()]}
Agreed, but I'd merge this first

2022-10-27 11:23 UTC, mat-hek commented on lib/membrane/core/child/pads_specs.ex
> +        in form of %:any{}, not >>any<< caps (to achieve such a effect, put
In practice, yes, but theoretically anyone can do
```elixir
defmodule :any do
  defstruct ...
end
```

2022-10-27 14:57 UTC, mat-hek approved these changes

2022-10-28 15:07 UTC, varsill approved these changes
LGTM, but I've left a few unresolved comments with some change suggestions concerning the spelling

2022-10-28 15:07 UTC, varsill commented on CHANGELOG.md
> + * Pass Elixir patterns to `:caps` in pad definition.
```suggestion
 * Use Elixir patterns as `:caps` in pad definition.
```

2022-10-31 11:11 UTC, merged