Remove :type from def_options
membraneframework/membrane_core pull request #466
Opened 2022-10-26 12:56 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-77

2022-10-26 13:23 UTC, varsill requested changes

2022-10-26 13:23 UTC, varsill commented on lib/membrane/time.ex
> +  def inspect(time) when is_time(time) do
How does it correspond to: https://github.com/membraneframework/membrane_core/pull/465 ? :D

2022-10-26 13:23 UTC, varsill commented on lib/membrane/core/options_specs.ex
>      opts_typespecs = KVEnum.map_values(opts, & &1[:spec])
Why not to do it in one line?

2022-10-26 13:49 UTC, FelonEkonom commented on lib/membrane/time.ex
> +  def inspect(time) when is_time(time) do
My changes would make it unnecessary

2022-10-28 14:27 UTC, mat-hek requested changes

2022-11-03 13:55 UTC, mat-hek approved these changes

2022-11-03 13:55 UTC, mat-hek commented on lib/membrane/core/options_specs.ex
> +        creating documentation instead of `inspect/1`, eg. `inspector: &Time.inspect/1`
```suggestion
        creating documentation instead of `inspect/1`, eg. `inspector: &Membrane.Time.inspect/1`
```

2022-11-03 15:12 UTC, merged