add playback related changes to the release guide
membraneframework/membrane_core pull request #472
Opened 2022-11-07 13:32 UTC by mat-hek

2022-11-08 08:57 UTC, varsill requested changes

2022-11-08 08:57 UTC, varsill commented on guides/upgrading/v0.11.md
> +Remove `handle_playing_to_prepared/2`, `handle_prepared_to_stopped/2` and `handle_shutdown/2`. Instead, use `Membrane.ResourceGuard`, `Membrane.UtilitySupervisor` or `handle_terminate_request/2`ą
```suggestion
Remove `handle_playing_to_prepared/2`, `handle_prepared_to_stopped/2` and `handle_shutdown/2`. Instead, use `Membrane.ResourceGuard`, `Membrane.UtilitySupervisor` or `handle_terminate_request/2`:
```

2022-11-08 08:57 UTC, varsill commented on guides/upgrading/v0.11.md
> ++ def handle_setup(ctx, state) do
How about a brief description of when to use `handle_init/2` and when to use `handle_setup/2`?

2022-11-08 08:57 UTC, varsill commented on guides/upgrading/v0.11.md
> ++  # or you can do that manually with `Membrane.Resource.cleanup_resource/2`
Are you sure that this sentence is saying what it is meant to say? :D 
I am not sure if that `or` statement fits in the place.

2022-11-08 08:57 UTC, varsill commented on guides/upgrading/v0.11.md
> +Remove `:type` key and related value from defined options. Add `:spec` instead, if it hasn't been added before, and proper `:inspector`, if the option has a default value, that shouldn't be inspected
```suggestion
Remove `:type` key and related value from the options definitions. Add `:spec` instead, if it hasn't been added before, and proper `:inspector`, if the option has a default value, that shouldn't be inspected by `inspect/1` during generating docs.
```

2022-11-08 14:28 UTC, FelonEkonom approved these changes

2022-11-16 11:59 UTC, mat-hek commented on guides/upgrading/v0.11.md
> ++ def handle_setup(ctx, state) do
done

2022-11-17 17:09 UTC, varsill approved these changes

2022-11-18 08:38 UTC, merged