Updating guide - parent/children communication and childrenspecs
membraneframework/membrane_core pull request #474
Opened 2022-11-15 09:31 UTC by varsill

Describe changes concerning parent/children communication and childrenspecs

2022-11-16 12:13 UTC, mat-hek requested changes

2022-11-16 12:13 UTC, mat-hek commented on guides/upgrading/v0.11.md
> +* `Membrane.Pipeline.handle_element_end_of_stream/3` into `Membrane.Pipeline.handle_element_end_of_stream/4`
```suggestion
```

I'd remove that, I think that explanation below and the example is enough

2022-11-16 12:13 UTC, mat-hek commented on guides/upgrading/v0.11.md
> +## Update the signatures of `handle_element_start_of_stream` and `handle_element_end_of_stream`
Since these are callbacks, I'd move them to the callbacks section, just mention that this applies to pipelines and bins only

2022-11-16 12:13 UTC, mat-hek commented on guides/upgrading/v0.11.md
> +## Update functions used for children <-> parent communication
let's move that to callbacks and actions, respectively

2022-11-16 12:13 UTC, mat-hek commented on guides/upgrading/v0.11.md
> +Since there are quite a few changed concerning children definition, we have decided to present them in the subsections below.
```suggestion
Since there are quite a few changes concerning children definition, we have decided to present them in the subsections below.
```

2022-11-16 12:13 UTC, mat-hek commented on guides/upgrading/v0.11.md
> ++ links = [get_child(:source) |> child(:another_filter, SomeFilter) |> get_child(:filter) |> child(:sink, SomeSink)]
```suggestion
+ structure = [
+   child(:source, SomeSource),
+   child(:filter, SomeFilter),
+   get_child(:source) |> child(:another_filter, SomeFilter) |> get_child(:filter) |> child(:sink, SomeSink)
+ ]
```

2022-11-16 12:13 UTC, mat-hek commented on guides/upgrading/v0.11.md
> ++ structure = children ++ links
```suggestion
```

2022-11-16 12:13 UTC, mat-hek commented on guides/upgrading/v0.11.md
> +```
I think we decided to move that to 1.0

2022-11-16 12:13 UTC, mat-hek commented on guides/upgrading/v0.11.md
> ++ spec = {children ++ links, children_group_id: :first_group, crash_group_mode: :temporary, node: another_node}
As above, I would encourage creating both children and links in the same list

2022-11-16 13:39 UTC, varsill commented on guides/upgrading/v0.11.md
> +* `Membrane.Pipeline.handle_element_end_of_stream/3` into `Membrane.Pipeline.handle_element_end_of_stream/4`
indeed, done

2022-11-16 13:41 UTC, varsill commented on guides/upgrading/v0.11.md
> ++ links = [get_child(:source) |> child(:another_filter, SomeFilter) |> get_child(:filter) |> child(:sink, SomeSink)]
done

2022-11-16 13:42 UTC, varsill commented on guides/upgrading/v0.11.md
> ++ structure = children ++ links
done

2022-11-16 13:42 UTC, varsill commented on guides/upgrading/v0.11.md
> +```
indeed, I've removed that

2022-11-16 13:45 UTC, varsill commented on guides/upgrading/v0.11.md
> ++ spec = {children ++ links, children_group_id: :first_group, crash_group_mode: :temporary, node: another_node}
done

2022-11-16 14:00 UTC, varsill commented on guides/upgrading/v0.11.md
> +## Update the signatures of `handle_element_start_of_stream` and `handle_element_end_of_stream`
done

2022-11-16 15:42 UTC, FelonEkonom commented on guides/upgrading/v0.11.md
> +  * add an implementation of the `Membrane.Bin.handle_parent_notification/3` and `Membrane.Element.handle_parent_notification/3` in place of the `Membrane.Bin.handle_other/3` and `Membrane.Pipeline.h
```suggestion
  * add an implementation of the `Membrane.Bin.handle_parent_notification/3` and `Membrane.Element.handle_parent_notification/3` in place of the `Membrane.Bin.handle_other/3` and `Membrane.Element.handle_other/3` that

```

2022-11-16 15:44 UTC, FelonEkonom commented on guides/upgrading/v0.11.md
> +We have restricted the available names for the children. Previously, the children name could be of `any()` type, now it is specified as follows: `tuple() | atom()`.
Are you sure, that we want to put there `tuple() | atom()`, not `{atom(), any()} | any()`?

2022-11-21 09:52 UTC, mat-hek approved these changes

2022-11-21 09:52 UTC, merged