Add :handle_tick implementation to the Zombie modules
membraneframework/membrane_core pull request #485
Opened 2022-11-29 15:48 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-111

2022-11-30 08:05 UTC, varsill reviewed
Just a general comment.- shouldn't we iterate through all the callbacks in a module (i.e. `Bin.behaviour_info(:callbacks)`) and then check, if given callback was defined with `defoverridable` (with the `Module.overridable?` function) - if so, we should call it's `super()` function, and otherwise we should return `{[], %{}}`?

2022-11-30 12:50 UTC, mat-hek commented
@FelonEkonom I'd just cancel all the timers when switching to the zombie mode

2022-12-01 11:01 UTC, mat-hek requested changes

2022-12-01 14:23 UTC, mat-hek approved these changes

2022-12-02 12:56 UTC, merged