Update Membrane.Time API
membraneframework/membrane_core pull request #494
Opened 2022-12-08 14:49 UTC by FelonEkonom

2022-12-12 16:06 UTC, varsill requested changes

2022-12-12 16:06 UTC, varsill commented on lib/membrane/time.ex
> +  Divides timestamp by timebase. Rounded to the nearest integer.
```suggestion
  Divides timestamp by a timebase. The result is rounded to the nearest integer.
```

2022-12-12 16:06 UTC, varsill commented on lib/membrane/time.ex
> +    nearest integer.
I would avoid the statement `if second argument is not provided` and instead I would stick to saying that "the default value of the second argument is `:exact`"

2022-12-14 10:37 UTC, mat-hek commented on lib/membrane/time.ex
> +    equal to `:round`, the result is rounded to the nearest integer.
```suggestion
    Returns time in #{unit.plural}.
    
    If the `mode` argument is equal to `:exact` (default), the result is
    represented as a rational number. Otherwise, if the `mode` is
    equal to `:round`, the result is rounded to the nearest integer.
```

2022-12-14 10:37 UTC, mat-hek commented on lib/membrane/time.ex
> +    @spec unquote(as_fun_name)(t, :round | :exact) :: integer | Ratio.t()
```suggestion
    @spec unquote(as_fun_name)(t, mode :: :round | :exact) :: integer | Ratio.t()
```

2022-12-15 11:17 UTC, varsill commented on CHANGELOG.md
> + * Rename `Membrane.Time.to_<unit name>/1` into `Membrane.Time.round_to_<unit name>/1` to indicate that the result will be rounded. Make `Membrane.Time.<plural unit name>/1` accept `%Ratio{}` as an a
Why are you modifying 0.11.0 changelog? The `Membrane.Time.round_to_timebase/2` was in fact added then.

2022-12-15 12:37 UTC, mat-hek approved these changes

2022-12-15 13:08 UTC, FelonEkonom commented on CHANGELOG.md
> + * Rename `Membrane.Time.to_<unit name>/1` into `Membrane.Time.round_to_<unit name>/1` to indicate that the result will be rounded. Make `Membrane.Time.<plural unit name>/1` accept `%Ratio{}` as an a
I have only deleted `/2` suffix. I have made this change to fix failing CI tests, eg:

https://app.circleci.com/pipelines/github/membraneframework/membrane_core/2359/workflows/c25316d2-cd55-4dca-b4d4-7a6a430b75ce/jobs/5637

2022-12-20 09:23 UTC, varsill approved these changes

2022-12-20 15:50 UTC, merged