Remove :playback action
membraneframework/membrane_core pull request #496
Opened 2022-12-12 16:51 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-108

2022-12-21 16:36 UTC, varsill commented on lib/membrane/pipeline/action.ex
> +  @type setup_t :: {:setup, :defer | :complete}
A typedoc would be required

2022-12-21 16:36 UTC, varsill commented on lib/membrane/playback.ex
> -  Playback can be controlled with `t:Membrane.Pipeline.Action.playback_t/0`.
Perhaps it would be good to describe when the playback is changed with the deferred setup mechanism?

2022-12-21 16:36 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +    assert_static_pads_linked(children_definitions, links)
NIT 
```suggestion
    :ok = assert_static_pads_linked(children_definitions, links)
```

2022-12-21 16:36 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +    assert_static_pads_linked(children_definitions, links)
With such an implementation, it's clear for the code reader that we haven't forgotten about the return value

2022-12-21 16:36 UTC, varsill commented on lib/membrane/core/playback_controller.ex
> +  @spec assert_operation_allowed(setup_operation_t(), atom(), boolean()) :: :ok | no_return()
do we need that spec and the `do_assert` subfunctions for a private function?

2022-12-21 16:36 UTC, varsill commented on lib/membrane/bin/action.ex
> +  @type setup_t :: {:setup, :defer | :complete}
typespec would be welcomed

2022-12-21 16:36 UTC, varsill commented on lib/membrane/core/playback_controller.ex
> +    Action {:setup, :defer} was returned from callback #{inspect(callback)}, but setup has already been deferred
I believe with that clause we posses even more information, that could be put into the error message. 
We know, that it is due to a `setup: defer` being returned by `handle_setup`, when it has already been returned by the `handle_init`

2022-12-21 16:36 UTC, varsill commented on lib/membrane/core/playback_controller.ex
> +  defp assert_operation_allowed(operation, callback, deferred?) do
```suggestion
  defp assert_operation_allowed!(operation, callback, deferred?) do
```

2022-12-21 16:36 UTC, varsill commented on lib/membrane/core/playback_controller.ex
> +        state
```suggestion
      Component.is_child?(state) ->
        Membrane.Logger.debug("Child initialized")
        Message.send(state.parent_pid, :initialized, state.name)
        state
```

2022-12-21 16:36 UTC, varsill commented on lib/membrane/core/playback_controller.ex
> +  def defer_setup(state) do
I don't think that function is used anywhere outside of that module

2022-12-21 16:36 UTC, varsill commented on test/membrane/core/pipeline_test.exs
> +          {:spec, [child(:a, TestBin)]},
Is it to cover broader scope of cases?

2022-12-21 16:36 UTC, varsill commented on test/membrane/integration/child_spawn_test.exs
>      end
# TO BE CONTINUED

2022-12-22 13:15 UTC, FelonEkonom commented on lib/membrane/core/playback_controller.ex
> +    Action {:setup, :defer} was returned from callback #{inspect(callback)}, but setup has already been deferred
Not really, returning `setup: :defer` two times in `actions` from a single callback would also cause such a error

2022-12-22 13:27 UTC, FelonEkonom commented on lib/membrane/core/playback_controller.ex
> +        state
Don't you think, that having log like `17:59:38.137 [debug] <0.309.0>/:bin/ Child initialized` is not as good, as with `Bin initialized`? IMO version with `Child` might be confusing, because you don't know, if it is about initializing bin, that prints this log, or one of it's children

2022-12-22 13:29 UTC, FelonEkonom commented on test/membrane/core/pipeline_test.exs
> +          {:spec, [child(:a, TestBin)]},
This test case without this change fails because it does not link a static pad of `Membrane.Testing.Source`

2022-12-22 15:30 UTC, mat-hek requested changes

2022-12-22 15:30 UTC, mat-hek commented on lib/membrane/bin/action.ex
> +  By default, component setup ends with the end of `handle_setup/2` callback.
```suggestion
  By default, component setup ends with the end of `c:Membrane.Bin.handle_setup/2` callback.
```

2022-12-22 15:30 UTC, mat-hek commented on lib/membrane/core/playback_controller.ex
> +  defp assert_operation_allowed(:incomplete, :handle_setup, true) do
checking if action is returned from a valid callback should happen in the action handler

2022-12-22 15:30 UTC, mat-hek commented on lib/membrane/core/playback_controller.ex
> +defmodule Membrane.Core.PlaybackController do
Setup isn't a part of playback. I'd handle it in the lifecycle controller

2022-12-22 15:30 UTC, mat-hek commented on lib/membrane/core/playback_controller.ex
> +        state
It can be determined by the `/` at the end of the path. This applies to all logs.

2022-12-22 15:30 UTC, mat-hek commented on lib/membrane/core/pipeline/state.ex
> +                setup_incomplete_returned?: false
```suggestion
                setup_incomplete?: false
```

2022-12-23 09:18 UTC, varsill commented on lib/membrane/core/playback_controller.ex
> +    Action {:setup, :defer} was returned from callback #{inspect(callback)}, but setup has already been deferred
Ok, indeed ;)

2022-12-23 17:12 UTC, mat-hek approved these changes

2022-12-23 17:12 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +  defp assert_static_pads_linked!(children_definitions, links) do
```suggestion
  defp assert_all_static_pads_linked!(children_definitions, links) do
```

2022-12-23 17:12 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +    linked_pads_set =
```suggestion
    pads_to_link =
```

2022-12-28 11:40 UTC, varsill reviewed
General question concerning tests - why have you changed the components used in the tests so that to make them use dynamic pads? Why not to simply don't defer the setup and let all the static pads be linked during that setup?

2022-12-28 11:40 UTC, varsill commented on lib/membrane/core/element/state.ex
> +      setup_incomplete?: false
NIT - are you sure about `setup_incomplete?` name? By default it's set to `false` which might be understood that the setup is already completed :D

2022-12-28 11:40 UTC, varsill commented on lib/membrane/pipeline/action.ex
> +  is returned from antoher callback.
How about emphasizing that until the setup lasts, the `playback` won't be `:playing`?

2022-12-28 11:40 UTC, varsill commented on test/membrane/integration/child_spawn_test.exs
> +      child(:source, %Testing.Source{output: ["a", "b", "c"]}, get_if_exists: true)
How cam that test does not fail, since the source is sending `"a"`, `"b"` and `"c"` buffers, and then you are asserting on receiving buffers with payload of form `1`, `2` and `3`

2022-12-28 11:40 UTC, varsill commented on test/membrane/remote_controlled/pipeline_test.exs
> -
why have we removed returning `spec` action from the test setup?

2022-12-28 11:40 UTC, varsill commented on test/membrane/integration/defer_setup_test.exs
> +      refute_grandhild_playing(pipeline, :bin_1, bin)
```suggestion
      refute_grandchild_playing(pipeline, :bin_1, bin)
```

2022-12-28 11:40 UTC, varsill commented on test/membrane/integration/defer_setup_test.exs
> +      refute_grandhild_playing(pipeline, :bin_1, bin)
```suggestion
      refute_grandchild_playing(pipeline, :bin_1, bin)
```

2023-01-02 11:06 UTC, varsill commented on lib/membrane/bin/action.ex
> +  Untils the setup lasts, the component won't enter `:playing` playback state.
No more are we using the "playback state" term - please use "playback" :D

2023-01-02 12:48 UTC, FelonEkonom commented
> General question concerning tests - why have you changed the components used in the tests so that to make them use dynamic pads? Why not to simply don't defer the setup and let all the static pads be linked during that setup?

Because in this PR I have added checking, if spec returned from a parent links all static pads of its children

2023-01-03 12:54 UTC, varsill approved these changes

2023-01-03 16:44 UTC, merged