Write function to get child pid in tests
membraneframework/membrane_core pull request #497
Opened 2022-12-16 14:02 UTC by FelonEkonom

2022-12-16 14:08 UTC, mat-hek requested changes

2022-12-16 14:08 UTC, mat-hek commented on lib/membrane/testing/utils.ex
> +      case :sys.get_state(parent_pid) do
This is meant for debugging purposes and relies on the core internals. Instead, do a normal call to the testing pipeline and make it take the PID from the context.

2022-12-23 09:14 UTC, varsill requested changes

2022-12-23 09:14 UTC, varsill commented on lib/membrane/testing/pipeline.ex
> +  @spec get_child_pid(pid(), child_ref_path :: Child.ref_t() | [Child.ref_t()]) ::
[JUST TO CONSIDER, it might not make any sense at all :D ] That implementation of the get_child_pid/2 would work perfectly well in case we put i.e. a bin's pid as a parent_pid. Perhaps that function should be provided by the `Testing.Utilities` module, rather then by just `Testing.Pipeline`?

2022-12-23 09:14 UTC, varsill commented on lib/membrane/testing/pipeline.ex
> +  def get_child_pid(parent_pid, []), do: {:ok, parent_pid}
I am not huge fan of that clause - we are calling `get_child_pid` to get `parent`'s pid and what we receive is the `parent_pid` itself - I know that the user shouldn't call `get_child_pid(pid, [])` on his/her own, but in fact the user can do it - perhaps it would be better not to allow that by introducing private function and implementing such a `recursion break` inside that private function?

2022-12-23 09:14 UTC, varsill commented on lib/membrane/testing/pipeline.ex
> +        {:error, :pipeline_not_alive}
We are returning an error saying that `pipeline_not_alive`, but in fact it might be a bin who is not alive

2022-12-23 09:14 UTC, varsill commented on lib/membrane/testing/utils.ex
> +  Provides functions facilitating testing Membrane components.
```suggestion
  Provides functions that facilitate testing Membrane components.
```

2022-12-23 10:54 UTC, FelonEkonom commented on lib/membrane/testing/pipeline.ex
> +  @spec get_child_pid(pid(), child_ref_path :: Child.ref_t() | [Child.ref_t()]) ::
I have added this previously to `Testing.Utils` module (see there https://github.com/membraneframework/membrane_core/pull/497/files/b93b55e1086922792f4df64d1af77a149b0724a7), but I have removed it after @mat-hek suggestion, to put it in `Testing.Pipeline`

2022-12-23 10:57 UTC, FelonEkonom commented on lib/membrane/testing/pipeline.ex
> +        {:error, :pipeline_not_alive}
Yes, but if bin is not alive, probably it will not be present in its parent `state.children` map, so recursion will return it `{:error, :child_not_found}` in previous call. But still, I can change this error to sth matching this case

2022-12-23 12:24 UTC, mat-hek requested changes

2022-12-23 12:24 UTC, mat-hek commented on lib/membrane/testing/utils.ex
> +    end
use Message.call

2022-12-23 12:24 UTC, mat-hek commented on lib/membrane/testing/utils.ex
> +  def get_child_pid(parent_pid, child_ref) do
This was to be moved to `Membrane.Testing.Pipeline`

2022-12-23 13:24 UTC, mat-hek approved these changes

2022-12-23 13:24 UTC, mat-hek commented on test/membrane/testing/get_child_pid_test.exs
> +defmodule Membrane.Testing.GetChildPidTest do
now this can be moved to testing pipeline tests

2022-12-27 14:58 UTC, varsill requested changes

2022-12-27 14:58 UTC, varsill commented on lib/membrane/testing/pipeline.ex
> +  Id second argument is a path of child references, function gets pid of
```suggestion
  If second argument is a path of child references, function gets pid of
```

2022-12-27 14:58 UTC, varsill commented on lib/membrane/testing/pipeline.ex
> +  def get_child_pid(parent_pid, []), do: {:ok, parent_pid}
Ok, let's leave it that way :D

2023-01-02 11:08 UTC, varsill approved these changes

2023-01-02 12:50 UTC, merged