Demand units conversion
membraneframework/membrane_core pull request #498
Opened 2022-12-16 15:53 UTC by varsill

2022-12-20 14:38 UTC, mat-hek requested changes

2022-12-20 14:38 UTC, mat-hek commented on lib/membrane/core/child/pads_specs.ex
> +                    &1.mode == :pull and (component == :bin or direction == :input) ->
I think we don't need demand units in bin pads anymore

2022-12-20 14:38 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +        else: pad_data.demand_unit
Shouldn't we always take `pad_data.demand_unit` here?

2022-12-20 14:38 UTC, mat-hek commented on lib/membrane/core/element/input_queue.ex
> +    output_metric_buffer_size = v |> output_metric.buffers_size
```suggestion
    input_metric_buffer_size = input_metric.buffers_size(v)
    output_metric_buffer_size = output_metric.buffers_size(v)
```

2022-12-20 14:38 UTC, mat-hek commented on lib/membrane/core/element/input_queue.ex
> +           demand_size + output_metric_buf_size - input_metric.buffers_size(back)}
this became quite complex and nested

2022-12-20 17:04 UTC, varsill commented on lib/membrane/core/element/demand_handler.ex
> +        else: pad_data.demand_unit
Well, it indeed appears that we should

2022-12-20 17:05 UTC, varsill commented on lib/membrane/core/element/input_queue.ex
> +    output_metric_buffer_size = v |> output_metric.buffers_size
done

2022-12-20 17:09 UTC, varsill commented on lib/membrane/core/element/input_queue.ex
> +           demand_size + output_metric_buf_size - input_metric.buffers_size(back)}
I have slightly rewritten it so perhaps it's a little bit more clear now - but at the same time is still quite "nested"

2022-12-21 15:35 UTC, varsill commented on lib/membrane/core/child/pads_specs.ex
> +                    &1.mode == :pull and (component == :bin or direction == :input) ->
done

2022-12-22 10:05 UTC, varsill commented on test/membrane/core/element/input_queue_test.exs
> +          output_metric: Buffer.Metric.Count,
I have also improved the "elements compatibility tests" so that they check if the elements don't get overloaded

2023-01-10 15:42 UTC, mat-hek approved these changes

2023-01-10 15:42 UTC, mat-hek commented on lib/membrane/core/element/pad_controller.ex
> +        inbound_demand_unit: input_queue_demand_unit,
```suggestion
        inbound_demand_unit: other_info[:demand_unit] || this_demand_unit,
```

2023-01-10 15:42 UTC, mat-hek commented on lib/membrane/core/element/input_queue.ex
> +        {b, back} = b |> outbound_metric.split_buffers(size_to_take_in_outbound_metric)
```suggestion
        {buffers, excess_buffers} = outbound_metric.split_buffers(b, size_to_take_in_outbound_metric)
```

2023-01-10 15:42 UTC, mat-hek commented on lib/membrane/core/element/input_queue.ex
> +        b_outbound_metric_size = outbound_metric.buffers_size(b)
```suggestion
        buffers_size_inbound_metric = inbound_metric.buffers_size(b)
        buffers_size_outbound_metric = outbound_metric.buffers_size(b)
```

2023-01-11 09:57 UTC, varsill commented on lib/membrane/core/element/input_queue.ex
> +        b_outbound_metric_size = outbound_metric.buffers_size(b)
done

2023-01-11 10:01 UTC, varsill commented on lib/membrane/core/element/input_queue.ex
> +        b_outbound_metric_size = outbound_metric.buffers_size(b)
done

2023-01-11 10:08 UTC, varsill commented on lib/membrane/core/element/pad_controller.ex
> +        inbound_demand_unit: input_queue_demand_unit,
done

2023-01-11 11:04 UTC, mat-hek approved these changes

2023-01-11 11:08 UTC, varsill commented on lib/membrane/pad.ex
> +           ]}
done

2023-01-11 11:08 UTC, varsill commented on lib/membrane/pad.ex
>               | {:demand_unit, Buffer.Metric.unit_t()}
done

2023-01-11 11:14 UTC, merged