Refactor callback contexts
membraneframework/membrane_core pull request #504
Opened 2023-01-04 15:05 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-138

2023-01-10 16:58 UTC, mat-hek requested changes
AFAIR we decided to document callback-specific fields in the callbacks' docs

2023-01-10 16:58 UTC, mat-hek commented on lib/membrane/core/child/lifecycle_controller.ex
> +    # context = Component.callback_context(state)
leftover

2023-01-10 16:58 UTC, mat-hek commented on lib/membrane/core/parent/lifecycle_controller.ex
> +    # context = Component.callback_context(state)
Another leftover. Check if there are more

2023-01-10 16:58 UTC, mat-hek commented on lib/membrane/core/element/callback_context.ex
> +  @type option_t ::
- It seems that the singular form is not needed (we can leave `options_t` only)
- This should be called `optional_fields_t` or `callback_specific_fields_t`

2023-01-10 18:02 UTC, FelonEkonom commented on lib/membrane/core/element/callback_context.ex
> +  @type option_t ::
I will change a name, but singular form is used in `Membrane.Core.Component`

2023-01-11 08:24 UTC, mat-hek commented on lib/membrane/core/element/callback_context.ex
> +  @type option_t ::
Only to create the plural form again :P

2023-01-11 09:50 UTC, FelonEkonom commented on lib/membrane/core/element/callback_context.ex
> +  @type option_t ::
Yes, but otherwise we would have to duplicate every option in code and put eg. `{:incoming_demand, non_neg_integer()}` in `Membrane.Core.Element.CallbackContext` and in `Membrane.Core.Componenet` as well

2023-01-11 09:52 UTC, FelonEkonom commented on lib/membrane/core/element/callback_context.ex
> +  @type option_t ::
If you know, how to do it without repeating every key and value type in these 2 modules, let me know

2023-01-11 10:20 UTC, mat-hek commented on lib/membrane/core/element/callback_context.ex
> +  @type option_t ::
In `Membrane.Core.Component` there should be an alternative of lists instead of a list with alternative:
```
options_t :: Membrane.Core.Element.CallbackContext.options_t | Membrane.Core.Bin.CallbackContext.options_t | Membrane.Core.Pipeline.CallbackContext.options_t
```

2023-01-11 11:12 UTC, mat-hek approved these changes

2023-01-11 12:47 UTC, merged