Unify mode and demand_mode options of pads
membraneframework/membrane_core pull request #508
Opened 2023-01-12 11:09 UTC by varsill

2023-01-12 17:37 UTC, mat-hek commented on lib/membrane/pad.ex
> +  That parameter is strictly connected with the concept of a pad mode.
I would remove pad mode and not refer to it at all, or we still end up with many terms describing a single concept

2023-01-12 17:45 UTC, mat-hek requested changes

2023-01-12 17:45 UTC, mat-hek commented on lib/membrane/core/element/action_handler.ex
>                "Tried to request a demand on pad #{inspect(pad_ref)} that has demand mode set to auto"
demand mode is no more ;) there are more occurrences, search for `demand mode`

2023-01-12 17:45 UTC, mat-hek commented on lib/membrane/pad.ex
> +  whenever there's demand on all output pads (that have `demand_mode` set to `:auto`).
demand_mode -> flow_control

2023-01-12 17:45 UTC, mat-hek commented on lib/membrane/core/filter_aggregator/context.ex
> +  defp ensure_auto_demands!(%{name: name, flow_control: mode}, module)
```suggestion
  defp ensure_flow_auto!(%{name: name, flow_control: mode}, module)
```

2023-01-13 09:44 UTC, varsill commented on lib/membrane/core/filter_aggregator/context.ex
> +  defp ensure_auto_demands!(%{name: name, flow_control: mode}, module)
done

2023-01-13 09:49 UTC, varsill commented on lib/membrane/pad.ex
> +  whenever there's demand on all output pads (that have `demand_mode` set to `:auto`).
done

2023-01-13 09:50 UTC, varsill commented on lib/membrane/core/element/action_handler.ex
>                "Tried to request a demand on pad #{inspect(pad_ref)} that has demand mode set to auto"
indeed ;) done

2023-01-13 13:51 UTC, mat-hek approved these changes

2023-01-13 13:54 UTC, merged