Update processed specs, when children or link is down
membraneframework/membrane_core pull request #517
Opened 2023-01-26 17:35 UTC by FelonEkonom

Rekated Jira ticket: https://membraneframework.atlassian.net/browse/MC-148

2023-02-02 13:21 UTC, varsill requested changes

2023-02-02 13:21 UTC, varsill commented on lib/membrane/core/parent/child_life_controller/link_utils.ex
> +    state = ChildLifeController.remove_link_from_spec(link.id, state)
[SUGGESTION] I am not biggest fan of these circular dependencies :D 
We are calling `handle_child_pad_removed()` from the ChildLifeController, and inside of that function we are calling another function from `ChildLifeController`. How about putting `remove_link_from_spec()` in `LinkUtils`?

2023-02-02 14:38 UTC, FelonEkonom commented on lib/membrane/pipeline.ex
> +  Removing child's pad due to return `t:Membrane.Bin.Action.remove_link()`
No, this version is correct. Now bin can remove his own, external pad by unlinking his child with this pad

2023-02-02 14:41 UTC, FelonEkonom commented on lib/membrane/core/bin/pad_controller.ex
> +  def remove_dynamic_pad!(pad_ref, state) do
This function fails, if passed pad is static - only exception is when component is in `terminating` state. What name do you suggest?

2023-02-02 14:45 UTC, FelonEkonom commented on lib/membrane/testing/pipeline.ex
> +    do: {[], nil}
This change fixes weird, nested multiple times, custom state in Testing.Pipeline, where custom module is `nil`

2023-02-02 15:36 UTC, FelonEkonom commented on lib/membrane/core/parent/child_life_controller/link_utils.ex
> +    state = ChildLifeController.remove_link_from_spec(link.id, state)
I agree, but I would refactor this along with crash groups

2023-02-02 15:58 UTC, FelonEkonom commented on lib/membrane/core/parent/child_life_controller.ex
> +      state = Enum.reduce(existing_members, state, &LinkUtils.unlink_element/2)
I removed the line with `LinkUtils.unlink_element`, because elements are already unlinked in `crash_all_group_members/3`

2023-02-06 16:42 UTC, mat-hek requested changes

2023-02-06 16:42 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> +      {:error, :unknown_pad} ->
- handle this error in element & parent
- add a comment on when this can happen here and in similarly weird places

2023-02-06 16:42 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +  end
- don't proceed with a dependent spec even if the dependency is removed
- simplify the code by iterating through children first and making use of spec_ref in child and link data

2023-02-14 14:14 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +      |> MapSet.new(& &1.id)
instead of getting id, we could get the spec ref

2023-02-14 14:28 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +      end)
we can get links specs as stated in the comment above and children specs from children data, so that this won't be needed

2023-02-14 14:52 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +      proceed_spec_startup(spec_ref, state)
It still duplicates the code from `remove_children_from_specs`

2023-02-14 14:54 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +    dependencies |> Map.keys() |> Enum.reduce(state, &proceed_spec_startup/2)
seems these are dependent_specs again

2023-02-15 11:36 UTC, mat-hek requested changes

2023-02-15 11:36 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +  Removing child's pad due to return `t:Membrane.Bin.Action.remove_link()`
I'm not sure if this changed, but I still have a hard time understanding this. The doc for this callback in Bin is even more sophisticated since there is a 'parent' and 'child' bin involved and it's hard to determine which is which. Maybe let's focus on when this callback _is_ called and provide some example/s.

2023-02-15 11:36 UTC, mat-hek commented on lib/membrane/testing/pipeline.ex
> +      implementing this callback via `:name` option.
`name` option?

2023-02-15 16:33 UTC, mat-hek approved these changes

2023-02-15 19:50 UTC, varsill approved these changes

2023-02-16 10:59 UTC, merged