Update Membrane.Pipeline.terminate/2 behavior
membraneframework/membrane_core pull request #519
Opened 2023-01-30 13:48 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-149

2023-02-07 10:35 UTC, mat-hek requested changes

2023-02-07 10:35 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +      pipeline will be killed using `Process.exit/2` with second argument set to
```suggestion
      pipeline will be killed using `Process.exit/2` with reason
```

2023-02-07 10:35 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +      the process, that called this function.
```suggestion
      the process that called this function.
```

2023-02-07 10:35 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +    {asynchronous?, opts} = Keyword.pop(opts, :asynchronous?, false)
let's use `Keyword.validate!` to get all the options

2023-02-07 10:35 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +          raise PipelineTerminationError, """
Having a separate error for that is an overkill, let's raise `PipelineError`

2023-02-07 10:35 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +  def run_terminate(pipeline, opts) do
This should have `@doc false`. `do_terminate` would be a better name too.

2023-02-07 10:52 UTC, varsill requested changes
One more thing - I haven't seen the usage of the `force?: true` option anywhere in the tests. Perhaps we should check if it's working with that option properly

2023-02-07 10:52 UTC, varsill commented on lib/membrane/pipeline.ex
> +      pipeline is still alive after `timeout`, function will raise an error.
[SOME THOUGHTS] Hmm should it raise under these circumstances? I think it would be better if we have simply returned the `:error` tuple, and let the user raise on her/his own

2023-02-07 10:52 UTC, varsill commented on lib/membrane/pipeline.ex
> +    * `asynchronous?` - if set to `true`, pipline termination won't be blocking and
I believe the default for that option is `false` - it's worth mentioning in docs

2023-02-07 10:52 UTC, varsill commented on lib/membrane/pipeline.ex
> +  @spec terminate(pipeline :: pid, timeout: timeout(), force?: boolean()) ::
You have missed the `asynchronous?` option in the spec

2023-02-07 10:52 UTC, varsill commented on lib/membrane/pipeline.ex
> +  @spec run_terminate(pipeline :: pid, timeout: timeout(), force?: boolean()) ::
That one should be somehow made "private". I known you have made it public since you can use it both directly and with the asynchronous `Task`, but now we will have `Membrane.Pipeline.run_terminate/2` function in the API, with a defective options list ;D

2023-02-07 10:52 UTC, varsill commented on lib/membrane/rc_pipeline.ex
> +    {[terminate: :normal], state}
Oh, that's odd that that one wasn't terminating :O

2023-02-14 11:46 UTC, mat-hek approved these changes

2023-02-14 12:21 UTC, varsill approved these changes

2023-02-14 12:27 UTC, merged