Implement auto push
membraneframework/membrane_core pull request #533
Opened 2023-02-24 13:15 UTC by FelonEkonom

2023-03-09 10:11 UTC, varsill requested changes
I have one general suggestion - perhaps we could try to somehow "merge" the process of resolving effective flow control with the process of resolving demand unit? Both take place in a similar place (PadController) and require similar data

2023-03-09 10:11 UTC, varsill commented on lib/membrane/core/element/toilet.ex
> +    %__MODULE__{
Finally we have a struct for the toilet! 🥇 🥇 🥇

2023-03-09 10:11 UTC, varsill commented on test/membrane/integration/effective_flow_control_resolution_test.exs
> +    end
you are repeating the code from lines 51-60. How about adding a private function to fetch the child's effective_flow_control?

2023-03-09 10:51 UTC, FelonEkonom commented on lib/membrane/core/element/effective_flow_control_controller.ex
> +  def resolve_effective_flow_control(%State{effective_flow_control: :undefined} = state) do
Exactly

2023-03-15 16:01 UTC, FelonEkonom commented
Changes from this PR will be merged in https://github.com/membraneframework/membrane_core/pull/537

After discussion with @varsill we came to the conclusion, that it is better to not merge demand unit resolution with resolving effective flow control

2023-03-22 13:24 UTC, closed without merging