Auto push full impl
membraneframework/membrane_core pull request #537
Opened 2023-03-13 16:59 UTC by FelonEkonom

2023-04-07 13:35 UTC, varsill requested changes

2023-04-07 13:35 UTC, varsill commented on lib/membrane/core/element/demand_controller.ex
> +           DemandCounter.get(demand_counter) do
I am back :D After inspecting InputQueue I realised that `demand_counter` in fact holds the `size` of a demand (expressed in the demand unit of the proceeding element's output pad). For me it would be much clearer to use `demand_size` instead of `demand` but I am not insisting since I'm aware that sometimes I'm extravagantly keen on descriptive names. 
With such a change we could have  `pad_demand_size`, `demand_counter` and `counters_demand_size`

2023-04-07 13:35 UTC, varsill commented on lib/membrane/core/element/demand_controller.ex
> +    buffers_size = Buffer.Metric.from_unit(pad_data.other_demand_unit).buffers_size(buffers)
Are you sure we should use `other_demand_unit` here? We are working on an `output` pad and the demand unit is expressed in the metric specified by the `output` pad.

2023-04-07 13:35 UTC, varsill commented on lib/membrane/core/element/demand_counter.ex
> +    defguardp on_this_same_node_as_self(distributed_atomic)
```suggestion
    defguardp on_the_same_node_as_self(distributed_atomic)
```

2023-04-07 13:35 UTC, varsill commented on lib/membrane/core/element/demand_counter.ex
> +    def new(initial_value \\ nil) do
[GENERAL IDEA] Do we really need to start the worker in case it we are operating on the same node?

2023-04-07 13:35 UTC, varsill commented on lib/membrane/core/element/demand_counter.ex
> +    :sender_pad_ref,
These three are not in the `@type t` definition

2023-04-07 13:35 UTC, varsill commented on lib/membrane/core/element/demand_counter.ex
> +  @distributed_buffered_decrementation_limit 150
That one used to be configurable from the `pad` options - we can reconsider whether it should or shouldn't stay that way

2023-04-07 13:35 UTC, varsill commented on lib/membrane/core/element/demand_counter.ex
> +          overflow_limit :: neg_integer() | nil
[NIT] Perhaps we should be more consistent with the naming and have either `toilet_capacity` or the `overflow_limit`?

2023-04-07 13:35 UTC, varsill commented on lib/membrane/core/element/pad_controller.ex
> +        -300
I believe we should have `toilet_capacity` passed here

2023-04-07 13:35 UTC, varsill commented on lib/membrane/core/element/demand_counter.ex
`DemandCounter` consists of `DistributedFlowMode` and `DistributedAtomic`. `DistributedFlowMode` is built on top of `DistributedAtomic` and `DistributedAtomic` uses `Worker`. 
How about moving the `DistributedAtomic` to the "private" part of the `DemandCounter` (i.e. putting it in some kind of a separate namespace), along with the `Worker`, leaving the `DistributedFlowMode` the way it is and adding a `DistributedCounter` built on top of `DistributedAtomic` (on the same "level" as the `DistributedFlowMode`)? I believe that the responsibilities of the modules would be then slightly less mixed.

2023-04-11 10:21 UTC, FelonEkonom commented on lib/membrane/core/element/input_queue.ex
> +  @type queue_item() :: Buffer.t() | Event.t() | struct() | atom()
`:atom` was for `start`/`end_of_stream`, as far as I remember

2023-04-11 11:17 UTC, mat-hek reviewed
TBC

2023-04-11 11:17 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +      state.delayed_demands == MapSet.new() ->
```suggestion
      Enum.empty?(state.delayed_demands) ->
```

2023-04-11 11:17 UTC, mat-hek commented on lib/membrane/core/element/effective_flow_controller.ex
> +defmodule Membrane.Core.Element.EffectiveFlowController do
Let's add description what is effective flow control and how it changes

2023-04-11 11:17 UTC, mat-hek commented on lib/membrane/element/pad_data.ex
> +          incoming_demand: integer() | nil,
why is it here?

2023-04-11 11:17 UTC, mat-hek commented on lib/membrane/element/pad_data.ex
> +          lacking_buffers: private_field,
describe somewhere what is it about

2023-04-13 14:47 UTC, varsill requested changes

2023-04-20 14:36 UTC, FelonEkonom commented on lib/membrane/core/element/demand_counter.ex
> +    def new(initial_value \\ nil) do
No, but in such a case the worker won't do any additional operations, so there is no extra performance overhead caused by it

2023-04-20 15:39 UTC, FelonEkonom commented on lib/membrane/core/element/demand_handler.ex
> +      state.delayed_demands == MapSet.new() ->
Calling `Enum.empty?` for MapSet has linear complexity while comparing with `MapSet.new()` is performed in constant time. This is the same case as in `if length(my_list) == 0 do ...`, which would cause generating a warning with a suggestion to replace it with `if my_list == [] do ...`

2023-04-20 16:03 UTC, FelonEkonom commented on lib/membrane/core/element/effective_flow_controller.ex
> +          |> DemandCounter.set_receiver_mode(state.effective_flow_control)
Because sender sets `receiver_mode` to `:to_be_resolved`, this line is to revert this change, when we don't have to resolve our own `effective_flow_control`

2023-04-20 16:18 UTC, FelonEkonom commented on lib/membrane/core/element/effective_flow_controller.ex
> +      state.playback != :playing or pad_data.direction != :input or pad_data.flow_control != :auto ->
Because we will resolve `effective_flow_control` on `handle_playing` anyway

2023-04-21 09:26 UTC, FelonEkonom commented on lib/membrane/core/element.ex
> +      EffectiveFlowController.handle_other_effective_flow_control(
Do you have any other ideas for this function name? `handle_other_effective_flow_control_resolved` is quite long :(

2023-04-21 09:28 UTC, FelonEkonom commented on lib/membrane/core/element/demand_counter.ex
I have put every module in the separate file, inside `core/element/demand_counter` directory

2023-04-24 09:52 UTC, FelonEkonom commented on test/membrane/core/element/demand_counter_test.exs
> +  test "if buffering decrementation works properly with distribution" do
I wouldn't say that, in this test I check if buffering decrementation mechanism works properly when `sender_process` is on different node, than process that have created `DemandCounter` instance, in this case that is test process

2023-05-08 12:58 UTC, FelonEkonom commented on lib/membrane/core/element/demand_controller.ex
> +    buffers_size = Buffer.Metric.from_unit(pad_data.other_demand_unit).buffers_size(buffers)
I haven't fixed this bug yet, but I will do it before merging this PR

2023-05-09 07:53 UTC, varsill commented on lib/membrane/core/element/input_queue.ex
> +  @type queue_item() :: Buffer.t() | Event.t() | struct() | atom()
but `start`/`end_of_stream` are both implementing `Membrane.EventProtocol` and therefore they are `Event.t`

2023-05-09 10:12 UTC, mat-hek commented on lib/membrane/core/element/demand_handler.ex
> +      state.delayed_demands == MapSet.new() ->
not true https://github.com/elixir-lang/elixir/blob/cbb4fd2b3d55487b43b370bba30ed04c379a59c0/lib/elixir/lib/map_set.ex#L412

2023-05-09 16:08 UTC, mat-hek requested changes
TBC :D

2023-05-09 16:08 UTC, mat-hek commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +  @lacking_buffer_size_upperbound 400
`auto_demand_size` doesn't seem to affect these

2023-05-10 10:34 UTC, varsill reviewed
TBC

2023-05-10 10:34 UTC, varsill commented on lib/membrane/core/element/effective_flow_controller.ex
> +        Message.send(pad_data.pid, :other_effective_flow_control_resolved, [
Are you sure that one is correct? You have set the sender mode for the `output` pad (of the sender) and then sent a message to the sender that the `other_effective_flow_control_resolved` and it's not `other_effective_flow_control` that has been resolved.

2023-05-10 10:34 UTC, varsill commented on lib/membrane/core/element/effective_flow_controller.ex
> +  def handle_other_effective_flow_control(my_pad_ref, other_effective_flow_control, state) do
Do we need to stick to the `other_*` nomenclature, like with `other_effective_flow_control`? I believe `handle_other_effective_flow_control` is always called for the `my_pad_ref ` being the `input` pad. Changing `other_effective_flow_control` to `output_effective_flow_control` could help make the code more clear, as the reader wouldn't need to search the context to find out if something is an input pad or an output pad. I think there are more changes of that type that can be done after you have simplified the links resolving.

2023-05-10 13:59 UTC, mat-hek requested changes

2023-05-10 13:59 UTC, mat-hek commented on lib/membrane/core/element/effective_flow_controller.ex
> +    end
I'd rather have it in the pad controller

2023-05-10 13:59 UTC, mat-hek commented on lib/membrane/core/element/input_queue.ex
> +    lacking_buffer_size = lacking_buffer_size + diff
```suggestion
```

2023-05-10 13:59 UTC, mat-hek commented on lib/membrane/core/element/input_queue.ex
> +    %{input_queue | lacking_buffer_size: lacking_buffer_size}
```suggestion
    %{input_queue | lacking_buffer_size: lacking_buffer_size + diff}
```

2023-05-11 09:56 UTC, varsill commented on lib/membrane/core/element/effective_flow_controller.ex
> +  def handle_other_effective_flow_control(my_pad_ref, other_effective_flow_control, state) do
After discussion we have decided to postpone it for a future refactor

2023-05-11 09:57 UTC, varsill commented on lib/membrane/core/element/effective_flow_controller.ex
> +        Message.send(pad_data.pid, :other_effective_flow_control_resolved, [
Apparently `pad_data.pid` is a pid of the other side of the link - I think we should rename it to i.e. `other_pid`, but let's do it later

2023-05-12 12:11 UTC, FelonEkonom commented on lib/membrane/core/bin/pad_controller.ex
> +      if direction == :input do
This line does not change anything. I will remove field `initiator` from `params` in the another PR, because it have become redundant, since we always do `handle_link` calls in order parent -> output sibling -> input sibling

2023-05-12 12:35 UTC, FelonEkonom commented on lib/membrane/core/element/effective_flow_controller.ex
> +        Message.send(pad_data.pid, :other_effective_flow_control_resolved, [
This message is sent to the receiver, not sender

2023-05-12 13:14 UTC, FelonEkonom commented on lib/membrane/core/element/demand_counter.ex
> +  def get_sender_mode(%__MODULE__{} = demand_counter) do
it is not really flow control, because this function can also return `:to_be_resolved`

2023-05-12 13:14 UTC, FelonEkonom commented on lib/membrane/core/element/demand_counter.ex
> +  def set_receiver_mode(%__MODULE__{} = demand_counter, mode) do
as above

2023-05-17 13:32 UTC, mat-hek requested changes

2023-05-17 13:32 UTC, mat-hek commented on lib/membrane/core/element/demand_counter.ex
> +        true -> @distributed_default_throttling_factor
but do we need it?

2023-05-17 14:24 UTC, FelonEkonom commented on lib/membrane/core/element/demand_counter.ex
> +        true -> @distributed_default_throttling_factor
Or we will have `@default_throttling_factor 1`, either we will have to check on every `DemandCounter.decrease`, if the sender is on this same node as the receiver.

2023-05-17 14:49 UTC, FelonEkonom commented on lib/membrane/core/element/demand_controller.ex
> +    demand_unit = pad_data.demand_unit || pad_data.other_demand_unit || :buffers
Yes, but this alternative matters when output pad or both sides of link has `:push` flow control

2023-05-18 08:35 UTC, mat-hek commented on lib/membrane/core/element/demand_controller.ex
> +    demand_unit = pad_data.demand_unit || pad_data.other_demand_unit || :buffers
So maybe we should calculate the demand unit no matter the flow control (since the demand counter is always there)

2023-05-19 08:44 UTC, mat-hek commented on lib/membrane/core/element/demand_controller.ex
> +    demand_unit = pad_data.demand_unit || pad_data.other_demand_unit || :buffers
> IMO it does not look good to have non-nil demand_unit when flow_control is `:push`.

IMO it looks even worse to have demand_counter and not have demand_unit there 🤔 And I see no point in resolving it each time when we can do it once.

Maybe the field should be `buffer_size_unit`, not `demand_unit` :D

2023-05-19 09:41 UTC, mat-hek requested changes

2023-05-19 09:41 UTC, mat-hek commented on lib/membrane/core/element/demand_counter/distributed_atomic.ex
> +    {:ok, worker} = Worker.start_link(self())
let's start it under the supervisor

2023-05-19 09:41 UTC, mat-hek commented on lib/membrane/core/element/effective_flow_controller.ex
> +  defp set_effective_flow_control(new_effective_flow_control, last_changed_pad, state) do
```suggestion
  defp set_effective_flow_control(new_effective_flow_control, triggerer_pad, state) do
```

2023-05-19 09:41 UTC, mat-hek commented on lib/membrane/core/element/effective_flow_controller.ex
> +      {pad_ref, %{direction: :input} = pad_data}, state when last_changed_pad != nil ->
```suggestion
      {pad_ref, %{direction: :input} = pad_data}, state ->
```

2023-05-19 14:11 UTC, varsill commented on lib/membrane/core/element/effective_flow_controller.ex
>    # :pull output pad, element A will set itss effective flow control to :pull and will forward this information
```suggestion
  # :pull output pad, element A will set its effective flow control to :pull and will forward this information
```

2023-05-22 12:14 UTC, FelonEkonom commented
> 🎉

awesome

2023-05-22 12:36 UTC, varsill approved these changes
There is one small comment concerning the docs, but generally speaking:
LGTM 🥇

2023-05-22 12:36 UTC, varsill commented on lib/membrane/core/element/demand_controller.ex
> +  # Module handling changes in values of output pads demand atomics
```suggestion
  # Module handling changes in values of output pads atomic demand
```
To be fair, I believe it should be written that way, but I don't find it anyhow crucial :D

2023-05-22 13:15 UTC, merged