Improve performance test
membraneframework/membrane_core pull request #540
Opened 2023-03-20 15:01 UTC by varsill

This PR improves the formatting of the metric printouts and solves the problem with final_memory metric

2023-03-22 13:33 UTC, FelonEkonom requested changes

2023-03-22 13:33 UTC, FelonEkonom commented on .circleci/config.yml
> +      - run: git checkout -f master
why?

2023-03-22 13:33 UTC, FelonEkonom commented on benchmark/compare.exs
> +          #{inspect(Map.get(test_case_results, metric_module), pretty: true, limit: :infinity)}
What about having `master branch` and `feature branch` labels, instead of `used to be` and `now is`? To be precise, we are not comparing `feature branch` `HEAD`  with `feature branch` `HEAD~10`, but with current `master`, that does not have to be behind `feature branch` `HEAD` in commits history

2023-03-23 09:27 UTC, varsill commented on .circleci/config.yml
> +      - run: git checkout -f master
Because on this feature branch I have needed to delete a file which still exists on master (`benchmark/metrics/final_memory.ex`)

2023-03-23 10:40 UTC, mat-hek approved these changes

2023-03-27 10:34 UTC, FelonEkonom approved these changes

2023-03-27 13:31 UTC, merged