Fix bug in make_cannonical, make Child.ref a macro
membraneframework/membrane_core pull request #545
Opened 2023-04-18 16:16 UTC by FelonEkonom

Related Jira tickets:
 - https://membraneframework.atlassian.net/browse/MC-169
 - https://membraneframework.atlassian.net/browse/MC-170

2023-04-20 07:40 UTC, varsill requested changes

2023-04-20 07:40 UTC, varsill commented on lib/membrane/child.ex
> +  defp ref_in_a_match(name, group: group) do
Right now, when the user passes an improper list of options to the `Child.ref` in `match` context, an error saying that the "`ref_in_a_match` function couldn't be matched" is raised. How about adding the following function clause:
```
 defp ref_in_a_match(_name, improper_options) do
    raise "Improper options: #{inspect(improper_options)}. The options must be in form of [group: group]."
  end
```

2023-04-20 07:40 UTC, varsill commented on lib/membrane/child.ex
> +  defp ref_in_a_match(name, group: group) do
Perhaps I am running into the future to much, but I also wonder if we should allow the user to match on the whole options list, that is - to fetch the `opts` from the following match case: `Child.ref(child_name, opts) = child`.

2023-04-20 07:40 UTC, varsill commented on lib/membrane/child.ex
> +      unquote(name)
why would we want to allow for such a match: `Child.ref({Membrane.Child, _, _}) = {Membrane.Child, :group, :name}`?

2023-04-20 10:07 UTC, FelonEkonom commented on test/membrane/integration/accepted_format_test.exs
> +    assert match?({%Membrane.StreamFormatError{}, _stacktrace}, reason) or reason == :noproc
When `pid` dies before `Process.monitor`

2023-04-20 10:08 UTC, FelonEkonom commented on lib/membrane/element/base.ex
> +    - `:bring_child?` - if true (default) requires and aliases `Membrane.Child`
Element still can use it to match on it's own name

2023-04-20 10:12 UTC, FelonEkonom commented on lib/membrane/child.ex
> +      unquote(name)
I don't, but I cannot check in inside a match :shit:

2023-04-21 12:15 UTC, varsill approved these changes

2023-04-24 12:41 UTC, mat-hek commented on test/membrane/integration/accepted_format_test.exs
> +    assert match?({%Membrane.StreamFormatError{}, _stacktrace}, reason) or reason == :noproc
This approach smells, if the reason is `:noproc` then the element could have died for any reason or even never started. The appropriate way would be to monitor the process when we're sure it should be still alive or use start_link

2023-04-24 12:50 UTC, mat-hek approved these changes

2023-04-25 14:24 UTC, mat-hek approved these changes

2023-04-25 14:47 UTC, merged