Implement Debug.Filter and Debug.Sink
membraneframework/membrane_core pull request #552
Opened 2023-05-08 15:26 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-174

2023-05-09 10:05 UTC, mat-hek requested changes

2023-05-09 10:05 UTC, mat-hek commented on test/membrane/integration/simple_elements_test.exs
> +  end
Does this do anything beyond the testing source?

2023-05-10 09:52 UTC, mat-hek commented on lib/membrane/simple/filter.ex
> +              handle_event: [spec: (Event.t() -> Event.t()), default: &__MODULE__.identity/1],
BTW, you can use ` &Function.identity/1

2023-05-10 10:27 UTC, FelonEkonom commented on test/membrane/integration/simple_elements_test.exs
> +  end
This source works in `push`, while Testing Source works in `pull`

2023-05-10 11:20 UTC, mat-hek commented on test/membrane/integration/simple_elements_test.exs
> +  end
does it matter in this use case?

2023-05-10 14:09 UTC, mat-hek commented on test/membrane/integration/simple_elements_test.exs
> +  end
It wouldn't be more than you provide via the `output` option

2023-05-11 09:04 UTC, mat-hek commented on lib/membrane/lambda_filter.ex
> +defmodule Membrane.LambdaFilter do
❤️

2023-05-11 09:04 UTC, mat-hek commented on lib/membrane/lambda_filter.ex
> +                Result of this function is passed to the `:event` action on the opposite pad to
hmm, this way we cannot know whether the event is going downstream or upstream, which is pretty important

2023-05-12 12:21 UTC, mat-hek approved these changes

2023-05-12 12:21 UTC, mat-hek commented on lib/membrane/debug/filter.ex
> +      end
you can use the forward action instead

2023-05-12 12:21 UTC, mat-hek commented on lib/membrane/debug/filter.ex
> +  Membrane Filter, that can be used to create a child that will be used to debug data flowing thouth pipeline.
```suggestion
  Membrane Filter, that can be used to create a child that will be used to debug data flowing thouth pipeline.
  
```

2023-05-15 12:38 UTC, merged