Raise on try to remove not existing child
membraneframework/membrane_core pull request #553
Opened 2023-05-10 15:53 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-176

2023-05-11 09:01 UTC, mat-hek requested changes

2023-05-11 09:01 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +    |> Enum.find(&(&1 not in all_children_and_children_groups))
instead of searching through all children, we could just search in the ones that are to be removed

2023-05-12 09:28 UTC, FelonEkonom commented on lib/membrane/core/parent/child_life_controller.ex
> +    |> Enum.find(&(&1 not in all_children_and_children_groups))
value `refs` in line 522 contains only references to the children that we have to remove, while variable `children_or_children_groups` might contain not only children refs, but child groups names as well, so I am not convinced if this change will make the code simpler

2023-05-12 12:18 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +    |> Enum.find(&(&1 not in all_children_and_children_groups))
but we can easily get the groups when retrieving refs

2023-05-15 10:01 UTC, mat-hek approved these changes

2023-05-15 10:01 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +        Trying to remove child #{inspect(child_ref)}, while such a child or children group does not exist.
```suggestion
    removed_children_or_groups
    |> Enum.reject(fn name ->
      Map.has_key?(state.children, name) or MapSet.member?(children_groups, name)
    end)
    |> case do
      [] ->
        :ok

      children_refs ->
        raise Membrane.ParentError, """
        Trying to remove children #{Enum.map_join(", ", &inspect/1)}, while such children or children groups do not exist.
```

2023-05-15 13:14 UTC, merged