v0.12 upgrading guide
membraneframework/membrane_core pull request #560
Opened 2023-05-29 12:43 UTC by FelonEkonom

2023-05-29 12:53 UTC, mat-hek requested changes

2023-05-29 12:53 UTC, mat-hek commented on test/membrane/integration/auto_demands_test.exs
> +      payloads = Enum.map(1..100_000, &inspect/1)
💪

2023-05-29 12:53 UTC, mat-hek commented on guides/upgrading/v0.12.md
> +```
````suggestion
```diff
+ spec = 
+   get_child(Child.ref(:source, group: :source_group))
+   |> child(:sink, My.Sink)
+ 
+ actions = [
+   spec: spec,
+   notify_child: {Child.ref(:source, group: :source_group), :start_streaming}
+ ]
+ 
+ {actions, state}
```
````

and add the pre-0.12 version like in the other examples

2023-05-29 12:53 UTC, mat-hek commented on guides/upgrading/v0.12.md
> +
I'd merge it into the previous point

2023-05-29 12:53 UTC, mat-hek commented on guides/upgrading/v0.12.md
> +If a component is spawned inside a group, value of field `name` in it's callback context changes as well, and becames `Child.ref(child_name, group: group_name)`
add an example

2023-05-29 12:53 UTC, mat-hek commented on guides/upgrading/v0.12.md
> +```
````suggestion
```diff
- {child(:source, %My.Source{options: options}), crash_group: {:source_group, :temporary}}
```
````

and add the 0.12 version

2023-05-29 12:56 UTC, FelonEkonom commented on guides/upgrading/v0.12.md
> +```
What do you mean? This is 0.12 version

2023-05-29 12:57 UTC, FelonEkonom commented on test/membrane/integration/auto_demands_test.exs
> +      payloads = Enum.map(1..100_000, &inspect/1)
🔥 🔥 🔥

2023-05-29 15:15 UTC, mat-hek commented on guides/upgrading/v0.12.md
> +```
there's no way to have a child in handle_init's context, let's change callback to handle_info

2023-05-29 15:15 UTC, mat-hek commented on guides/upgrading/v0.12.md
> +Instead of it, there is a new action introduced in `membrane_core` v0.12, `setup: :incomplete | :complete`. If you want to defer a moment when a component enters the playing playback, you can return
Check if grammarly reports more errors

```suggestion
Instead of it, there is a new action introduced in `membrane_core` v0.12, `setup: :incomplete | :complete`. If you want to defer a moment when a component enters the playing playback, you can return `{:setup, :incomplete}` action from `handle_setup` callback. If you do that, a component will enter the playing playback only when you return `{:setup, :complete}` action from another callback, eg. `handle_info`.
```

2023-05-30 10:15 UTC, mat-hek approved these changes

2023-05-31 07:53 UTC, varsill requested changes

2023-05-31 07:53 UTC, varsill commented on .circleci/config.yml
> +            - v3-mix-deps-cache-
what for is that change?

2023-05-31 07:53 UTC, varsill commented on guides/upgrading/v0.12.md
> +Between v0.11 and v0.12 some breaking changes have occurred, so here comes the guide that will help you adjust your code to the new API. See the [changelog](https://github.com/membraneframework/membr
```suggestion
Between v0.11 and v0.12 some breaking changes have occurred, so here comes the guide that will help you adjust your code to the new API. See the [release notes](https://github.com/membraneframework/membrane_core/releases/tag/v0.12.0) for details.
```
You haven't linked changelog :D

2023-05-31 09:26 UTC, varsill approved these changes

2023-05-31 15:48 UTC, merged