Update supervisor exit reason
membraneframework/membrane_core pull request #567
Opened 2023-06-15 11:41 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-203

2023-06-15 11:44 UTC, FelonEkonom commented
This will fix https://github.com/membraneframework/membrane_core/issues/566

2023-06-22 09:44 UTC, mat-hek requested changes

2023-06-22 09:44 UTC, mat-hek commented on lib/membrane/core/process.ex
> +defmodule Membrane.Core.Process do
```suggestion
defmodule Membrane.Core.ProcessHelper do
```

2023-06-22 09:44 UTC, mat-hek commented on lib/membrane/core/process.ex
> +    # nor {:shutdown, reason}
move that to the doc of this function

2023-06-22 09:44 UTC, mat-hek commented on lib/membrane/core/process.ex
> +  def exit_self(reason, opts \\ []) do
```suggestion
  def take_french_leave(reason, opts \\ []) do
```

2023-06-22 09:44 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +        Core.Process.exit_self({:child_crash, child_name})
```suggestion
        Core.Process.exit_self({:membrane_child_crash, child_name})
```

2023-06-22 09:44 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +        Core.Process.exit_self({:child_crash, child_name})
I'd also not call exit from this function directly, but return `{:stop, reason}` and handle that in the calling module

2023-06-23 08:47 UTC, mat-hek approved these changes

2023-06-23 08:47 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +          {_result, state} ->
```suggestion
          {:not_removed, state} ->
```

2023-06-23 08:47 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller.ex
> +        state
consider returning `{:continue, state} | {:stop, reason, state}` and handling that in bin.ex/pipeline.ex

2023-06-23 09:56 UTC, merged