Dashboard
membraneframework/membrane_core pull request #571
Opened 2023-06-27 13:48 UTC by mat-hek

2023-06-28 14:16 UTC, FelonEkonom commented on lib/membrane/core/observer.ex
> +    utility_name = Map.get(opts, :utility_name)
```suggestion
    utility_name = Map.get(opts, :utility_name, "")
```

2023-06-29 10:15 UTC, varsill requested changes

2023-06-29 10:15 UTC, varsill commented on lib/membrane/core/observer.ex
> +    dt_seconds = (new_timestamp - timestamp) / 1000
That conversion to seconds here might be slightly enigmatic. Wouldn't it be better to have the `timestamps` in `Membrane.Time` units, and convert it with `Membrane.Time.*` functions?

2023-06-29 10:15 UTC, varsill commented on lib/membrane/core/observer.ex
> +    defmacro report(metric, value, opts \\ []) do
Is it intetional that in case of enabled metrics, the macros names (`report_metric` and `report_metric_update`) are different than with metrics disabled (`report` and `report_update`)?

2023-06-29 12:47 UTC, FelonEkonom requested changes

2023-06-29 12:48 UTC, FelonEkonom commented on lib/membrane/core/observer.ex
> +    )
Even if in some cases it is necessary, let's create it only when it will be used by `register_name_for_observer/1`

2023-06-30 09:27 UTC, mat-hek commented on lib/membrane/core/observer.ex
> +  @metrics_enabled Application.compile_env(:membrane_core, :enable_metrics, true)
If they're enabled by default, it's easier to use them, and we can avoid a case when someone enables them and the system starts behaving differently. There's also less chance that they stop working at some point and no one notices :P It seems we need to reduce their performance impact though

2023-06-30 09:35 UTC, mat-hek commented on lib/membrane/core/observer.ex
> +    # is on the same node as the pipeline
Then there would be no way to use metrics when any component is on a different node. It wouldn't be that hard to support multi-node metrics, we can add that to backlog :P

2023-06-30 09:36 UTC, mat-hek commented on lib/membrane/core/observer.ex
> +  @unsafely_name_processes_for_observer Application.compile_env(
yes :D

2023-06-30 09:36 UTC, mat-hek commented on lib/membrane/core/observer.ex
I don't like the name either. Any better ideas? :P

2023-06-30 09:42 UTC, mat-hek commented on lib/membrane/core/observer.ex
> +      do: Process.put(:__membrane_observer_ets__, observer.ets)
The idea is to make it simpler to report a metric from anywhere, just like you can log messages from anywhere, even if the state is not accessible, like in the InputBuffer.

2023-06-30 11:15 UTC, varsill commented on lib/membrane/core/observer.ex
> +    # is on the same node as the pipeline
Sure, I also think that it shouldn't be difficult :D 
In case you think that user might benefit from such "partial" metrics (only from components spawned on the same node as observer) we can leave it as is.

2023-06-30 11:16 UTC, varsill commented on lib/membrane/core/observer.ex
> +  @unsafely_name_processes_for_observer Application.compile_env(
I've forgotten to get back here after seeing the usage of that attribute ;) We can leave it as it is

2023-07-11 10:01 UTC, FelonEkonom requested changes

2023-07-11 10:01 UTC, FelonEkonom commented on lib/membrane/core/stalker.ex
> +    end)
Is it possible, to call `:ets.match_delete` only once, with more complex pattern?

2023-07-11 10:17 UTC, mat-hek commented on lib/membrane/core/stalker.ex
> +    setup_process_local_observability(config, %{stalker: stalker})
'stalkerity' is not really appealing to me :P

2023-07-11 10:17 UTC, mat-hek commented on lib/membrane/core/element/buffer_controller.ex
> +    :atomics.put(demand_metric, 1, demand - buf_size)
Yes, that is what this metric is supposed to measure

2023-07-11 10:19 UTC, mat-hek commented on lib/membrane/core/element/pad_controller.ex
> +      end
Initializing only fields that are needed in a particular case is quite common in our codebase IMO

2023-07-11 11:59 UTC, mat-hek commented on lib/membrane/core/stalker.ex
> +    end)
Not sure, possibly yes, but that would be way more complex and I'm not sure if it would help

2023-07-13 13:35 UTC, FelonEkonom approved these changes

2023-07-14 07:55 UTC, varsill approved these changes
I have left some two small things to consider, but generally: LGTM 🥇

2023-07-14 07:55 UTC, varsill commented on lib/membrane/core/child/pad_model.ex
> +          metrics: %{atom => :atomics.atomics_ref()}
wouldn't it be better to have `stalker_metrics` here?

2023-07-14 07:55 UTC, varsill commented on lib/membrane/core/element/input_queue.ex
> +          stalker_metrics: map()
[NIT] How about:
```suggestion
          stalker_metrics: %{atom() => any()}
```?

2023-07-14 09:23 UTC, merged