Add docs about default callback implementation
membraneframework/membrane_core pull request #572
Opened 2023-06-29 13:58 UTC by Rados13

Solves: https://membraneframework.atlassian.net/browse/MSB-63?atlOrigin=eyJpIjoiZWUwYzgzNmJhNDI1NDZiYmI0YjNmZTI1ZjYyYzQzYmEiLCJwIjoiaiJ9

2023-06-29 14:06 UTC, FelonEkonom requested changes

2023-06-29 14:06 UTC, FelonEkonom commented on lib/membrane/element/base.ex
> +  By default it create map from opts struct.
```suggestion
  By default it creates map from opts struct.
```
Here and in Bin

2023-06-29 14:06 UTC, FelonEkonom commented on lib/membrane/pipeline.ex
> +  By default it ignores received notification from child.
```suggestion
 By default, it ignores the notification received from the child.
```

2023-06-29 14:06 UTC, FelonEkonom commented on lib/membrane/pipeline.ex
> +  By default it ignores received message.
```suggestion
 By default, it ignores the received message.
```

2023-06-30 12:59 UTC, FelonEkonom approved these changes

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/bin.ex
> +  By default it ignores `:start_of_stream`.
```suggestion
  
  By default it does nothing.
```

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/bin.ex
> +  By default it ignores `:end_of_stream`.
```suggestion

  By default it does nothing.
```

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/bin.ex
> +  By default, it does nothing.
```suggestion

  By default, it does nothing.
```

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/element/base.ex
> +  By default it ignores message.
```suggestion
  By default it ignores the received message.
```

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/element/base.ex
> +  By default it ignores received message from parent.
```suggestion
  By default it ignores the received message.
```

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +  By default, it ignores the notification received from the child.
```suggestion
  Callback invoked when a notification comes in from a child.

  By default, it ignores the notification.
```

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +  By default it ignores `:start_of_stream`.
```suggestion
  
  By default it does nothing.
```

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +  By default it ignores `:end_of_stream`.
```suggestion

  By default it does nothing.
```

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +  By default, it does nothing.
```suggestion

  By default, it does nothing.
```

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/pipeline.ex
> +  By default, it creates a map from opts struct.
```suggestion
  By default, it converts the `opts` to a map if they're a struct and sets them as the pipeline state.
```

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/bin.ex
> +  By default, it creates a map from opts struct.
By default, it converts the `opts` struct to a map and sets them as the bin's state.

2023-06-30 13:17 UTC, mat-hek commented on lib/membrane/element/base.ex
> +  By default, it creates a map from opts struct.
```suggestion
  By default, it converts the `opts` struct to a map and sets them as the element's state.
```

2023-06-30 14:16 UTC, mat-hek approved these changes

2023-06-30 14:16 UTC, mat-hek commented on lib/membrane/bin.ex
> +
```suggestion
```

2023-07-03 07:58 UTC, merged