Refactor code related to crash groups and linking mechanism
membraneframework/membrane_core pull request #574
Opened 2023-06-30 13:01 UTC by FelonEkonom

Related Jira ticekt: https://membraneframework.atlassian.net/browse/MC-191

2023-07-19 11:34 UTC, mat-hek requested changes

2023-07-19 11:34 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/crash_group_utils.ex
> +        member == child_name or not Map.has_key?(state.children, member)
if a child is not in `state.children`, shouldn't it have been removed from `group.members` already?

2023-07-19 11:34 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/crash_group_utils.ex
> +  def handle_crash_group_member_death(child_name, crash_group_data, reason, state)
this has so many clauses, can we make it a bit less verbose?

2023-07-19 11:34 UTC, mat-hek commented on lib/membrane/core/element/pad_controller.ex
> +  end
These add another level of complexity, which is one level too much IMO. If you don't like passing a function to `merge_pad_data`, I'd rather remove it and rename each `init_pad_*_data` function to `merge_pad_*_data` and explicitly call `Map.merge` there.

2023-07-19 12:10 UTC, FelonEkonom commented on lib/membrane/core/parent/child_life_controller/crash_group_utils.ex
> +        member == child_name or not Map.has_key?(state.children, member)
When a child dies with a reason different than `:normal`, then it lasts in `group.members`, until the whole group dies

2023-07-26 07:46 UTC, varsill requested changes

2023-07-26 07:46 UTC, varsill commented on lib/membrane/core/element/pad_controller.ex
> +  defp do_handle_link(:input, endpoint, other_endpoint, pad_info, link_props, state) do
the same applies for the `do_handle_link(:output, ...)`

2023-07-26 07:46 UTC, varsill commented on lib/membrane/core/element/pad_controller.ex
> +          )
[NIT] I would opt for moving that part of code to some separate function, e.g. `update_associated_pads` or something like that.

2023-07-26 07:46 UTC, varsill commented on lib/membrane/core/parent/child_life_controller.ex
> +      if options.crash_group_mode != nil or Map.has_key?(state.crash_groups, options.group) do
I am not sure I get it - shouldn't it be: `if options.crash_group_mode != nil and (not Map.has_key?(state.crash_groups, options.group))`
?

2023-07-26 07:46 UTC, varsill commented on lib/membrane/core/parent/child_life_controller/crash_group_utils.ex
> +  defp trigger_crash_group(crash_initiator, %CrashGroup{} = group, state) do
I am not the biggest fan of the `trigger_crash_group` name - I would opt at least for `trigger_crash_group_crash`, but it might sound funny :D 
Perhaps you have some better alternative?

2023-07-26 07:46 UTC, varsill commented on lib/membrane/core/parent/child_life_controller/crash_group_utils.ex
> +  defp trigger_crash_group(crash_initiator, %CrashGroup{} = group, state) do
and when it comes to `triggered?` - I would rename it to `crash_triggered?` or something like that

2023-08-18 14:10 UTC, mat-hek requested changes
Looks good 👍

2023-08-18 14:10 UTC, mat-hek commented on lib/membrane/core/parent/child_life_controller/crash_group_utils.ex
> +    state = put_in(state, [:crash_groups, group.name, :members], members)
I forgot again why we remove a member if it crashed with the reason `normal` and we don't otherwise. I think it should be refactored to make it more explicit or I'd add a comment.
BTW, I'd merge this and the subsequent clause anyway

2023-08-21 14:06 UTC, FelonEkonom commented on lib/membrane/core/parent/child_life_controller/crash_group_utils.ex
> +    state = put_in(state, [:crash_groups, group.name, :members], members)
Why would you merge these two caluses? IMO operations executed in these clauses are quite different and it is cleaner to keep them separate

2023-08-21 14:52 UTC, mat-hek approved these changes

2023-08-22 12:23 UTC, varsill commented on test/membrane/core/element_test.exs
> +            # other_info: other_info,
;)

2023-08-22 12:23 UTC, varsill commented on lib/membrane/core/parent/child_life_controller/crash_group_utils.ex
> +  def extend_crash_group(group_name, _mode, children, state) do
I would remove `mode` argument here
```suggestion
  def extend_crash_group(group_name, children, state) do
```

2023-08-22 14:30 UTC, FelonEkonom commented on test/membrane/core/element_test.exs
> +                     direction: :output,
Without this fix, this test doesn't pass

2023-08-22 14:54 UTC, varsill approved these changes

2023-08-22 15:16 UTC, merged