Send end of stream, even if there was no start of stream before
membraneframework/membrane_core pull request #577
Opened 2023-07-13 15:55 UTC by FelonEkonom

2023-07-18 15:58 UTC, mat-hek requested changes

2023-07-19 09:51 UTC, FelonEkonom commented on lib/membrane/core/element/event_controller.ex
> +    do: [preceded_by_start_of_stream?: PadModel.get_data!(state, pad_ref, :start_of_stream?)]
I have extracted it to the separate private functions, because without it ` do_exec_handle_event` was a long serie of statements like 
```elixir
case event_type do
  StartOfStream ->
    this
  
  EndOfStream ->
    that
end
```

2023-07-19 11:46 UTC, mat-hek commented on lib/membrane/core/element/event_controller.ex
> +    do: [preceded_by_start_of_stream?: PadModel.get_data!(state, pad_ref, :start_of_stream?)]
But actually, when I look at it now, I'd remove `handle_special_event` and move its logic to the corresponding `do_handle_event` clauses. I'd also call `check_syncs` from `do_handle_event` clause that matches on start of stream.

2023-07-26 08:43 UTC, varsill approved these changes

2023-08-22 13:41 UTC, mat-hek requested changes

2023-08-22 13:41 UTC, mat-hek commented on lib/membrane/core/element/event_controller.ex
> +    :ok = check_sync(event, state)
this is only relevant for start of stream

2023-08-22 13:41 UTC, mat-hek commented on lib/membrane/core/element/event_controller.ex
> +      state
let's handle that in the `do_handle_event` clause for `EndOfStream`

2023-08-22 14:18 UTC, mat-hek approved these changes

2023-08-22 16:02 UTC, merged