Refactor child pad removed default error message
membraneframework/membrane_core pull request #581
Opened 2023-07-19 12:08 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-214

2023-07-19 14:08 UTC, mat-hek requested changes

2023-07-19 14:08 UTC, mat-hek commented on lib/membrane/core/parent.ex
> +    Child #{inspect(child)} removed its pad #{inspect(pad)}, but callback #{callback_ref} is not implemented in #{inspect(component_module)}.
```suggestion
    Bin #{inspect(child)} removed its pad #{inspect(pad)}, but callback #{callback_ref} is not implemented in #{inspect(component_module)}.
```

2023-07-19 14:08 UTC, mat-hek commented on lib/membrane/core/parent.ex
> +    This means, that `#{inspect(child)} is a bin, that removed its pad #{inspect(pad)} on its own, without knowledge of its parent. It
```suggestion
    This means, that `#{inspect(child)} removed the pad on its own, without knowledge of its parent. It
```

2023-07-19 14:08 UTC, mat-hek commented on lib/membrane/core/parent.ex
> +    If you want to handle e scenario when a child removes its pad in #{inspect(component_module)}, implement #{callback_ref} callback.
```suggestion
    If you want to handle this scenario, implement #{callback_ref} callback in #{inspect(component_module)}.
```

2023-07-19 14:08 UTC, mat-hek commented on lib/membrane/core/parent.ex
> +    between #{inspect(child)} and its child.
```suggestion
    may have happened because, for example, #{inspect(child)} removed its child linked to its inner pad or removed a link
    between its child and its inner pad.
```

2023-07-21 09:52 UTC, varsill approved these changes
Just consider my last suggestion ;)

2023-07-21 09:52 UTC, varsill commented on lib/membrane/exceptions.ex
> +    This means, that `#{inspect(child)} removed the pad on its own, without knowledge of its parent. For example it could happen due to removing #{inspect(child)}'s child linked to the #{inspect(chil
shouldn't we split it into two lines?

2023-07-21 11:15 UTC, merged