Implement soft corcking
membraneframework/membrane_core pull request #586
Opened 2023-07-21 14:18 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-213

2023-07-26 09:51 UTC, varsill commented on test/membrane/integration/demands_test.exs
> +    def_input_pad :input, accepted_format: _any, flow_control: :auto, availability: :always
[NIT] I think that one is default ;)
```suggestion
    def_input_pad :input, accepted_format: _any, flow_control: :auto
```

2023-07-26 09:51 UTC, varsill commented on test/membrane/integration/demands_test.exs
> +      Process.sleep(10)
let's parametrize that `10` as an module's attribute

2023-07-28 10:46 UTC, varsill requested changes

2023-07-28 10:46 UTC, varsill commented on test/membrane/integration/demands_test.exs
>        assert buff_no > 70
Do you have some kind of an idea how that value (`70`) and the other one used in assertion (`25`) is correlated with the number of buffers we expect to be sent (`100`)? Is it a linear correlation? If so, we can parametrize the `100` and use some kind of a coefficient to get the values used in assertions

2023-07-28 10:46 UTC, varsill commented on lib/membrane/core/element/action_handler.ex
> +      handle_action({:pause_auto_demand, in_ref}, cb, params, state)
I believe now you are repeating that pattern three times (`pause_auto_demand`, `pause_auto_demand` and `redemand`) - how about adding some helper function?

2023-07-28 10:46 UTC, varsill commented on lib/membrane/core/element/action_handler.ex
> +      when type in [:sink, :filter, :endpoint] and is_pad_ref(in_ref) do
[GENERAL THOUGHT] I am not sure if the user benefits from the fact that we have `is_pad_ref` guard here (and in a few other places in action handler).
Depending on whether user mistakenly passes a term that follows the pad name's pattern or not, he will either receive `Unknown pad` error, or `Unknown action` error.

2023-07-28 10:46 UTC, varsill commented on test/membrane/integration/demands_test.exs
How about adding a test with a "mixing" element (the one that has provoked use to think about that "soft corcking" solution)?
In an ideal situation I would check if there is indeed no need to buffer the incoming buffers from a pad, which sends the buffers more frequently than the other.
However, I believe that can wait for the "hard blocking" solution with that test, 
but as for now, I would at least check such a scenario: 
1) The mixer passes the buffers received on its inputs exactly the moment they are received
2) The mixer stops autodemands on one of its pads
3) The element after the mixer should stop receiving buffers from the source connected with the "corcked" pad after some time, but it should still receive the buffers from the source connected to the "uncorcked" pad

2023-07-28 10:46 UTC, varsill commented on lib/membrane/element/pad_data.ex
> +          auto_demand_stopped?: boolean(),
You need to add the description of the `auto_demand_stopped?` flag to the `PadData` moduledoc since now that field is public

2023-07-28 10:46 UTC, varsill commented on lib/membrane/element/action.ex
> +  arrive on the pad, depends on the behaviour of the elements ealier in the pipeline.
```suggestion
  arrive on the pad, depends on the behaviour of the elements earlier in the pipeline.
```

2023-07-28 10:46 UTC, varsill commented on lib/membrane/element/action.ex
> +  When auto-demanding is already paused, this action will have no effect.
```suggestion
  When auto-demanding is already paused, this action has no effect.
```

2023-07-28 10:46 UTC, varsill commented on lib/membrane/element/action.ex
> +  When auto demanding is not paused, this action will have no effect.
```suggestion
  When auto demanding is not paused, this action has no effect.
```

2023-07-28 10:46 UTC, varsill commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +  defp set_auto_demand_stopped_flag(pad_ref, new_value, state) do
[NIT] I think it will be easier to read it that way
```suggestion
  defp set_auto_demand_stopped_flag(pad_ref, stopped?, state) do
```

2023-08-23 14:24 UTC, FelonEkonom commented on test/membrane/integration/demands_test.exs
>        assert buff_no > 70
I have added comments describing why I used these numbers

2023-08-23 14:24 UTC, FelonEkonom commented on test/membrane/integration/demands_test.exs
Done

2023-08-24 14:32 UTC, varsill requested changes

2023-08-24 14:32 UTC, varsill commented on test/membrane/integration/demands_test.exs
> +        if pad_counter > pad_upperbound and not ctx.pads[pad].auto_demand_paused? do
that `pad_counter > pad_upperbound` comparison is quite tricky :D

2023-08-24 14:38 UTC, mat-hek approved these changes
Looks great!

2023-08-24 14:38 UTC, mat-hek commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +      Membrane.Logger.debug(
```suggestion
      Membrane.Logger.debug_verbose(
```

2023-08-25 09:27 UTC, FelonEkonom commented on test/membrane/integration/demands_test.exs
> +        if pad_counter > pad_upperbound and not ctx.pads[pad].auto_demand_paused? do
term `some_integer < :infinity` is always equal `true`

2023-08-25 11:14 UTC, varsill approved these changes

2023-08-25 11:14 UTC, varsill commented on test/membrane/integration/demands_test.exs
> +      end
If it's ok that the eos will be send on funnel's output right after first eos from input is received, we can leave it that way

2023-08-25 12:29 UTC, merged