Readme
membraneframework/membrane_core pull request #597
Opened 2023-09-15 09:36 UTC by mat-hek

2023-09-19 11:57 UTC, FelonEkonom requested changes

2023-09-19 11:57 UTC, FelonEkonom commented on example.livemd
> +Membrane.Pipeline.start_link(MyPipeline, mp3_url)
What about `MyPipeline.start_link(mp3_url)`?

2023-09-19 11:57 UTC, FelonEkonom commented on example.livemd
> +Membrane.Pipeline.terminate(pipeline)
Variable `pipeline` isn't set anywhere

2023-09-19 11:57 UTC, FelonEkonom commented on example.livemd
> +Membrane.Pipeline.start_link(MyPipeline, mp3_url)
And you forgot to fetch value returned from this function into a variable

2023-09-19 11:57 UTC, FelonEkonom commented on README.md
> +- do whatever you imagine if you implement it yourself :D Membrane makes it easy to plug in your code at almost any point of processing.
Remove `,` and `.` from the ends of the lines

2023-09-19 11:57 UTC, FelonEkonom commented on README.md
> +Want a generic media server, instead of building a custom one? Try [Jellyfish](https://github.com/jellyfish-dev/jellyfish) - it's built on top of Membrane and provides many of its features via simple
🤯

2023-09-19 11:57 UTC, FelonEkonom commented on README.md
> +  - On Debian: `apt install libmad0-dev portaudio19-dev`
I guess, that since introducing precompiled dependencies in `Bundlex`, it won't be needed - as far as I know, it should be merged soon

2023-09-19 11:57 UTC, FelonEkonom commented on README.md
> +The best place to learn Membrane is the [membrane.stream/learn](https://membrane.stream/learn) website and the [membrane_demo](https://github.com/membraneframework/membrane_demo) repository. Try them
Don't we want to have guide/tutorials here?

2023-09-19 11:57 UTC, FelonEkonom commented on README.md
> +Plugins provide elements that you can use in your pipeline. Each plugin lives in a `membrane_X_plugin` repository, where X can be a protocol, codec, container or functionality, for example [mebrane_o
WDYT about changing `Element` on `Component` here? I understand, that introducing concept of `bin` might make this section unnecessary complicated, but using word `Component` instead of `Element` won't cause that

2023-09-19 11:57 UTC, FelonEkonom commented on README.md
> +{:membrane_core, "~> 0.12.0"}
```suggestion
{:membrane_core, "~> 0.12.9"}
```

2023-09-19 11:57 UTC, FelonEkonom commented on README.md
> +- Contribute code - plugins, features and bug fixes. It's best to contact us before, so we can provide our help & assistance, and agree on important matters. For details see the [contribution guide](
Add dot at the end of the last line or remove it from the end of the line with `Create learning materials ...`

2023-09-19 12:39 UTC, mat-hek commented on update_packages_list.exs
> +      "https://api.github.com/orgs/#{org}/repos?per_page=100",
That's the maximum that github allows :/ if we want more, we need to paginate, I'll see how hard is it

2023-09-19 12:43 UTC, mat-hek commented on update_packages_list.exs
> +  |> Enum.filter(&(&1.owner.login == "membraneframework"))
This is the organisation, it can be membraneframework-labs, jellyfish-dev or some third party. This is needed to print a warn whenever a repo from membraneframework is not in the list

2023-09-19 12:46 UTC, mat-hek commented on example.livemd
> +Membrane.Pipeline.start_link(MyPipeline, mp3_url)
I'm considering not generating the start_link from 1.0. We can discuss it after the standup

2023-09-19 12:47 UTC, mat-hek commented on example.livemd
> +Membrane.Pipeline.terminate(pipeline)
done

2023-09-19 12:48 UTC, mat-hek commented on README.md
> +- do whatever you imagine if you implement it yourself :D Membrane makes it easy to plug in your code at almost any point of processing.
I believe this is grammatically correct 🤔 Alternatively, we could start each bullet with a capital letter and end it with a dot.

2023-09-19 12:48 UTC, mat-hek commented on README.md
> +Want a generic media server, instead of building a custom one? Try [Jellyfish](https://github.com/jellyfish-dev/jellyfish) - it's built on top of Membrane and provides many of its features via simple
😱

2023-09-19 12:49 UTC, mat-hek commented on README.md
> +The best place to learn Membrane is the [membrane.stream/learn](https://membrane.stream/learn) website and the [membrane_demo](https://github.com/membraneframework/membrane_demo) repository. Try them
Guide is being moved to tutorials, and tutorials are deployed to membrane.stream/learn

2023-09-20 08:59 UTC, mat-hek commented on README.md
> +Plugins provide elements that you can use in your pipeline. Each plugin lives in a `membrane_X_plugin` repository, where X can be a protocol, codec, container or functionality, for example [mebrane_o
I thought about it, but it would require explaining what are components

2023-09-22 14:11 UTC, mat-hek commented on README.md
> +### []() Learn more at [rtcon.live](https://rtcon.live)
Yes, github sometimes behaves weirdly if there's a link in a header. Adding an empty link at the beginning seems to fix it.

2023-09-25 11:38 UTC, FelonEkonom approved these changes

2023-09-26 09:48 UTC, FelonEkonom commented on .github/workflows/update-packages-list.yml
> +          git checkout -b auto-update-packages-list
This line will fail, if branch `auto-update-packages-list` already exists

2023-09-26 09:48 UTC, FelonEkonom commented on .github/workflows/update-packages-list.yml
> +          git commit -m"auto update packages list in readme" --allow-empty
```suggestion
          git commit -m "auto update packages list in readme" --allow-empty
```

2023-09-26 09:48 UTC, FelonEkonom commented on update_packages_list.exs
> +|> then(&File.write(readme_path, &1))
```suggestion
|> then(&File.write!(readme_path, &1))
```

2023-09-26 11:48 UTC, FelonEkonom approved these changes

2023-09-26 14:21 UTC, merged