defimpl Inspect for components states
membraneframework/membrane_core pull request #614
Opened 2023-09-29 13:33 UTC by FelonEkonom

Related Jira ticket: https://membraneframework.atlassian.net/browse/MC-240

2023-10-02 12:17 UTC, mat-hek requested changes

2023-10-02 12:17 UTC, mat-hek commented on lib/membrane/core/inspect.ex
> +    :pads_to_snapshot
```suggestion
    :children,
    :links,
    :crash_groups,
    :pending_specs,
    :synchronization,
    :delayed_demands,
    :effective_flow_control,
    :initialized?,
    :terminating?,
    :setup_incomplete?,
    :supplying_demand?,
    :handling_action?,
    :stalker,
    :resource_guard,
    :subprocess_supervisor,
    :children_log_metadata,
    :handle_demand_loop_counter,
    :demand_size,
    :pads_to_snapshot,
    :playback_queue,
    :pads_data
```

2023-10-02 12:17 UTC, mat-hek commented on lib/membrane/core/inspect.ex
> +    |> Enum.filter(&(&1 not in @fields_order))
```suggestion
    |> Enum.reject(&(&1 in @fields_order))
```

2023-10-02 12:17 UTC, mat-hek commented on lib/membrane/core/inspect.ex
> +        Fields #{inspect(fields)} from #{inspect(state_module)} structure are omitted in @fields_order module attribute in #{inspect(__MODULE__)}. Add them to @fields_order, to define where they will
```suggestion
        Fields #{inspect(fields)} from #{inspect(state_module)} structure are omitted in @fields_order module attribute in #{inspect(__MODULE__)}.\
        Add them to @fields_order, to define where they will occur in the error logs.
```

2023-10-02 14:49 UTC, FelonEkonom commented on lib/membrane/core/inspect.ex
> +    :pads_to_snapshot
Are you sure we want to have `pads_data` at the end, even after things like `delayed_demands` or `handle_demand_loop_counter`?

2023-10-04 10:08 UTC, mat-hek requested changes
As we spoke, let's use the order of fields as specified in each state module

2023-10-04 13:33 UTC, mat-hek approved these changes

2023-10-04 13:46 UTC, merged