Queue buffers when auto demand is low enough
membraneframework/membrane_core pull request #693
Opened 2023-12-15 16:22 UTC by FelonEkonom

Closes https://github.com/membraneframework/membrane_core/issues/642

2023-12-26 14:50 UTC, itamm15 commented on lib/membrane/core/element/buffer_controller.ex
> +        raise "to nie powinno sie zdarzyc dupa 2"
Love it #dupa

2023-12-26 21:16 UTC, FelonEkonom commented on lib/membrane/core/element/buffer_controller.ex
> +        raise "to nie powinno sie zdarzyc dupa 2"
🇵🇱 🇵🇱 🇵🇱 This is still a draft for a reason 🇵🇱 🇵🇱 🇵🇱

2024-01-05 16:08 UTC, itamm15 commented on lib/membrane/core/element/buffer_controller.ex
> +        raise "to nie powinno sie zdarzyc dupa 2"
@FelonEkonom out of curiosity - may I participate in the code review process? 😄

2024-01-05 16:31 UTC, FelonEkonom commented on lib/membrane/core/element/buffer_controller.ex
> +        raise "to nie powinno sie zdarzyc dupa 2"
Yes. I will mark this PR as `Ready for review`, when I fix bugs causing tests to fail

2024-01-16 21:05 UTC, itamm15 reviewed
Have done some part of CR, and will be back for the next part soon 😬

2024-01-16 21:05 UTC, itamm15 commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +    do: MapSet.size(pads) == 0
Pattern match is faster than looping over whole map 

```suggestion
  defp output_auto_demand_positive?(%State{satisfied_auto_output_pads: %{}}), do: true
  defp output_auto_demand_positive?(_state), do: false
```

2024-01-16 21:05 UTC, itamm15 commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
>    }
Q: Are you sure you want to use `{}` in the alias? It will be hard for grepping specific context (definitely such as `State`)

2024-01-31 15:18 UTC, mat-hek requested changes

2024-01-31 15:18 UTC, mat-hek commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +  # def onUncorck() do
Is it called `pop_queues_and_bump_demand` in the real code?

2024-01-31 18:03 UTC, FelonEkonom commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +  # def onUncorck() do
It is quite close, but to be precise, it works like:
```
def pop_queues_and_bump_demand() do
  if uncorcked do
    onUncorck()
  end
end
```

2024-02-09 11:54 UTC, FelonEkonom commented on lib/membrane/core/element/buffer_controller.ex
> +      end
I tested this idea and it looks like it makes things even worse

2024-02-09 11:55 UTC, FelonEkonom commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +    pad_ref = Enum.random(state.awaiting_auto_input_pads)
Do you mean to do everything in the same way as it is, but just call `Enum.random` less frequently?

2024-02-09 11:58 UTC, FelonEkonom commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +    |> PadModel.get_data!(pad_ref, :auto_flow_queue)
I can test if it changes anything, but remember, that performance worsening happens even if we don't put anything into `auto flow queue`.

2024-02-09 11:58 UTC, FelonEkonom commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +  #   - sending an EOS to the auto output pad
I'll do it

2024-02-09 13:28 UTC, FelonEkonom commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +  #   - sending an EOS to the auto output pad
yes, because on transition from `corcked` to  `uncorcked` nothing special happens, until buffer arrival - then an element processes it immediately, omitting `auto_flow_queue`

2024-02-09 13:31 UTC, FelonEkonom commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +    pad_ref = Enum.random(state.awaiting_auto_input_pads)
It is problematic, how to handle satisfying the demand on one of the output pads, while being in the middle of the batch of popped buffers

2024-02-16 12:52 UTC, mat-hek commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +  #   - sending an EOS to the auto output pad
I'd mention it anyway

2024-02-16 12:53 UTC, mat-hek commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +    pad_ref = Enum.random(state.awaiting_auto_input_pads)
Yes

2024-02-16 12:58 UTC, mat-hek commented on lib/membrane/core/element/demand_controller/auto_flow_utils.ex
> +  # def onUncorck() do
So I'd adjust it to reflect the names from the code, it would be easier to follow

2024-02-16 15:20 UTC, mat-hek commented on lib/membrane/core/element/action_handler.ex
> +      end)
why this?

2024-02-16 15:20 UTC, mat-hek commented on lib/membrane/core/element/event_controller.ex
> +
here we can potentially store async events in the queue

2024-02-22 11:53 UTC, FelonEkonom commented on lib/membrane/core/element/action_handler.ex
> +      end)
It is faster

2024-02-22 11:55 UTC, FelonEkonom commented on lib/membrane/core/element/event_controller.ex
> +
Do you mean the first case of `cond` statement? The same condition as there is currently on `master`, I haven't changed it

2024-02-23 15:31 UTC, mat-hek commented on lib/membrane/core/element/event_controller.ex
> +
On master there's an `if`, not `cond` https://github.com/membraneframework/membrane_core/blob/475c22c045c050721cd3ffa19ebd7e73e5eff19a/lib/membrane/core/element/event_controller.ex#L42

2024-02-23 15:41 UTC, FelonEkonom commented on lib/membrane/core/element/event_controller.ex
> +
Yeah, I just transformed `if` into `cond`, the logic of the code is the same

2024-02-23 16:39 UTC, FelonEkonom commented on lib/membrane/core/element/event_controller.ex
> +
1st condition in `cond` is `true` `<=>` condition in `if` is satisfied

2024-02-26 13:43 UTC, mat-hek approved these changes

2024-02-26 14:47 UTC, merged