Add crash reason handle crash group
membraneframework/membrane_core pull request #720
Opened 2024-01-26 14:34 UTC by DominikWolek

2024-01-26 14:48 UTC, FelonEkonom requested changes

2024-01-26 14:52 UTC, FelonEkonom requested changes

2024-01-26 14:52 UTC, FelonEkonom commented on lib/membrane/core/bin/callback_context.ex
>            | [members: [Membrane.Child.name()], crash_initiator: Membrane.Child.name()]
```suggestion
          | [members: [Membrane.Child.name()], crash_initiator: Membrane.Child.name(), reason: any()]
```

2024-01-26 14:52 UTC, FelonEkonom commented on lib/membrane/core/bin/callback_context.ex
> +          | [reason: any()]
```suggestion
```

2024-01-26 14:52 UTC, FelonEkonom commented on lib/membrane/core/bin/callback_context.ex
> +          | [reason: any()]
Fix this in the pipeline module as well

2024-02-02 08:39 UTC, mat-hek requested changes

2024-02-02 08:39 UTC, mat-hek commented on lib/membrane/bin/callback_context.ex
> +          optional(:reason) => any(),
- let's call it `crash_reason`, so it's less ambiguous
- the type could be  `:normal | :shutdown | {:shutdown, term()} | term()` to be more descriptive, like [here](https://hexdocs.pm/elixir/GenServer.html#c:terminate/2)

2024-02-02 10:56 UTC, FelonEkonom requested changes

2024-02-02 10:56 UTC, FelonEkonom commented on test/support/child_crash_test/pipeline.ex
> +    send(pid, {:inform_about_crash, send_to})
```suggestion
    send(pipeline, {:inform_about_crash, self()})
```

The only value, that is passed as `send_to`, is `self()`

2024-02-02 10:56 UTC, FelonEkonom commented on test/membrane/integration/child_crash_test.exs
> +    assert_receive({:crash, reason: :crash})
```suggestion
pipeline = Testing.Pipeline.start_supervised!(module: ChildCrashTest.Pipeline)
ChildCrashTest.Pipeline.add_path(pipeline_pid, [], :source, 1, :group_1)

# time for pipeline to start :source
Process.sleep(100)

ChildCrashTest.Pipeline.inform_about_details_in_case_of_crash(pipeline)

Testing.Pipeline.get_child_pid!(pipeline, :source)
|> Process.exit(:custom_crash_reason)

assert_receive {:crash, reason: :custom_crash_reason} 

Testing.Pipeline.terminate(pipeline)
```

1) `Process.flag(:trap_exit, true)` is unnecessary, we can just omit linking with pipeline and source.
2) It is necessary to terminate the pipeline at the end of the test

2024-02-02 10:56 UTC, FelonEkonom commented on test/membrane/integration/child_crash_test.exs
> +  test "Pipeline receive correct crash reason" do
```suggestion
  test "Pipeline receives correct crash reason" do
```

2024-02-07 14:01 UTC, FelonEkonom approved these changes

2024-02-07 14:01 UTC, FelonEkonom commented on lib/membrane/core/parent/crash_group.ex
> +              [members: [], detonating?: false, crash_initiator: nil, reason: nil]
```suggestion
              [members: [], detonating?: false, crash_initiator: nil, crash_reason: nil]
```
Unify name of the field in `%CrashGroup{}` struct with name of the field passed in context to `handle_crash_group_down`

2024-02-09 11:08 UTC, mat-hek approved these changes

2024-02-13 13:50 UTC, merged