Refactor demand mechanism
membraneframework/membrane_core pull request #783
Opened 2024-03-26 12:54 UTC by FelonEkonom

2024-04-02 14:12 UTC, mat-hek requested changes

2024-04-02 14:12 UTC, mat-hek commented on lib/membrane/core/element/demand_controller.ex
> +        raise("cannot snapshot atomic counter in input pad")
add pad ref

2024-04-03 09:49 UTC, mat-hek commented
@FelonEkonom BTW I recall you wanted to refactor `InputQueue` as well

2024-04-03 09:51 UTC, mat-hek approved these changes

2024-04-03 09:51 UTC, mat-hek commented on lib/membrane/core/element/demand_controller.ex
> +        raise("cannot snapshot atomic counter in input pad #{inspect(pad_ref)}")
```suggestion
        raise Membrane.ElementError, "Cannot snapshot atomic counter in input pad #{inspect(pad_ref)}"
```

2024-04-03 09:51 UTC, mat-hek commented
@FelonEkonom BTW I recall you wanted to refactor `InputQueue` as well

2024-04-03 13:41 UTC, FelonEkonom commented
@mat-hek I know, but then I decided that I would rather focus more on the code related to `DemandHandler`, because it was more messy and some changes, that I wanted to make in `InputQueue` (like deleting from it `AtomicDemand`) turned to be not a good ideas

2024-04-03 13:41 UTC, merged