Modify 5s linking timeout constraint
membraneframework/membrane_core pull request #810
Opened 2024-05-23 14:18 UTC by FelonEkonom

Solves https://github.com/membraneframework/membrane_core/issues/786

2024-05-27 14:16 UTC, mat-hek requested changes

2024-05-27 14:16 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> +        Map.update!(state, :linking_timeout_counters, &Map.delete(&1, pad_ref))
Remember we talked about something similar, but couldn't we store the reference to the timer in `pad_data` and compare it when the timeout arrives?

2024-05-27 14:16 UTC, mat-hek commented on test/membrane/integration/linking_test.exs
> +  @tag :xd
xd

2024-05-28 08:34 UTC, FelonEkonom commented on lib/membrane/core/bin/pad_controller.ex
> +        Map.update!(state, :linking_timeout_counters, &Map.delete(&1, pad_ref))
It is not a good idea, this approach generates some weird race conditions and it's implementation would be far more complex. I don't se any pros of it, only cons

2024-05-28 08:36 UTC, FelonEkonom commented on lib/membrane/core/bin/pad_controller.ex
> +        Map.update!(state, :linking_timeout_counters, &Map.delete(&1, pad_ref))
Conclusion from out last talk was that we don't want to do this

2024-05-29 14:41 UTC, mat-hek requested changes
As we spoke, the best approach would be to create the pad data earlier and store the timer reference there

2024-06-03 11:01 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> -          |> Map.update!(:pad_refs, &[pad_ref | &1])
Why remove `pad_refs`? In case you forgot, it was added by yourself in this PR: https://github.com/membraneframework/membrane_core/pull/641 :P

2024-06-03 12:28 UTC, FelonEkonom commented on lib/membrane/core/bin/pad_controller.ex
> -          |> Map.update!(:pad_refs, &[pad_ref | &1])
Ok, I didn't remember it 🙈 There was 1 place, where the pad was removed from `pads_data` but not from `pad_refs`, so without this PR value stored under this field may be incorrect and I saw that nothing relies on the value of this field. I guess that the reason of this field was to have more readable logs, but has anybody ever used it in this purpose?

2024-06-03 12:41 UTC, mat-hek commented on lib/membrane/core/bin/pad_controller.ex
> -          |> Map.update!(:pad_refs, &[pad_ref | &1])
I didn't, but hard to say in general. I have the following idea:
- call it `inspect_pad_refs` and assign to it a function that will accept the state and return the pad refs
- in `Membrane.Core.Inspect`, if a field starts with `inspect_`, we'll call the function in it instead of printing it directly

I don't like it much, but should be better than what we have. Otherwise I'd just remove this field, but it should be removed from the element as well

2024-06-03 13:05 UTC, FelonEkonom commented on lib/membrane/core/bin/pad_controller.ex
> -          |> Map.update!(:pad_refs, &[pad_ref | &1])
there is no such a field in the element state

2024-06-03 13:10 UTC, mat-hek approved these changes

2024-06-03 13:13 UTC, merged