Ensure error logs are always printed
membraneframework/membrane_core pull request #822
Opened 2024-06-10 14:49 UTC by FelonEkonom

2024-06-10 14:59 UTC, mat-hek approved these changes

2024-06-10 14:59 UTC, mat-hek commented on lib/membrane/core/macros.ex
> +defmodule Membrane.Core.Macros do
```suggestion
defmodule Membrane.Core.Utils do
```

2024-06-10 14:59 UTC, varsill requested changes
How about adding it to other GenServers that we define in Core as well (like ResourceGuard etc.?)

2024-06-10 14:59 UTC, varsill commented on lib/membrane/core/element.ex
> +    end
why `Telemetry.report_metric` is outside of the `Macros.log_on_error`?

2024-06-10 14:59 UTC, varsill commented on lib/membrane/core/macros.ex
> +  # we add this macro, to ensure that error logs wil be always logged
```suggestion
  # we add this macro, to ensure that error logs are always printed
```

2024-06-11 13:48 UTC, varsill approved these changes
Initially I just thought of adding it only in other processes that can execute users code (just like `ResourceGuard`, which executes registered user's lambda), but since you have added logging to all GenServers it's even better, as it will be easier for us to debug if we made some mistakes :D

2024-06-11 15:00 UTC, merged