Add max_cardinality option for dynamic pads
membraneframework/membrane_core pull request #876
Opened 2024-09-27 11:52 UTC by FelonEkonom

2024-09-30 12:45 UTC, mat-hek reviewed
Let's add it to the docs generation too https://github.com/membraneframework/membrane_core/blob/a9b052d10f9014612bb163fad3f81d3c7e84268a/lib/membrane/core/child/pads_specs.ex#L274

2024-09-30 12:45 UTC, mat-hek commented on lib/membrane/bin/pad_data.ex
> +          max_cardinality: Membrane.Pad.max_cardinality() | nil,
What about `max_instances`? :P

2024-09-30 12:48 UTC, mat-hek commented on lib/membrane/pad.ex
> +  can occur within single component.
```suggestion
  can occur simultaneously within a single component.
```

2024-10-01 09:07 UTC, varsill requested changes

2024-10-01 09:07 UTC, varsill commented on lib/membrane/pad.ex
> +           max_cardinality: max_cardinality()}
It's probably not the scope of this PR, but is this `element_spec` a proper typespec? I think that it doesn't highlight the fact that some of these fields are mandatory, while the others are optional

2024-10-01 09:07 UTC, varsill commented on lib/membrane/pad.ex
> +           max_cardinality: max_cardinality()}
BTW. - Perhaps it would be good to write somewhere that `max_cardinality` defaults to `:infinity` for dynamic pads? I don't think there is a way to tell that without checking the code.

2024-10-24 10:47 UTC, mat-hek approved these changes

2024-10-29 10:37 UTC, merged