Detect diamonds
membraneframework/membrane_core pull request #909
Opened 2024-11-21 10:42 UTC by FelonEkonom

Closes #873

2024-11-28 12:54 UTC, mat-hek requested changes

2024-11-28 12:54 UTC, mat-hek commented on lib/membrane/core/element/diamond_detection_controller.ex
> +    # always has more than 64 bytes, so it won't be copied during sending a message
I'm not convinced it's worth the hassle. Did you do any benchmarks? BTW, it seems we construct this 'serialized' component path every time we need it - I'd do that once and keep it in state.

2024-11-28 12:54 UTC, mat-hek commented on lib/membrane/core/element/diamond_detection_controller.ex
> +
Let's describe how the algorithm works

2024-11-28 12:54 UTC, mat-hek commented on lib/membrane/core/element.ex
> +  end
These messages seem quite internal to the diamond detection. I'd make them a single message and dispatch within DiamondDetectionController

2024-11-28 12:54 UTC, mat-hek commented on lib/membrane/core/element/state.ex
> +          diamond_detection_postponed?: boolean()
let's put these into a single `diamond_detection` map/struct

2024-12-10 14:19 UTC, mat-hek commented on lib/membrane/core/element/diamond_detection_controller.ex
> +  #   * if the new spec caused some new diamond to occur, this diamond will contain some of
```suggestion
  #   * if the new spec created a new diamond, this diamond will contain some of
```

2024-12-10 14:19 UTC, mat-hek commented on lib/membrane/core/element/diamond_detection_controller.ex
> +  # The algorithm is made of two phases: (1) triggering and (2) proper searching.
why _proper_ searching? :P

2024-12-10 14:19 UTC, mat-hek commented on lib/membrane/core/element/diamond_detection_controller.ex
> +            | :delete_trigger_ref,
I'm not a fan of these names :P there's `start`, `start_trigger` and `trigger`, hard to tell the difference. `diamond_detection` is pretty generic. They should at least correspond to the terms used in the algorithm description (proper search?), ideally be mentioned there

2024-12-10 14:19 UTC, mat-hek commented on lib/membrane/core/element/diamond_detection_controller.ex
> +    # always has more than 64 bytes, so it won't be copied during sending a message
I see it's now constructed once, but I'm still unconvinced about prepending the prefix. Handling ref-counted binaries strains GC, and copying may be more efficient if the binary is small, so I wouldn't force either way, at least without benchmarks.

2024-12-10 14:19 UTC, mat-hek commented on lib/membrane/core/element/state.ex
> +              postponed?: false
NIT: You can move the type and initialization to the DiamondDetection module

2024-12-12 18:53 UTC, FelonEkonom commented on lib/membrane/core/element/diamond_detection_controller.ex
> +  # The algorithm is made of two phases: (1) triggering and (2) proper searching.
It is supposed to be a translation of "właściwe szukanie"

2024-12-13 09:10 UTC, mat-hek commented on lib/membrane/core/element/diamond_detection_controller.ex
> +  # The algorithm is made of two phases: (1) triggering and (2) proper searching.
Got it, 'proper' is more like 'correct'. The best term I know would be 'actual search', though I'd just go for 'search', since the whole process is called 'detection', not 'search', so there's no other 'search' unless I'm missing something ;)

2024-12-19 11:10 UTC, mat-hek commented on lib/membrane/core/element/diamond_detection_controller.ex
> +  # triggerall elements whose output pads have been linked in this spec (`type: :start_trigger`).
```suggestion
  # trigger all elements whose output pads have been linked in this spec (`type: :start_trigger`).
```

2024-12-19 11:10 UTC, mat-hek commented on lib/membrane/core/element/diamond_detection_controller.ex
> +  # (2) Proper searching:
Seems like 'proper' is still there, can we make it just 'searching'?

2024-12-23 13:53 UTC, mat-hek approved these changes
Remember to create an issue for warning only when the pipeline stucks

2024-12-23 15:49 UTC, merged