Telemetry (#905)
membraneframework/membrane_core pull request #918
Opened 2024-12-06 11:19 UTC by wende

Relates to #905

2024-12-30 12:43 UTC, FelonEkonom commented on lib/membrane/core/bin.ex
> +      end
Since we will have an appropriate span for `handle_init` in `CallbackHandler`, there is no need for span for `:init` here

2024-12-30 12:44 UTC, FelonEkonom commented
I took a brief look at your changes and I commented things that caught my attention

2025-01-10 13:12 UTC, wende commented
@FelonEkonom, could you provide an example of how the .config.exs file should look for the end user? This would help me a lot with separation of concerns.
```
config :membrane_core, :telemetry_flags,
    handlers: [
      element: [
        :init,
        :setup,
        :terminate_request,
        :playing,
        :parent_notification
      ],
      bin: :all,
      pipeline: :all
    ],
    metrics: :all
 ```
 Is this example requiring excessive detail from the end user? Or would you consider it an adequate level of granularity?

2025-01-10 15:06 UTC, FelonEkonom commented
It could look like 
```

config :membrane_core, :telemetry_flags,
    tracked_callbacks: [
      element: [
        :handle_init,
        :handle_playing,
        :handle_demand
      ],
      bin: :all,
      pipeline: :all
    ],
    metrics: :all
```
or simply
```
config :membrane_core, :telemetry_flags,
    tracked_callbacks: :all,
    metrics: :all
```

@varsill @mat-hek @Noarkhh WDYT guys?

2025-01-16 10:27 UTC, wende commented on lib/membrane/core/telemetry.ex
> +  end
It might be a little bit over-engineered, but it gives the performance benefit of head-matching instead of a run-time lookup.

2025-01-16 10:31 UTC, wende commented on lib/membrane/core/telemetry.ex
> +              raise "Unexpected telemetry span result. Use Telemetry.state_result/3 instead"
A bit more lenient solution would be to issue a warning that telemetry won't be reported and return whatever the end-user returned themselves. 
Use your best judgment which one you prefer

2025-01-16 10:35 UTC, wende commented on lib/membrane/core/telemetry.ex
> +      measurement
This one is currently unused. There used to be some metrics measured by legacy code of this purpose, but since it wasn't tested anywhere I treated it as dead code and removed it
A list of metrics that you want to measure would be appreciated.

2025-01-16 10:39 UTC, wende commented on lib/membrane/telemetry.ex
This list is outdated as of this PR since it wasn't in any way tested. Let me know if these are really the metrics you'd like to have measured; as well as any additional ones if applicable

2025-01-16 10:57 UTC, wende commented
This is an MVP version of this PR. I'm going to need a list of desirable metrics to be measured, as well as some guidance on how to document `Membrane.Telemetry` and `Membrane.Core.Telemetry` in relation to each other

2025-01-17 16:52 UTC, FelonEkonom requested changes
I haven't finished my review, but I am publishing some of the comments that I've made.

Further review soon 🔜

2025-01-17 16:52 UTC, FelonEkonom commented on lib/membrane/core/telemetry.ex
> +    Map.take(state, @public_state_keys[struct])
It can't be done this way, I believe it would affect the performance too much. 
Let's create a type being part of a public API that will contain some fields from the private state that we want to make public, e.g.

```elixir 
@type pipeline_metadata :: %{
          module: module,
          playback: Membrane.Playback.t(),
          internal_state: Membrane.Pipeline.state() | nil,
          children: ChildrenModel.children(),
          links: %{Link.id() => Link.t()},
          crash_groups: %{CrashGroup.name() => CrashGroup.t()},
          initialized?: boolean(),
          terminating?: boolean(),
          resource_guard: Membrane.ResourceGuard.t(),
          setup_incomplete?: boolean(),
          subprocess_supervisor: pid(),
          optional(any()) => any()
}
```

We will declare that we pass `pipeline_metadata` (you can rename it to sth different) to the `:telemetry` event, but in fact we will pass there `Membrane.Pipeline.Core.State.t()`. It can be done this way because `Membrane.Pipeline.Core.State.t()` always matches type `pipeline_metadata`.

To be more certain, what is the impact of a specific PR on the performance of the framework, we have a job on the CI called `test_performance`, that needs to be manually triggered on CIrcleCI website to be run. I have triggered it, but it looks that it has some problems, that I see for the first time. There is the link to the job I am talking about: https://app.circleci.com/pipelines/github/membraneframework/membrane_core/4128/workflows/536725be-8718-4158-90a5-b7b28ec10189/jobs/14079

2025-01-20 11:55 UTC, wende commented on lib/membrane/core/telemetry.ex
> +        def handler_measured?(unquote(component), _), do: false
Good catch. The catch-all case at the bottom was added later

2025-01-20 12:10 UTC, wende commented on lib/membrane/core/telemetry.ex
> +    Map.take(state, @public_state_keys[struct])
So what you mean is to pass the entire state to the end user, but document only the fields that are considered public?

2025-01-20 13:52 UTC, FelonEkonom commented on lib/membrane/core/telemetry.ex
> +    Map.take(state, @public_state_keys[struct])
Yes

2025-01-21 15:29 UTC, FelonEkonom reviewed
It would be nice to have a piece of documentation that describes
 - how to enable metrics in config
 - what events are emitted and when
 - what is passed as events metadata
but you can wait with it until the code and API are more or less stable within this PR

Another thing is, please take a look at the CI: `test_performance` job doesn't work at all for now, but `test` and `lint` should pass

2025-01-21 15:29 UTC, FelonEkonom commented on test/membrane/telemetry_test.exs
> +      Process.flag(:trap_exit, true)
Use `Testing.Pipeline.start_supervised!/1` and remove `Process.flag(:trap_exit, true)`.

I recommend you to avoid using `Process.flag(:trap_exit, true)` when it is possible, the bugs that might be caused by it sometimes are hard to be found  🐛

2025-01-21 15:29 UTC, FelonEkonom commented on test/test_helper.exs
> -# ExUnit.start(exclude: [:long_running], assert_receive_timeout: 500)
👍

2025-01-21 15:29 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
If we had some `:telemetry` metrics, that were emitted, I wouldn't remove them because of the backwards compatibility, but IMO the main goal is to have new, well designed and documented metrics that will allow us to plug something more or less like [this](https://github.com/membraneframework-labs/membrane_opentelemetry_plugs)

2025-01-22 11:17 UTC, varsill commented
@wende @FelonEkonom performance tests should be fixed, you just need to merge changes from current master branch for them to run properly

2025-01-24 11:22 UTC, wende commented on lib/membrane/core/callback_handler.ex
> +        )
The purpose of `Telemetry.state_result` was exactly that to avoid circular dependency. I did incorrectly use it after all though. 
Take a look at the most recent version. I don't believe there is a way to avoid circ dependency with a macr. Using this `state_result/2` workaround while not ideal achieves better decoupling.

2025-01-24 11:23 UTC, wende commented on test/membrane/telemetry_test.exs
> +  @moduletag :telemetry
None. Deleted :+1:

2025-01-24 11:23 UTC, wende commented on test/membrane/telemetry_test.exs
> +    ref = make_ref()
Done

2025-01-24 11:23 UTC, wende commented on test/membrane/telemetry_test.exs
> +      |> child(:filter, %TestFilter{target: self()})
Fixed

2025-01-24 11:31 UTC, wende commented
> If we had some :telemetry metrics, that were emitted, I wouldn't remove them because of the backwards compatibility, but IMO the main goal is to have new, well designed and documented metrics that will allow us to plug something more or less like [this](https://github.com/membraneframework-labs/membrane_opentelemetry_plugs)

 I am planning to restore these in accordance with new changes. Please keep in mind though that these were calls at the very heart of the core functionality while being 100% uncovered by tests. I want to make sure these are properly TDDed before they are reintroduced

2025-01-24 11:37 UTC, wende commented on lib/membrane/telemetry.ex
> +          component_path: Membrane.ComponentPath.path(),
The change is valid, but right now I realized that it would break backwards compatibility, so I'll reverse it back to the original

2025-01-24 11:39 UTC, wende commented on lib/membrane/telemetry.ex
I addressed this ☝️ in the main comment below

2025-01-24 11:40 UTC, wende commented on lib/membrane/core/telemetry.ex
> +  # Verify at compile time that every key is actually present in Core.*.State
done

2025-01-24 11:40 UTC, wende commented on lib/membrane/core/telemetry.ex
> +    Map.take(state, @public_state_keys[struct])
done

2025-01-24 11:44 UTC, wende commented on test/membrane/telemetry_test.exs
> +      :ok = Testing.Pipeline.terminate(pid)
done

2025-01-24 11:45 UTC, wende commented on test/membrane/telemetry_test.exs
> +      assert value.duration > 0
done

2025-01-24 11:45 UTC, wende commented on test/membrane/telemetry_test.exs
> +      Process.flag(:trap_exit, true)
done

2025-01-24 13:54 UTC, wende commented on lib/membrane/core/element.ex
> +          parent: pid(),
I changed it across core/element, core/bin and core/pipeline to follow elixir style guidelines and be consistent with the rest of the codebase. Let me know if putting it in this PR is overstepping

2025-01-24 13:58 UTC, wende commented on test/membrane/telemetry_test.exs
> +  end
These tests are a placeholder. I plan on extending them to cover idiosyncrasies of each individual metric

2025-01-24 14:13 UTC, wende commented on lib/membrane/core/telemetry.ex
> +      value = Enum.reduce(List.wrap(buffers), 0, &(&2 + Membrane.Payload.size(&1.payload)))
This currently crashes in tests, because some teasts pass integers as buffer. Which, although allowed by documentation and typespecs, does not implement standard functions like size/1 causing this to crash.

Let me know should I account for integer buffers here or add an implementation of `Membrane.Payload` for integers, or change the tests that are failing

2025-01-24 14:20 UTC, wende commented on lib/membrane/core/telemetry.ex
> +      measurement
I reimplemented metrics for: `[link, buffer, bitrate, queue, stream_format, event, store]`

2025-01-24 14:21 UTC, wende commented on lib/membrane/telemetry.ex
> +
No longer relevant

2025-01-24 14:22 UTC, wende commented on lib/membrane/core/callback_handler.ex
> +        )
Not to mention there is little to no benefit of using a macro here, I don't think it's warranted but i'm open to discussion

2025-01-28 16:40 UTC, wende commented on lib/membrane/core/legacy_telemetry.ex
This file is almost entirely identical to what it was before this PR. Small adjustments were made to make it more resilient, discontinued telemetry events are rerouted to this module. Events that appear in both implementations are routed based on telemetry config indicating legacy format or the new one.

2025-01-28 17:05 UTC, wende commented on test/membrane/telemetry_test.exs
> +  describe "Telemetry reports pipelines'" do
There's unfortunately no tests for bin's reports since i couldn't find anything like Testing.Bin consistent with Testing.Pipeline and Testing.Element

2025-01-29 10:56 UTC, FelonEkonom commented on lib/membrane/core/element.ex
> +          parent: pid(),
It is fine

2025-01-29 15:19 UTC, FelonEkonom requested changes
Please fix `lint` CI job. 
Take a look at `test_performance` - there is a decrease in performance on this branch. Optimising code around callback execution should bring the biggest performance boost.

Please, check if you can request performance tests on CI on your own and let me know if you will meet any problems with it.

Add a very short description of this PR on the top of `CHANGELOG.md` file.

2025-01-29 15:19 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> +  It is user's responsibility to use some sort of event consumer and metric reporter
```suggestion
  It is user's responsibility to use some sort of event handler and metric reporter
```

2025-01-29 15:19 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> +      * `:exception` - when the handler crashes during execution
`handler` in `:telemetry` documentation is used as a name of a function that is attached to an event, so I would avoid using this word in our documentation to describe things different than that 

https://hexdocs.pm/telemetry/telemetry.html

2025-01-29 15:19 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> -  * `:take_and_demand` - reports the current size of a input buffer when taking buffers and making a new demand
If I understand correctly, these two should be restored

2025-01-29 15:24 UTC, FelonEkonom commented on lib/membrane/core/telemetry.ex
> +      value = Enum.reduce(List.wrap(buffers), 0, &(&2 + Membrane.Payload.size(&1.payload)))
Generating a metric only if a payload is binary is OK (like you did it now)

2025-01-30 09:50 UTC, mat-hek commented on lib/membrane/core/telemetry.ex
> +  @type telemetry_result() :: {:telemetry_result, {any(), list(), map(), map(), map()}}
🤔

2025-01-30 09:50 UTC, mat-hek commented on lib/membrane/core/telemetry.ex
> +      {:telemetry_result, {result, _, _, _, _}} = f.()
This wraps every callback with an additional lambda call even if telemetry is disabled. Since the `:telemetry.span` function basically emits `start` and `stop` events, wouldn't it be better to emit them manually?

2025-01-30 09:50 UTC, mat-hek commented on lib/membrane/telemetry.ex
>          }
I see some fields here that are not part of the callback context, like `pads_info`. Others have different names, such as `pads_data`. I don't think we should make too many internal fields public, as they may change

2025-01-30 11:17 UTC, wende commented on test/membrane/telemetry_test.exs
> +      assert meta.duration > 0
It's calculated on monotonic time so it's impossible to be 0. But i don't have a strong feeling about changing it to >=

2025-01-30 11:22 UTC, wende commented on lib/membrane/core/telemetry.ex
> +      {:telemetry_result, {result, _, _, _, _}} = f.()
That's true, i didn't consider it to be deal-breaking since the lambda calls are virtually free. I could change it to a macro to make it more inlined at compile time, didn't want to prematurely optimize though

2025-01-30 11:23 UTC, wende commented on lib/membrane/core/telemetry.ex
> +  @type telemetry_result() :: {:telemetry_result, {any(), list(), map(), map(), map()}}
Yeah, it's not very self explanatory, is it 😅

2025-01-30 11:24 UTC, wende commented on lib/membrane/core/telemetry.ex
> +  end
It can be tested by uncommenting what's in the config. I did run it to confirm it works as intended and it didn't seem to have a problem with that

2025-01-30 11:25 UTC, wende commented on test/membrane/telemetry_test.exs
> +      Process.flag(:trap_exit, true)
Yeah I recovered it when doing some trial and error tests. Forgot to remove it after all. On it

2025-01-30 11:31 UTC, wende commented on test/membrane/telemetry_test.exs
> +        assert meta.system_time > 0
This is returned from `:telemetry.span` so I don't have control over the contents of this result. It does however return both system_time and monotonic_time

2025-01-30 11:33 UTC, wende commented on lib/membrane/core/telemetry.ex
> +  # Verify at compile time that every key is actually present in Core.*.State
No longer relevant

2025-01-30 11:41 UTC, wende commented on config/config.exs
> +  # ]
I think I want to leave it in some documentation since it makes it much easier to manually test behaviour on legacy settings. Any idea where I could put it?

2025-01-30 11:43 UTC, wende commented on lib/membrane/core/callback_handler.ex
> +        )
```
def apply_within_span(lambda, callback, callback_args, internal_state, state) do
  report_span(
    state.__struct__,
    callback,
    fn -> apply(lambda) |> state_result(internal_state, state) end
  )
end
```

This solution has the problem that internal state passed this way would be an old internal state, instead of the new one

2025-01-30 11:45 UTC, wende commented on test/membrane/telemetry_test.exs
> +      Process.flag(:trap_exit, true)
Done

2025-01-30 11:47 UTC, wende commented on lib/membrane/core/element.ex
> +      Telemetry.report_queue_len(self())
All calls that were removed go directly to LegacyTelemetry so that they can be easily identified to be removed later on. Those that are both in the old and the new one go to Telemetry that redirects the calls based on the config having old or new format. When the legacy telemetry is removed this will allow it only to delete lines with LegacyTelemetry as well as the small block of redirection in new Telemetry

2025-01-30 11:54 UTC, wende commented on lib/membrane/telemetry.ex
>          }
This is a contentious issue. Because internal state is available both before and after the call . Higher state however is not, so merging them together may be confusing

2025-01-30 11:57 UTC, wende commented on lib/membrane/telemetry.ex
>          }
@mat-hek Could you revise the metadata above to remove some fields that are unnecessary? I'm not familiar with state of the components enough to make that decision myself

2025-01-30 11:58 UTC, wende commented on test/membrane/telemetry_test.exs
> +      assert meta.duration > 0
Good catch. I made the change without verifying its validity. Thanks 👍

2025-01-30 12:12 UTC, wende commented on lib/membrane/telemetry.ex
> -  * `:take_and_demand` - reports the current size of a input buffer when taking buffers and making a new demand
1. Take was removed by me incorrectly. Which would break backwards compatibility so good catch
2. Demand is an interesting metric because although defined it was actually never implemented anywhere in the codebase. Should I add it myself?

2025-01-30 12:21 UTC, wende commented on config/config.exs
> +    events: :all
The word :metrics is terribly confusing. Since there is no metric. They are telemetry logs or telemetry events. Metrics would be something that aggregates them, which we don't do. Not to mention the whole Telemetry.Metrics confusion on top of that.

> Do I understand correctly:
Legacy API is still supported, but there is a new API that covers new callback events and legacy events as well?
Correct me if I am wrong

Depending on the format of configuration, new telemetry will reroute calls to the old module if it discovers configuration to be of old telemetry system.
```elixir
...
if @legacy? do
      do_legacy_telemetry(event_name, lazy_block)
else
...
```

If the format is consistent with new changes it will use the new Telemetry instead

2025-01-30 12:22 UTC, wende commented on lib/membrane/core/legacy_telemetry.ex
> +                &(Membrane.Core.LegacyTelemetry.get_payload_size(&1.payload) + &2)
done

2025-01-30 12:22 UTC, wende commented on lib/membrane/core/legacy_telemetry.ex
> +            |> inspect()
done

2025-01-30 15:59 UTC, FelonEkonom commented on test/membrane/telemetry_test.exs
> +        assert meta.system_time > 0
so please assert on `monotonic_time`

2025-01-31 13:37 UTC, FelonEkonom commented on lib/membrane/core/callback_handler.ex
> +        )
You can get the new one from the value returned from `apply(lambda)`

2025-01-31 14:20 UTC, FelonEkonom commented on lib/membrane/core/callback_handler.ex
> +        )
For me it is overcomplicated and I still think that it is possible to write functions in `Membrane.Core.Telemetry` in a way that they will be much more intuitive to read. We can do pair-coding session to do so

2025-01-31 14:31 UTC, FelonEkonom commented on test/membrane/telemetry_test.exs
> +        assert results.monotonic_time < 0
Why do you check, if `monotonic_time` is smaller than zero? Shouldn't it be a positive number?

2025-01-31 14:31 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> +      * `:exception` - when the handler crashes during execution
It is still undone

2025-01-31 14:32 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> -  * `:take_and_demand` - reports the current size of a input buffer when taking buffers and making a new demand
Don't add it if it hasn't been implemented before, leave it as it was

2025-01-31 14:46 UTC, wende commented on lib/membrane/telemetry.ex
> +      * `:exception` - when the handler crashes during execution
I changed it to "component handler" to distinguish between the two

2025-01-31 14:48 UTC, wende commented on test/membrane/telemetry_test.exs
> +        assert results.monotonic_time < 0
On systems I checked at the monotonic time was always negative. But I did some research and it appears it can be positive on some systems. I'll change it to just be different than 0 to make sure it doesn't fail randomly for some

2025-01-31 14:53 UTC, FelonEkonom requested changes

2025-01-31 14:53 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> +
This is for legacy events, right?

2025-01-31 14:53 UTC, FelonEkonom commented on lib/membrane/core/element/stream_format_controller.ex
> +      Telemetry.report_stream_format(stream_format, inspect(pad_ref))
Shouldn't it be in legacy telemetry?

2025-01-31 14:53 UTC, FelonEkonom commented on lib/membrane/core/telemetry.ex
> +          component_context: Membrane.Telemetry.component_context()
please add `module`, component_path and `setup_incomplete?` (the last one is the value stored in state) to `Membrane.Element/Bin/Pipeline.CallbackContext.t()` and to values returned from functions defined in  `Membrane.Core.Element/Bin/Pipeline.CallbackContext`

Since `module` will be inside callback_context, there will be no need to have it explicitly in `telemetry_callback_metadata`

2025-01-31 14:53 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> +          Element.CallbackContext.t() | Bin.CallbackContext.t() | Pipeline.CallbackContext.t()
Rename it to `callback_context`

2025-01-31 14:53 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> -  * `:take_and_demand` - reports the current size of a input buffer when taking buffers and making a new demand
Add a mention, that `events` will be removed in `v2.0`

2025-01-31 14:53 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> +        }
Do you have any idea what prefix could be added to names of these two types, to avoid confusion if it has anything to do with newly added callback events?

2025-02-04 11:18 UTC, FelonEkonom requested changes
@wende are you planning on making any major changes to the documentation?

2025-02-04 11:18 UTC, FelonEkonom commented on lib/membrane/core/callback_handler.ex
> +      }
Let's move creating this map into `Telemetry.span_component_callback/4`

2025-02-04 11:18 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> +          internal_state_after: Element.state() | Bin.state() | Pipeline.state() | nil
Let's rename fields `internal_state_before` and `internal_state_after` to `state_before_callback` and `state_after_callback`.

The name `internal_state` occurs only inside `membrane_core` private modules and nowhere beyond them. In every other place it is called just `state`

2025-02-04 11:18 UTC, FelonEkonom commented on config/config.exs
>    # config :membrane_core, :telemetry_flags, [
I would remove the legacy config

2025-02-04 11:18 UTC, FelonEkonom commented on lib/membrane/core/telemetry.ex
> +  def span_component_callback(f, component_module, callback, meta) do
```suggestion 
 def apply_callback_within_span(callback_lambda, component_module, callback, meta) do
```
IMO name of this function is little weird

2025-02-04 11:18 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
>        * `:exception` - when the component's handler crashes during execution
```suggestion
      * `:start` - when the components begins callback's execution
      * `:stop` - when the components finishes callback's execution
      * `:exception` - when the component crashes during callback's execution
```

2025-02-04 15:06 UTC, wende commented
> @wende are you planning on making any major changes to the documentation?
Not unless they're needed. I want to have this merged as soon as possible and the documentation can always be improved upon without breaking changes

2025-02-04 15:19 UTC, wende commented on lib/membrane/core/telemetry.ex
> +  def span_component_callback(f, component_module, callback, meta) do
It uses span as a verb, but I'll find a better name for it

2025-02-04 15:30 UTC, wende commented on lib/membrane/core/telemetry.ex
> +  def span_component_callback(f, component_module, callback, meta) do
What do you think of "track_callback_handler" it has less ambiguous verb, it still specifies it's for a callback and also adds handler to be more descriptive and consistent with "callback_tracked?/1" function name

2025-02-05 10:58 UTC, mat-hek commented on config/config.exs
> +    datapoints: :all
IIRC, this enables the old, deprecated metrics. Why do we add a new config key for a deprecated feature?

2025-02-05 14:20 UTC, wende commented on config/config.exs
> +    datapoints: :all
It's not for deprecated metrics. It's for those that were renewed. So:
link, buffer, queue_len, stream_format, event, store and take (no bitrate, demand, init or terminate)

And it's only for those to be tested

2025-02-05 14:21 UTC, mat-hek approved these changes

2025-02-06 10:21 UTC, FelonEkonom approved these changes
Fix these two things and it should be fine

2025-02-06 10:21 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> -  * `:take_and_demand` - reports the current size of a input buffer when taking buffers and making a new demand
> Add a mention, that events will be removed in v2.0

Undone

2025-02-06 10:21 UTC, FelonEkonom commented on lib/membrane/telemetry.ex
> +    where handler is any possible handle_* function defined for a component.
```suggestion
    * `[:membrane, :element | :bin | :pipeline, callback, :start | :stop | :exception]` -
    where `callback` is any possible handle_* function defined for a component.
```

2025-02-06 13:27 UTC, merged