More docs for v1.2
membraneframework/membrane_core pull request #923
Opened 2024-12-19 16:51 UTC by FelonEkonom

Closes #872 

- [x] specs examples, including mermaid graphs visualizing children topology
- [x] examples of starting `timer` with usage of `Membrane.Time` (`Membrane.Time` was the problem)
- [x] lifecycle of Element / Bin / Pipeline

2025-01-08 09:07 UTC, varsill requested changes

2025-01-08 09:07 UTC, varsill commented on guides/timer.md
> +        else: []
How about moving stream format sending to the `handle_playing` callback? I think it's more common to do it this way and we won't need to tinker around context

2025-01-08 09:07 UTC, varsill commented on guides/timer.md
> +        # let's postopne pausing :my_timer to the upcomping handle_tick
```suggestion
        # let's postpone pausing :my_timer to the upcoming handle_tick
```

2025-01-08 09:07 UTC, varsill commented on guides/components_lifecycle.md
> +When an element determines that it will no longer send buffers from a specific pad, it can return `:end_of_stream` action to that pad. The linked element receives this in `handle_end_of_stream/3`. Th
```suggestion
When an element determines that it will no longer send buffers from a specific pad, it can return `:end_of_stream` action to that pad. The linked element receives it in `handle_end_of_stream/3`. The parent component (either a Bin or Pipeline) is notified via `handle_element_end_of_stream/4`.
```

2025-01-08 09:07 UTC, varsill commented on guides/components_lifecycle.md
> +Typically, the last callback executed within a Membrane Component is `handle_terminate_request`. By default, it returns a `terminate: :normal` action, concluding the component's lifespan with the rea
I am not sure the phrase "concluding the component's lifespan" is widely recognized :D How about something simpler, just like "terminating the component"?

2025-01-08 09:07 UTC, varsill commented on guides/components_lifecycle.md
> +The `handle_info/3` callback is present in all Membrane Components and `handle_call/3` in Membrane Pipelines. These can be triggered at any time while the component is alive, functioning similarly to
```suggestion
The `handle_info/3` callback is present in all Membrane Components and `handle_call/3` in Membrane Pipelines. These can be triggered at any time while the component is alive, functioning similarly to their counterparts in `GenServer`.
```

2025-01-08 14:35 UTC, mat-hek commented on assets/images/spec_with_audio.svg
more info here https://elixirforum.com/t/using-mermaid-with-ex-doc/40727

2025-01-08 14:48 UTC, mat-hek commented on guides/components_lifecycle.md
> +For components with pads having `availability: :on_request`, the corresponding `handle_pad_added/3` callbacks are called between `handle_setup/2` and `handle_playing/2` if they are linked in the same
As we spoke recently, I believe that linking happens only after the child setup is completed, see https://github.com/membraneframework/membrane_core/blob/master/lib/membrane/core/lifecycle_controller.ex#L14 and
https://github.com/membraneframework/membrane_core/blob/ac6b793e2ea46316af569735c63dade1d83f6ddf/lib/membrane/core/parent/child_life_controller.ex#L92

2025-01-08 14:48 UTC, mat-hek commented on guides/timer.md
> +Exampls below illustrate how to use `:start_timer`, `:timer_interval` and `:stop_timer` actions on the example of `Membrane.Source`, but the API looks the same for all kinds of the Membrane Component
```suggestion
Examples below illustrate how to use `:start_timer`, `:timer_interval` and `:stop_timer` actions on the example of `Membrane.Source`, but the API looks the same for all kinds of the Membrane Components
```

put that through Grammarly to avoid typos

2025-01-08 14:48 UTC, mat-hek commented on mix.exs
> +      {:ex_doc, "0.34.2", only: :dev, runtime: false},
why this version?

2025-01-08 16:16 UTC, FelonEkonom commented on mix.exs
> +      {:ex_doc, "0.34.2", only: :dev, runtime: false},
I will check once again but I searched for a version that generates valid docs

2025-01-15 13:35 UTC, varsill commented on lib/membrane/pipeline/action.ex
> +  will result in having the following children's topology:
```suggestion
  will result in the following childrens' topology:
```

2025-01-15 13:35 UTC, varsill commented on guides/components_lifecycle.md
> +Events are one type of item that can be sent via an Element's pads and are managed in `handle_event/4`. Events are the only things that can travel both upstream and downstream relative to the pad’s d
```suggestion
Events are one type of data that can be sent via an Element's pads and are managed in `handle_event/4`. Events are the only items that can travel both upstream and downstream - all other types of data sent through pads have to follow the direction of the link.
```

2025-01-15 13:35 UTC, varsill commented on lib/membrane/bin/action.ex
> +  will result in having the following children's topology:
```suggestion
  will result the following children's topology:
```

2025-01-15 17:39 UTC, FelonEkonom commented on lib/membrane/pipeline/action.ex
> +  will result in having the following children's topology:
`childrens'` - are you sure? `children` is already plural 😛

2025-01-17 08:42 UTC, varsill commented on lib/membrane/pipeline/action.ex
> +  will result in having the following children's topology:
Yeah, you are right, children is already plural, so it should be `will result in the following children's topology:`

2025-01-17 08:46 UTC, varsill approved these changes
LGTM 🥇

2025-01-17 14:28 UTC, FelonEkonom commented on assets/drawio_schemes/spec_with_audio.drawio
I wasn't aware of this functionality, are you sure it can be done with SVG?

2025-01-20 09:29 UTC, mat-hek approved these changes

2025-01-20 09:46 UTC, merged